# -*- coding: utf-8 -*-
SERVICE = dict(
    slug="ai", order=2,
    for_whom=[
        {"ru": "Есть требование «внедрить ИИ», а какую именно задачу это решает — пока не сформулировано.",
         "en": "There is a requirement to \"implement AI\", but which problem it solves hasn't been articulated yet."},
        {"ru": "Хочется заменить человека моделью, и нужен честный ответ, какую часть работы ей действительно можно доверить.",
         "en": "You want to replace a person with a model and need an honest answer about which part of the work it can actually be trusted with."},
        {"ru": "Подрядчик обещает окупаемость в сотни процентов, и вы хотите проверить арифметику до подписания.",
         "en": "A supplier promises a return in the hundreds of per cent and you want the arithmetic checked before signing."},
        {"ru": "Данные чувствительные, и вопрос «где это будет работать» важнее вопроса «какую модель возьмём».",
         "en": "The data is sensitive, and \"where will this run\" matters more than \"which model shall we use\"."},
    ],
    steps=[
        ({"ru": "Выясняю, какую задачу вы решаете",
          "en": "I establish which problem you're solving"},
         {"ru": "«Внедрить ИИ» — не задача, а способ. Пока не названа задача, любое внедрение будет успешным по формальным признакам и бесполезным по существу.",
          "en": "\"Implement AI\" is a method, not a problem. Until the problem is named, any implementation will succeed formally and be useless substantively."}),
        ({"ru": "Разделяю работу на то, что можно отдать модели, и то, что нельзя",
          "en": "I split the work into what a model may take and what it may not"},
         {"ru": "Граница проходит не по сложности, а по ответственности: шаг, за который кто-то отвечает лично, автоматизируется до состояния «подготовлено к решению», но не «решено».",
          "en": "The boundary isn't drawn by difficulty but by accountability: a step somebody answers for personally can be automated to \"prepared for decision\" and no further."}),
        ({"ru": "Считаю риски, которых нет в презентации подрядчика",
          "en": "I cost the risks missing from the supplier's deck"},
         {"ru": "Утечка данных, галлюцинации в документах с юридическим весом, отсутствие ответственного за вывод, склонность к типовому решению, цена при потоке, географические ограничения и перебои связи.",
          "en": "Data leakage, hallucinations in documents with legal weight, nobody accountable for the output, a pull toward the standard answer, cost at volume, geographic restrictions and connectivity gaps."}),
        ({"ru": "Даю письменный ответ, включая вариант «не надо»",
          "en": "I give a written answer, including \"don't\""},
         {"ru": "В половине случаев результат — решение без модели: шаблоны, связки между системами, бот. Оно дешевле, предсказуемее и не зависит от чужого сервиса.",
          "en": "In half the cases the answer is a solution without a model: templates, connections between systems, a bot. Cheaper, more predictable, and not dependent on somebody else's service."}),
    ],
    you_keep=[
        {"ru": "Письменный разбор с расчётом, который можно проверить и повторить",
         "en": "A written analysis with arithmetic you can check and repeat"},
        {"ru": "Разметку процесса: что можно отдать модели, что нельзя и почему",
         "en": "A map of the process: what a model may take, what it may not, and why"},
        {"ru": "Список рисков с оценкой, а не общие слова про безопасность",
         "en": "A costed list of risks rather than general words about security"},
        {"ru": "Если решение собирается — работающий контур в ваших системах",
         "en": "If something gets built — a working setup inside your systems"},
    ],
    formats=[
        ("pinpoint", {"ru": "Один вопрос: стоит ли здесь ИИ и что он даст",
                      "en": "One question: is AI right here, and what would it give"}),
        ("fast", {"ru": "Решение понятно, нужно собрать и внедрить",
                  "en": "The solution is clear; it needs building"}),
        ("flagship", {"ru": "Задача на стыке аналитики, автоматизации и разработки",
                      "en": "A problem across analysis, automation and development"}),
    ],
    case=dict(path="cases/ai-manager/",
              stat={"ru": "0 моделей в контуре", "en": "0 models in the perimeter"},
              title={"ru": "Клиент просил ИИ и получил результат без него",
                     "en": "The client asked for AI and got the result without it"},
              lead={"ru": "Шесть причин отказа от платных моделей в порядке весомости для клиента — и что собрали вместо них.",
                    "en": "Six reasons for ruling out paid models, in the order that mattered to the client — and what was built instead."}),
    reading=[("automation-consultant-role", {"ru": "Консультант по автоматизации: новая роль", "en": "The automation consultant"}),
             ("automation-instead-of-hiring", {"ru": "Автоматизация вместо найма: как посчитать", "en": "Automate or hire: the arithmetic"}),
             ("when-not-to-automate", {"ru": "Когда не нужно автоматизировать", "en": "When not to automate"})],
    not_this=[
        {"ru": "Не обучаю и не дообучаю модели: это отдельная профессия, и здесь я не она.",
         "en": "I don't train or fine-tune models: that is a separate profession and I'm not it."},
        {"ru": "Не берусь автоматизировать решения, за которые кто-то должен отвечать лично.",
         "en": "I don't automate decisions somebody has to answer for personally."},
        {"ru": "Не подтверждаю уже принятое решение о внедрении: если вывод окажется другим, я его и напишу.",
         "en": "I don't rubber-stamp a decision already made: if the conclusion differs, that is what I'll write."},
    ],
)
