# -*- coding: utf-8 -*-
SERVICE = dict(
    slug="analytics", order=3,
    for_whom=[
        {"ru": "Данные есть, а ответа нет: непонятно, какая акция сработала, откуда взялась просадка, окупается ли направление.",
         "en": "You have the data but not the answer: which promotion worked, where the dip came from, whether a line of business pays for itself."},
        {"ru": "Цифры из разных систем не сходятся, и никто не может сказать, какая из них правильная.",
         "en": "Numbers from different systems don't reconcile, and nobody can say which one is right."},
        {"ru": "Решение уже надо принимать, а расчёта под него внутри компании сделать некому.",
         "en": "A decision is due and nobody inside the company has the time to work out the numbers behind it."},
        {"ru": "Отчёт есть, он верный и на шестьдесят слайдов — и после него ничего не изменилось.",
         "en": "There is a report, it is correct, it runs to sixty slides — and nothing changed after it."},
    ],
    steps=[
        ({"ru": "Формулирую вопрос так, чтобы на него был проверяемый ответ",
          "en": "I phrase the question so it can have a checkable answer"},
         {"ru": "«Почему падает прибыль» ответа не имеет. «Какие из трёх типов акций окупились за прошлый год и на сколько» — имеет.",
          "en": "\"Why is margin falling\" has no answer. \"Which of three promotion types paid for themselves last year, and by how much\" does."}),
        ({"ru": "Свожу разрозненные выгрузки в одну картину",
          "en": "I pull the scattered exports into a single picture"},
         {"ru": "Обычно самая трудоёмкая часть и самая полезная: половина расхождений между системами объясняется на этом шаге, ещё до анализа.",
          "en": "Usually the most laborious part and the most useful: half the discrepancies between systems get explained here, before any analysis."}),
        ({"ru": "Проверяю гипотезы, в том числе неудобные",
          "en": "I test the hypotheses, including the uncomfortable ones"},
         {"ru": "Включая ту, что эффекта нет вовсе. Если данные не позволяют ответить уверенно, я говорю это, а не подгоняю вывод под ожидание.",
          "en": "Including the one where there is no effect at all. If the data can't support a confident answer, I say so rather than fitting the conclusion to the expectation."}),
        ({"ru": "Отдаю письменный ответ с расчётом, который вы повторите сами",
          "en": "I hand back a written answer with arithmetic you can repeat"},
         {"ru": "Не презентация «куда двигаться», а вывод с показанным ходом расчёта и оговорками о том, чего он не доказывает.",
          "en": "Not a deck about where to go next, but a conclusion with the arithmetic shown and caveats about what it doesn't prove."}),
    ],
    you_keep=[
        {"ru": "Сведённые данные в редактируемом виде, а не картинки",
         "en": "The consolidated data in editable form, not pictures"},
        {"ru": "Расчёт, который можно повторить и проверить",
         "en": "Arithmetic you can repeat and check"},
        {"ru": "Письменный ответ с оговорками о границах вывода",
         "en": "A written answer with caveats about the limits of the conclusion"},
        {"ru": "Список того, что стоит померить в следующий раз, чтобы ответ был крепче",
         "en": "A list of what to measure next time so the answer gets stronger"},
    ],
    formats=[
        ("pinpoint", {"ru": "Один конкретный вопрос с письменным ответом",
                      "en": "One specific question, answered in writing"}),
        ("flagship", {"ru": "Данные разъехались и надо разбираться со всем контуром",
                      "en": "The data has drifted and the whole picture needs untangling"}),
    ],
    case=dict(path="cases/",
              stat={"ru": "+22% ROI акций", "en": "+22% promo ROI"},
              title={"ru": "Какие акции действительно окупаются", "en": "Which promotions actually pay"},
              lead={"ru": "Сеть из 25 магазинов, четыре типа промо и честная оговорка о том, чего эти 22% не доказывают.",
                    "en": "A 25-store chain, four promotion types, and an honest caveat about what those 22% don't prove."}),
    reading=[("audit-nobody-reads", {"ru": "Аудит, который никто не читает", "en": "The audit nobody reads"}),
             ("how-much-does-business-consulting-cost", {"ru": "Сколько стоит бизнес-консалтинг", "en": "What business consulting costs"}),
             ("silent-failure-mode", {"ru": "Тихий отказ: сигналы, которых не слышно", "en": "The silent failure mode"})],
    not_this=[
        {"ru": "Не строю дашборды как самоцель: сначала вопрос, потом форма ответа.",
         "en": "I don't build dashboards as an end in themselves: the question comes first, the format of the answer second."},
        {"ru": "Не даю прогнозов там, где данных для прогноза нет, — говорю, что их нет.",
         "en": "I don't forecast where the data can't support a forecast — I say that it can't."},
        {"ru": "Не работаю без доступа к данным: анализ по пересказу это не анализ.",
         "en": "I don't work without access to the data: analysis from hearsay isn't analysis."},
    ],
)
