# -*- coding: utf-8 -*-
SERVICE = dict(
    slug="automation", order=1,
    for_whom=[
        {"ru": "Рутина съедает часы каждую неделю: перенос данных между системами, однотипные документы, разбор почты, согласования.",
         "en": "Routine eats hours every week: moving data between systems, producing the same documents, triaging mail, chasing approvals."},
        {"ru": "Готовое no-code решение не подходит, а нанимать разработчика в штат ради одной задачи дорого и долго.",
         "en": "An off-the-shelf no-code tool doesn't fit, and hiring a developer for one task is slow and expensive."},
        {"ru": "Процесс существует давно, но целиком его не описывал никто — и версии разных людей расходятся после третьего шага.",
         "en": "The process has run for years but nobody ever wrote it down end to end — and different people's accounts diverge after step three."},
        {"ru": "Уже был подход к автоматизации, и он оставил после себя систему, которую некому поддерживать.",
         "en": "There was an earlier attempt at automation, and it left behind a system nobody can maintain."},
    ],
    steps=[
        ({"ru": "Разбираю процесс по шагам, а не по должностям",
          "en": "I map the process as steps, not job titles"},
         {"ru": "Разговариваю с теми, кто делает работу руками. Разница между регламентом и тем, как идёт работа на самом деле, — основной материал.",
          "en": "I talk to the people who do the work by hand. The gap between the policy and how the work actually runs is the raw material."}),
        ({"ru": "Отделяю рутину от решений",
          "en": "I separate routine from decisions"},
         {"ru": "Рутина воспроизводима и не содержит выбора. Решение — точка, где возможны два исхода и один дороже. Смешивать их — самая частая ошибка внедрения.",
          "en": "Routine is reproducible and contains no choice. A decision is a point where two outcomes are possible and one costs more. Mixing them is the most common implementation error."}),
        ({"ru": "Считаю, что стоит автоматизировать, а что чинить",
          "en": "I work out what to automate and what to fix"},
         {"ru": "Доля исключений выше 20% означает переработку процесса до автоматизации. Иногда честный вывод — не делать ничего, и я его говорю.",
          "en": "An exception rate above 20% means redesigning the process first. Sometimes the honest answer is to do nothing, and I say so."}),
        ({"ru": "Собираю, тестирую на реальных данных и передаю",
          "en": "I build it, test on real data and hand it over"},
         {"ru": "Всё живёт в ваших системах с первого дня. Документация такая, чтобы процесс поднял другой человек. Названный владелец до запуска, а не после.",
          "en": "Everything lives in your systems from day one. Documentation good enough for somebody else to stand it up. A named owner before launch, not after."}),
    ],
    you_keep=[
        {"ru": "Процессы автоматизации в вашем контуре, доступы у вас",
         "en": "The automation running inside your perimeter, with you holding access"},
        {"ru": "Шаблоны и таблицы, по которым всё собирается",
         "en": "The templates and spreadsheets everything is built from"},
        {"ru": "Документацию, достаточную для поддержки без меня",
         "en": "Documentation sufficient to maintain it without me"},
        {"ru": "Ответ на вопрос «как мы узнаем, что это перестало работать правильно»",
         "en": "An answer to \"how would we know this stopped being correct\""},
    ],
    formats=[
        ("fast", {"ru": "Задача уже сформулирована, нужно собрать и внедрить",
                  "en": "The task is defined; it needs building and shipping"}),
        ("flagship", {"ru": "Непонятно, где заканчивается задача и с чего начинать",
                      "en": "Where the task starts and ends isn't clear yet"}),
    ],
    case=dict(path="cases/ai-manager/",
              stat={"ru": "−60% рутины", "en": "−60% routine"},
              title={"ru": "ИИ-менеджер вместо найма", "en": "AI manager instead of a hire"},
              lead={"ru": "Заполненное ТЗ по проекту целиком: разметка 80/20, оценка пригодности и почему в итоге обошлись без ИИ.",
                    "en": "The full brief for the project: the 80/20 split, the fitness score, and why it ended up without AI."}),
    reading=[("when-not-to-automate", {"ru": "Когда не нужно автоматизировать", "en": "When not to automate"}),
             ("automation-instead-of-hiring", {"ru": "Автоматизация вместо найма: как посчитать", "en": "Automate or hire: the arithmetic"}),
             ("small-business-automation-guide", {"ru": "Что автоматизировать первым", "en": "What to automate first"})],
    not_this=[
        {"ru": "Не строю платформу «на вырост» — собираю решение под конкретный процесс.",
         "en": "I don't build a platform \"for future growth\" — I build for the actual process."},
        {"ru": "Не беру постоянную поддержку чужого кода как отдельную услугу.",
         "en": "I don't take on ongoing maintenance of somebody else's codebase as a standalone service."},
        {"ru": "Не автоматизирую процесс, который никто не может описать целиком: сначала описание.",
         "en": "I don't automate a process nobody can describe end to end: the description comes first."},
    ],
)
