# -*- coding: utf-8 -*-
SERVICE = dict(
    slug="project-management", order=4,
    for_whom=[
        {"ru": "Проект идёт, сроки едут, и на вопрос «где мы сейчас» каждый отвечает по-своему.",
         "en": "The project is running, dates keep slipping, and \"where are we now\" gets a different answer from everyone."},
        {"ru": "Есть подрядчик и есть договор, но нет никого, кто с вашей стороны читает его результаты по существу.",
         "en": "There is a contractor and a contract, but nobody on your side reads the deliverables on the merits."},
        {"ru": "Внедрение застряло между отделами: каждый сделал свою часть, а вместе не работает.",
         "en": "A rollout is stuck between departments: everyone did their part and the parts don't fit."},
        {"ru": "Решения принимаются на совещаниях и там же теряются — через месяц никто не помнит, почему выбрали так.",
         "en": "Decisions get made in meetings and lost in the same meetings — a month later nobody remembers why."},
    ],
    steps=[
        ({"ru": "Собираю фактическое состояние, а не отчётное",
          "en": "I establish the actual state, not the reported one"},
         {"ru": "Что сделано и принято, что сделано и не принято, что считается сделанным по недоразумению. Обычно третья группа и есть источник срыва сроков.",
          "en": "What is done and accepted, what is done and not accepted, and what is believed done by misunderstanding. The third group is usually where the slippage lives."}),
        ({"ru": "Фиксирую определение готовности и список недоделанного",
          "en": "I write down the definition of done and the list of undone work"},
         {"ru": "Приём из Large-Scale Scrum: отгружаемое = определение готовности + недоделанное. Пока недоделанное не названо вслух, оно считается нулём и всплывает в конце.",
          "en": "A Large-Scale Scrum habit: shippable = definition of done + undone work. Until the undone work is named out loud it counts as zero and surfaces at the end."}),
        ({"ru": "Ставлю допуски и правило эскалации",
          "en": "I set tolerances and an escalation rule"},
         {"ru": "По шести измерениям PRINCE2: сроки, деньги, объём, качество, риск, выгода. Внутри допуска — решает исполнитель, за границей — поднимается наверх. Это снимает половину совещаний.",
          "en": "Across the six PRINCE2 dimensions: time, cost, scope, quality, risk, benefit. Inside tolerance the doer decides; outside it, it escalates. That removes half the meetings."}),
        ({"ru": "Ввожу журнал решений",
          "en": "I introduce a decision log"},
         {"ru": "Одна строка на решение: что решили, из каких вариантов, кто решил, что должно случиться, чтобы решение пересмотреть. Через полгода это единственное, что спасает от повторного спора.",
          "en": "One line per decision: what was decided, out of which options, by whom, and what would have to happen to revisit it. Six months later it's the only thing that stops the argument repeating."}),
        ({"ru": "Передаю управление вам и ухожу",
          "en": "I hand the controls back and step out"},
         {"ru": "Цель — не остаться в проекте, а оставить схему, по которой он ведётся без меня. Если через месяц после моего ухода всё разъехалось, работа сделана плохо.",
          "en": "The goal isn't to stay in the project but to leave behind a scheme that runs without me. If it falls apart a month after I leave, the work was bad."}),
    ],
    you_keep=[
        {"ru": "Реестр статусов: сделано / принято / недоделано, с именами и датами",
         "en": "A status register: done / accepted / undone, with names and dates"},
        {"ru": "Письменное определение готовности, о которое можно опереться в споре с подрядчиком",
         "en": "A written definition of done you can lean on in a dispute with a contractor"},
        {"ru": "Таблицу допусков и правило, когда вопрос поднимается наверх",
         "en": "A tolerance table and the rule for when a question escalates"},
        {"ru": "Журнал решений и шаблон, чтобы вести его дальше самим",
         "en": "A decision log and the template to keep it going yourself"},
    ],
    formats=[
        ("pinpoint", {"ru": "Разобрать один застрявший проект и написать, где он стоит",
                      "en": "Untangle one stuck project and put in writing where it stands"}),
        ("flagship", {"ru": "Внедрение или программа, где участвуют несколько сторон",
                      "en": "A rollout or programme with several parties involved"}),
        ("reserve", {"ru": "Читать результаты подрядчика и держать журнал решений помесячно",
                     "en": "Reading contractor deliverables and keeping the decision log month to month"}),
    ],
    case=dict(path="cases/ai-manager/",
              stat={"ru": "ТЗ целиком", "en": "The whole brief"},
              title={"ru": "Кейс как заполненное ТЗ", "en": "A case as a filled brief"},
              lead={"ru": "Не рассказ о проекте, а рабочий документ по нему — с пояснениями, почему каждый ответ сформулирован именно так.",
                    "en": "Not a story about a project but the working document behind it, with notes on why each answer is worded that way."}),
    reading=[("erp-implementation-failure-reasons",
              {"ru": "Почему проваливаются внедрения ERP", "en": "Why ERP rollouts fail"}),
             ("lidl-digital-transformation-failure",
              {"ru": "Как Lidl потерял 500 миллионов", "en": "How Lidl lost 500 million"}),
             ("informal-org-structures",
              {"ru": "Неформальные структуры внутри компании", "en": "The informal org chart"})],
    not_this=[
        {"ru": "Не заменяю вашего руководителя проекта насовсем: я ставлю схему и ухожу, а не занимаю ставку.",
         "en": "I don't permanently replace your project manager: I set the scheme up and leave, I don't fill the seat."},
        {"ru": "Не веду проект, где заказчик не готов принимать решения, — управлять нечем.",
         "en": "I don't run a project where the client won't make decisions — there's nothing to manage."},
        {"ru": "Не занимаюсь сертификацией и внедрением методологии ради методологии: беру из PRINCE2 и LeSS то, что решает вашу задачу.",
         "en": "I don't do certification or methodology for its own sake: I take from PRINCE2 and LeSS what solves your problem."},
    ],
)
