# -*- coding: utf-8 -*-
SERVICE = dict(
    slug="web", order=5,
    for_whom=[
        {"ru": "Сайт есть, трафик есть, заявок нет — и непонятно, на каком шаге люди уходят.",
         "en": "The site exists, the traffic exists, the enquiries don't — and it's unclear at which step people leave."},
        {"ru": "Нужны две-три языковые версии, и переводом дело не решается: у аудиторий разные вопросы.",
         "en": "You need two or three language versions, and translation doesn't solve it: the audiences ask different questions."},
        {"ru": "Сайт делали давно и в спешке, править его дороже, чем собрать заново.",
         "en": "The site was built long ago in a hurry, and patching it costs more than rebuilding."},
        {"ru": "Нужен рабочий сайт под конкретную задачу, а не витрина на полгода согласований.",
         "en": "You need a working site for a specific job, not a showcase that takes six months to sign off."},
    ],
    steps=[
        ({"ru": "Начинаю с того, что должно произойти после визита",
          "en": "I start from what should happen after the visit"},
         {"ru": "Заявка, звонок, скачивание, запись — что-то одно. Сайт без названного целевого действия нельзя ни спроектировать, ни потом оценить.",
          "en": "An enquiry, a call, a download, a booking — one thing. A site with no named target action can neither be designed nor judged afterwards."}),
        ({"ru": "Разбираю путь до этого действия по шагам",
          "en": "I break the path to that action into steps"},
         {"ru": "Где человек не понял, где не поверил, где не нашёл. Это три разные проблемы, и лечатся они разным.",
          "en": "Where the visitor didn't understand, didn't believe, didn't find. Three different problems with three different fixes."}),
        ({"ru": "Развожу языковые версии по смыслу, а не по словарю",
          "en": "I separate language versions by meaning, not by dictionary"},
         {"ru": "У русскоязычного и англоязычного посетителя разные возражения, разные привычные форматы оплаты и разное представление о том, что считается доказательством. Перевод их не выравнивает.",
          "en": "A Russian-speaking and an English-speaking visitor have different objections, different payment habits and different ideas of what counts as proof. Translation doesn't level that."}),
        ({"ru": "Собираю так, чтобы вы могли править сами",
          "en": "I build it so you can edit it yourself"},
         {"ru": "Без слоя, который знаю только я. Текст, цены и страницы меняются без моего участия — иначе через год сайт снова устареет и снова понадобится подрядчик.",
          "en": "No layer only I understand. Text, prices and pages change without me — otherwise in a year the site is stale again and a contractor is needed again."}),
        ({"ru": "Ставлю измерение и говорю, чего оно не покажет",
          "en": "I set up measurement and say what it won't show"},
         {"ru": "Несколько событий, которые действительно о чём-то говорят, вместо большой аналитики, в которую никто не заходит.",
          "en": "A few events that actually mean something, instead of a large analytics setup nobody opens."}),
    ],
    you_keep=[
        {"ru": "Сайт, который вы правите без подрядчика",
         "en": "A site you edit without a contractor"},
        {"ru": "Исходники и доступы целиком, без привязки к моей инфраструктуре",
         "en": "The sources and all accesses, with no tie to my infrastructure"},
        {"ru": "Описанный путь до целевого действия — чтобы понимать, что и зачем менять дальше",
         "en": "A written path to the target action — so you know what to change next and why"},
        {"ru": "Список того, что осталось несделанным, и во что это упрётся",
         "en": "A list of what stayed undone and what it will run into"},
    ],
    formats=[
        ("fast", {"ru": "Собрать и запустить сайт под конкретную задачу",
                  "en": "Build and launch a site for a specific job"}),
        ("pinpoint", {"ru": "Разобрать существующий сайт и написать, где теряются заявки",
                      "en": "Review the existing site and put in writing where enquiries are lost"}),
    ],
    case=dict(path="cases/",
              stat={"ru": "Запуск за 2 недели", "en": "Live in 2 weeks"},
              title={"ru": "Сайты, работающие в двух алфавитах", "en": "Sites that work in two alphabets"},
              lead={"ru": "Пять языков, две валютные зоны и разные возражения у аудиторий — почему прямой перевод не сработал.",
                    "en": "Five languages, two currency zones and audiences with different objections — why straight translation failed."}),
    reading=[("multilingual-website-not-converting",
              {"ru": "Почему многоязычный сайт не конвертирует", "en": "Why a multilingual site doesn't convert"}),
             ("infrastructure-inbreeding",
              {"ru": "Инфраструктурное инбридинг", "en": "Infrastructure inbreeding"}),
             ("small-business-automation-guide",
              {"ru": "Автоматизация малого бизнеса: с чего начать", "en": "Small business automation: where to start"})],
    not_this=[
        {"ru": "Не делаю дизайн ради дизайна: если красивее, но заявок меньше, это не сделано.",
         "en": "I don't do design for its own sake: prettier with fewer enquiries isn't done."},
        {"ru": "Не беру большие магазины с тысячами товаров и сложной логистикой — там нужна команда, а не один человек.",
         "en": "I don't take large shops with thousands of SKUs and complex logistics — that needs a team, not one person."},
        {"ru": "Не сажаю вас на платформу, из которой нельзя уйти с исходниками.",
         "en": "I don't put you on a platform you can't leave with your sources."},
    ],
)
