# -*- coding: utf-8 -*-
POST = dict(
    slug="automation-instead-of-hiring",
    date="2026-09-01",
    updated="2026-09-01",
    tag={"en": "Automation & AI", "ru": "Автоматизация и ИИ"},
    title={
        "en": "Automate or Hire: How to Actually Do the Arithmetic",
        "ru": "Автоматизация вместо найма: как посчитать честно",
    },
    h1={
        "en": "Automate or Hire: How to Do the Arithmetic Without Fooling Yourself",
        "ru": "Автоматизация вместо найма: как посчитать, что на самом деле дешевле",
    },
    dek={
        "en": "Comparing a salary to the price of software is useless: both numbers are understated, and in different directions. Here is what each side actually contains.",
        "ru": "Сравнивать зарплату со стоимостью софта бесполезно: обе цифры занижены, причём по-разному. Вот из чего на самом деле состоит каждая сторона.",
    },
    description={
        "en": "The full cost of a hire, the full cost of automation, the 80/20 split that usually wins, and the one thing that cannot be delegated to a machine at any price.",
        "ru": "Полная стоимость сотрудника, полная стоимость автоматизации, правило 80/20 и то единственное, что не делегируется машине ни за какие деньги.",
    },
    keywords={
        "en": "automate or hire, cost of automation vs employee, total cost of a hire, automation ROI, when to hire instead of automating, AI instead of a hire, process automation economics",
        "ru": "автоматизация вместо найма, стоимость сотрудника, окупаемость автоматизации, нанимать или автоматизировать, ИИ вместо сотрудника, экономика автоматизации процессов, полная стоимость найма",
    },
    hashtags=["Automation", "AI", "Hiring", "Operations", "Efficiency"],
    related=["when-not-to-automate", "small-business-automation-guide", "one-person-consulting-studio"],
    body={
        "ru": [
            ("p", "Обычно решение выглядит так: есть поток работы, которого стало слишком много, и вопрос «кого на это нанять». Иногда рядом появляется второй вариант — «а может, это автоматизировать» — и начинается сравнение: зарплата против стоимости внедрения."),
            ("p", "Это сравнение почти всегда неверное, потому что обе цифры занижены, и занижены по-разному. Зарплата — не стоимость сотрудника, а стоимость внедрения — не стоимость автоматизации."),
            ("q", "«Кого нанять на эту работу» — вопрос второй. Первый звучит иначе: должен ли этим вообще заниматься человек?"),
            ("p", "Разница не риторическая. Первый вопрос заставляет искать исполнителя под работу в том виде, в каком она сложилась. Второй позволяет заметить, что часть этой работы существует только потому, что её некому было отменить."),

            ("h2", "Что на самом деле стоит сотрудник"),
            ("p", "Оклад — это та часть, которую видно. Полная стоимость складывается ещё как минимум из пяти строк, и почти все они повторяющиеся."),
            ("table", {
                "caption": "Строки, из которых состоит стоимость сотрудника. Проценты — от годового оклада.",
                "head": ["Строка", "Порядок величины", "Почему её забывают"],
                "rows": [
                    ["Налоги и взносы работодателя", "зависит от юрисдикции, обычно +20–40%", "Считают «на руки», а платят полную"],
                    ["Рабочее место, техника, лицензии", "5–15% в год", "Разовая покупка выглядит как разовая, а обновляется регулярно"],
                    ["Выход на нормальную производительность", "1–3 месяца оклада", "Первые месяцы человек учится, а платят с первого дня"],
                    ["Время руководителя", "2–6 часов в неделю", "Не попадает ни в один бюджет, потому что руководитель уже нанят"],
                    ["Риск неудачного найма", "20–40% попыток", "Считают удачный сценарий, а платят за среднее по попыткам"],
                    ["Замена при уходе", "поиск плюс повторный разгон", "Считают, что человек останется навсегда"],
                ],
            }),
            ("p", "Числа в правой колонке — ориентиры, а не константы: подставьте свои, они у вас есть. Важен не точный коэффициент, а порядок: <strong>полная стоимость обычно в полтора-два раза выше оклада</strong>, и это повторяется каждый год."),
            ("note", "Отдельно стоит посчитать не деньги, а календарь. Между решением «нанимаем» и моментом, когда человек работает самостоятельно, обычно проходит от трёх до пяти месяцев. Если задача горит, эти месяцы — часть цены."),

            ("h2", "Что на самом деле стоит автоматизация"),
            ("p", "Здесь ошибка зеркальная. В смету попадает разработка, а из неё выпадает всё, что начинается на следующий день после запуска."),
            ("table", {
                "caption": "Стоимость автоматизации после запуска. Считается от стоимости сборки.",
                "head": ["Строка", "Порядок величины", "Когда всплывает"],
                "rows": [
                    ["Поддержка при изменениях в смежных системах", "10–20% в год, бессрочно", "Когда обновится то, к чему вы подключились"],
                    ["Обработка исключений", "может превысить саму сборку", "Со второго месяца, когда пойдут нетиповые случаи"],
                    ["Тихий отказ", "не ограничена сверху", "Тогда, когда кто-то случайно заметит"],
                    ["Потеря знания", "проявляется через год-два", "Когда понадобится изменить процесс, а помнивших его уже нет"],
                    ["Владение", "ноль в смете, дорого в реальности", "Когда автоматизация становится ничьей и начинает гнить"],
                ],
            }),
            ("p", "Подробный разбор этих издержек и того, какие процессы вообще не стоит трогать, — в статье <a href=\"../when-not-to-automate/\">когда не нужно автоматизировать</a>. Здесь важно другое: <strong>у автоматизации тоже есть повторяющаяся годовая стоимость</strong>, просто её не называют зарплатой."),

            ("h2", "Ни то, ни другое: правило восьмидесяти к двадцати"),
            ("p", "Практически всегда честный ответ — не «нанять» и не «автоматизировать», а разделить роль. Один из наших проектов начинался ровно с вопроса, вынесенного в заголовок: владелец компании в логистике собирался нанять ещё одного менеджера, а потом решил, что справится ИИ — сметы, документы, бухгалтерия, разбор почты, логистика."),
            ("p", "Шесть интервью с теми, кто эту работу делает руками, показали устойчивую пропорцию:"),
            ("ul", [
                "около <strong>80% времени</strong> уходило на настоящую рутину: перенести числа в шаблон, оформить документ, отправить типовое письмо, спросить статус;",
                "около <strong>20%</strong> — на небольшое число решений: какое отклонение поставщика принять, когда запросу клиента нужен другой коммерческий ответ, когда задержку пора эскалировать и кому;",
                "и почти <strong>весь риск</strong> жил в этих 20%. Ошибка в рутине означала переделку. Ошибка в решении означала потерянные деньги или потерянного клиента.",
            ]),
            ("p", "Поэтому решение выглядело так: автоматизировать восемьдесят процентов, оставить двадцать человеку — и, что важнее, сделать так, чтобы автоматизированная часть <em>сама приносила</em> человеку эти двадцать процентов с полным контекстом, а не голым уведомлением. Экономия вышла меньше, чем в первоначальном предложении, и продержалась."),
            ("q", "Полная автоматизация дала бы более красивую цифру в обосновании и худший результат во втором квартале."),

            ("h2", "Чего нельзя автоматизировать ни за какие деньги"),
            ("p", "Есть граница, которая не двигается ростом качества моделей, потому что она проходит не по способностям. <strong>Машина не может нести ответственность.</strong> А там, где нет ответственности, нет и гарантий."),
            ("p", "Это не абстракция. Мы делали софт, который оценивает кандидатов по косвенным признакам, и упёрлись в неожиданное: изменить наём на уровне программы невозможно, потому что рекрутер делегирует программе собственное суждение. Хуже того — если показать ему, как именно алгоритм пришёл к выводу, он согласится с этим выводом ещё сильнее."),
            ("p", "Механика здесь общая, и она касается любой автоматизации решений: <strong>объяснимость повышает доверие быстрее, чем точность</strong>. Человек, которому показали ход рассуждения, перестаёт проверять результат. Поэтому шаг, за который кто-то должен отвечать лично, автоматизируется только до состояния «подготовлено к решению», но не «решено»."),
            ("checklist", [
                "Есть ли у результата этого шага адресат, с которого можно спросить?",
                "Что произойдёт, если результат окажется неверным, и кто это заметит?",
                "Согласится ли этот человек подписаться под выводом, не проверяя его?",
                "Если да — вы автоматизировали не работу, а снятие ответственности.",
            ]),

            ("h2", "Когда нанимать всё-таки правильно"),
            ("p", "Автоматизация не универсальный ответ, и есть два случая, где наём честно выигрывает."),
            ("h3", "1. Работа не повторяется"),
            ("p", "Автоматизация окупается повторами. Если задача возникает нерегулярно, каждый раз в новой форме и требует разбираться заново, автоматизировать нечего: вы построите систему под случай, который больше не повторится в том же виде. Это ровно тот класс работы, ради которого людей и нанимают."),
            ("h3", "2. Человек способен автоматизировать себя сам"),
            ("p", "Есть специалисты, которые приходят и первым делом убирают собственную рутину: собирают себе шаблоны, скрипты, связки между системами. Такой человек стоит дороже среднего и окупается быстрее любого проекта внедрения, потому что автоматизирует не абстрактный процесс, а тот, в котором работает каждый день, и сразу видит исключения."),
            ("p", "Практический вывод для найма: <strong>спрашивайте не «какими инструментами вы владеете», а «что вы автоматизировали на прошлом месте и что из этого сломалось»</strong>. Второй вопрос отсеивает тех, кто ставил галочки в резюме."),

            ("h2", "Порядок расчёта"),
            ("p", "Если свести всё вышесказанное к процедуре, она занимает пару часов и делается до разговора с подрядчиком."),
            ("steps", [
                ("Опишите работу по шагам, а не по должности",
                 "Не «менеджер по логистике», а перечень того, что делается за неделю. Пока работа описана должностью, её нельзя разделить."),
                ("Разметьте шаги на рутину и решения",
                 "Рутина — воспроизводимая последовательность без выбора. Решение — момент, где возможны два исхода и один из них дороже."),
                ("Посчитайте часы отдельно по каждой группе",
                 "Обычно выясняется, что решений мало по времени и много по риску. Это и есть та самая пропорция."),
                ("Посчитайте полную стоимость обеих сторон",
                 "Сотрудник — по таблице выше, с налогами, разгоном и риском найма. Автоматизация — со стоимостью поддержки и обработки исключений на три года вперёд, а не на год."),
                ("Проверьте рутинную часть на пригодность",
                 "Стабильна ли она, описуема ли одинаково двумя людьми, какова доля исключений. Выше 20% исключений — сначала переделка процесса."),
                ("Назначьте владельца до старта",
                 "Автоматизация без названного ответственного за неё человека становится ничьей за один квартал."),
            ]),

            ("h2", "Что обычно получается"),
            ("p", "В небольшой компании с простыми процессами сложная автоматизация чаще всего стоит дороже, чем экономит: объёма повторов не хватает, чтобы окупить поддержку. Там выигрывает наём или пара точечных связок за неделю работы."),
            ("p", "В средних и крупных организациях всё наоборот: тысячи часов уходят в повторяющуюся отчётность, согласования, перенос данных и координацию — и там автоматизация становится стратегически интересной, потому что каждая устранённая рутина умножается на количество людей, которые ею занимались."),
            ("p", "Но и в том, и в другом случае вопрос остаётся один и тот же. Не «заменит ли ИИ людей», а <strong>какую часть работы вообще стоит оставлять человеку</strong> — и хватит ли у вас честности признать, что часть её не стоит оставлять никому."),
            ("p", "Одностраничная выжимка из этой статьи — <a href=\"{{HOME}}templates/automate-or-hire/\">чек-лист «нанимать или автоматизировать»</a>: то же самое, но в виде, который можно распечатать и заполнить."),
        ],

        "en": [
            ("p", "The decision usually arrives like this: there is more work than the team can absorb, and the question is who to hire for it. Sometimes a second option shows up — maybe this could be automated — and a comparison begins: a salary against the price of an implementation."),
            ("p", "That comparison is almost always wrong, because both numbers are understated, and understated differently. A salary is not the cost of an employee, and a build price is not the cost of automation."),
            ("q", "\"Who should we hire for this\" is the second question. The first one is different: should a person be doing this at all?"),
            ("p", "The difference is not rhetorical. The first question sends you looking for someone to do the work in the shape it has already taken. The second lets you notice that part of that work exists only because nobody was in a position to cancel it."),

            ("h2", "What an employee actually costs"),
            ("p", "The salary is the visible part. The full cost is made of at least five more lines, and nearly all of them repeat every year."),
            ("table", {
                "caption": "The lines that make up the cost of an employee. Percentages are of annual salary.",
                "head": ["Line", "Order of magnitude", "Why it gets missed"],
                "rows": [
                    ["Employer taxes and contributions", "jurisdiction-dependent, typically +20–40%", "People budget take-home and pay gross"],
                    ["Workspace, equipment, licences", "5–15% per year", "A one-off purchase looks one-off and then recurs"],
                    ["Ramp to normal productivity", "1–3 months of salary", "The first months are learning; payroll starts on day one"],
                    ["Manager's time", "2–6 hours per week", "Lands in no budget, because the manager is already hired"],
                    ["Risk of a bad hire", "20–40% of attempts", "People budget the good outcome and pay the average"],
                    ["Replacement when they leave", "search plus a second ramp", "People budget as if nobody ever leaves"],
                ],
            }),
            ("p", "The right-hand column is a set of reference points, not constants — substitute your own, you have them. What matters is not the exact multiplier but the order: <strong>the full cost is usually one and a half to two times the salary</strong>, and it repeats annually."),
            ("note", "Count the calendar separately from the money. Between deciding to hire and the person working unsupervised there are usually three to five months. If the problem is urgent, those months are part of the price."),

            ("h2", "What automation actually costs"),
            ("p", "Here the error is the mirror image. The estimate covers the build and omits everything that starts the day after launch."),
            ("table", {
                "caption": "The cost of automation after launch. Measured against build cost.",
                "head": ["Line", "Order of magnitude", "When it surfaces"],
                "rows": [
                    ["Maintenance when neighbouring systems change", "10–20% per year, indefinitely", "When whatever you connected to gets updated"],
                    ["Exception handling", "can exceed the build itself", "From month two, when the non-standard cases arrive"],
                    ["Silent failure", "unbounded", "Whenever somebody happens to notice"],
                    ["Knowledge loss", "shows up after a year or two", "When the process needs changing and nobody remembers it"],
                    ["Ownership", "zero in the estimate, expensive in reality", "When the automation becomes nobody's and starts to rot"],
                ],
            }),
            ("p", "A full breakdown of these costs, and of which processes should not be touched at all, is in <a href=\"../when-not-to-automate/\">when not to automate</a>. The point here is narrower: <strong>automation also has a recurring annual cost</strong> — it just isn't called a salary."),

            ("h2", "Neither one: the eighty-twenty rule"),
            ("p", "In practice the honest answer is almost never hire or automate, but split the role. One of our projects started with exactly the question in this headline: the owner of a logistics company was about to hire another manager, then decided AI should do the job — estimates, documents, bookkeeping, mail triage, logistics."),
            ("p", "Six interviews with the people who do that work by hand showed a stable proportion:"),
            ("ul", [
                "roughly <strong>80% of the time</strong> went to genuine routine: move numbers into a template, produce a document, send a standard follow-up, ask for status;",
                "roughly <strong>20%</strong> went to a small number of decisions: which supplier exception to accept, when a client's request needs a different commercial answer, when a delay is worth escalating and to whom;",
                "and nearly <strong>all the risk</strong> lived in that 20%. An error in the routine meant rework. An error in a decision meant lost money or a lost client.",
            ]),
            ("p", "So the answer was: automate the eighty per cent, leave the twenty with a person, and — more importantly — make the automated part <em>deliver</em> those twenty per cent to that person with full context rather than a bare notification. The saving came out smaller than the original pitch, and it held."),
            ("q", "Full automation would have produced a prettier number in the business case and a worse outcome in the second quarter."),

            ("h2", "What no budget can automate"),
            ("p", "There is a boundary that better models do not move, because it isn't drawn by capability. <strong>A machine cannot carry responsibility.</strong> And where there is no responsibility, there are no guarantees."),
            ("p", "This is not abstract. We built software that assesses candidates from indirect signals, and ran into something unexpected: hiring cannot be changed at the software level, because the recruiter delegates their own judgement to the software. Worse — show them how the algorithm reached its conclusion and they agree with that conclusion more strongly, not less."),
            ("p", "The mechanism is general, and it applies to any automated decision: <strong>explainability raises trust faster than accuracy does</strong>. A person shown the reasoning stops checking the result. So a step that somebody must answer for personally can be automated up to \"prepared for decision\" and no further."),
            ("checklist", [
                "Does the output of this step have an addressee who can be held to it?",
                "What happens if the output is wrong, and who would notice?",
                "Would that person sign off on the conclusion without checking it?",
                "If yes, you haven't automated the work — you've automated the removal of accountability.",
            ]),

            ("h2", "When hiring is genuinely the right answer"),
            ("p", "Automation is not a universal answer, and there are two cases where a hire wins honestly."),
            ("h3", "1. The work doesn't repeat"),
            ("p", "Automation pays for itself through repetition. If a task appears irregularly, in a different shape each time, and has to be worked out from scratch, there is nothing to automate: you would build a system for a case that never recurs in the same form. This is exactly the class of work people are hired for."),
            ("h3", "2. The person automates themselves"),
            ("p", "Some specialists arrive and immediately remove their own routine: they build themselves templates, scripts, connections between systems. That person costs more than average and pays back faster than any implementation project, because they are automating the process they work inside every day and can see the exceptions from the first week."),
            ("p", "The practical hiring consequence: <strong>don't ask which tools they know, ask what they automated in their last job and what part of it broke</strong>. The second question filters out people who collected badges."),

            ("h2", "The order of operations"),
            ("p", "Reduced to a procedure, this takes a couple of hours and happens before you talk to any supplier."),
            ("steps", [
                ("Describe the work as steps, not as a job title",
                 "Not \"logistics manager\" but a list of what actually gets done in a week. While the work is described by a title, it cannot be split."),
                ("Mark each step as routine or decision",
                 "Routine is a reproducible sequence with no choice in it. A decision is a point where two outcomes are possible and one of them is expensive."),
                ("Count the hours in each group separately",
                 "It usually turns out that decisions are small in time and large in risk. That is the proportion you are looking for."),
                ("Cost both sides in full",
                 "The employee from the table above, with taxes, ramp and hiring risk. The automation with maintenance and exception handling projected three years out, not one."),
                ("Test the routine part for fitness",
                 "Is it stable, would two people describe it identically, what is the exception rate? Above 20% exceptions, redesign the process first."),
                ("Name an owner before you start",
                 "Automation with nobody named as responsible for it becomes nobody's within a quarter."),
            ]),

            ("h2", "How it usually comes out"),
            ("p", "In a small company with simple processes, sophisticated automation more often costs more than it saves: there isn't enough repetition to pay back the maintenance. There, a hire wins — or a couple of targeted connections built in a week."),
            ("p", "In medium and large organisations the opposite holds: thousands of hours disappear into repeated reporting, approvals, data transfer and coordination, and automation becomes strategically interesting because every removed routine multiplies by the number of people who were doing it."),
            ("p", "But in both cases the question is the same one. Not whether AI will replace people, but <strong>which part of the work is worth leaving to a person at all</strong> — and whether you are honest enough to admit that part of it isn't worth leaving to anyone."),
            ("p", "A one-page distillation of this article — <a href=\"{{HOME}}templates/automate-or-hire/\">the automate-or-hire checklist</a>: the same thing in a form you can print and fill in."),
        ],
    },
    takeaways={
        "ru": [
            "Зарплата — не стоимость сотрудника: с налогами, техникой, разгоном, временем руководителя и риском неудачного найма полная цифра обычно в полтора-два раза выше оклада и повторяется каждый год.",
            "Стоимость сборки — не стоимость автоматизации: поддержка при изменениях смежных систем, обработка исключений, тихий отказ и потеря знания добавляют повторяющуюся годовую цену, которой нет в смете.",
            "Считайте не должность, а шаги: пока работа описана названием роли, её нельзя разделить на рутину и решения.",
            "Обычная честная пропорция — 80% рутины и 20% решений, причём почти весь риск живёт в этих 20%. Автоматизируйте первое, отдавайте второе человеку с полным контекстом.",
            "Машина не берёт ответственность, поэтому шаг, за который кто-то отвечает лично, автоматизируется до «подготовлено к решению», но не до «решено».",
            "Объяснимость повышает доверие быстрее точности: человек, которому показали ход рассуждения, перестаёт проверять результат — и это опаснее ошибки.",
            "Нанимать правильно там, где работа не повторяется, и там, где человек умеет автоматизировать себя сам.",
        ],
        "en": [
            "A salary is not the cost of an employee: with taxes, equipment, ramp, manager time and hiring risk, the full figure is usually one and a half to two times salary, and it repeats annually.",
            "A build price is not the cost of automation: maintenance when neighbouring systems change, exception handling, silent failure and knowledge loss all add a recurring annual cost that never appears in the estimate.",
            "Cost the steps, not the job title: while work is described by a role name it cannot be split into routine and decisions.",
            "The honest proportion is usually 80% routine and 20% decisions, with nearly all the risk living in the 20%. Automate the first, hand the second to a person with full context.",
            "A machine cannot carry responsibility, so a step somebody answers for personally can be automated to \"prepared for decision\" and no further.",
            "Explainability raises trust faster than accuracy: a person shown the reasoning stops checking the result, which is more dangerous than the error itself.",
            "Hiring wins where the work doesn't repeat, and where the person is capable of automating their own routine.",
        ],
    },
    faq={
        "ru": [
            ("Как понять, что дешевле — нанять или автоматизировать?",
             "Посчитайте обе стороны целиком. У сотрудника к окладу добавляются налоги и взносы, рабочее место, один-три месяца выхода на производительность, два-шесть часов в неделю времени руководителя и вероятность неудачного найма — обычно выходит в полтора-два раза выше оклада ежегодно. У автоматизации к стоимости сборки добавляются 10–20% в год на поддержку, обработка исключений, риск тихого отказа и потеря знания. Сравнивать имеет смысл только полные цифры и минимум на три года."),
            ("Какую часть работы стоит автоматизировать?",
             "Ту, которая воспроизводима и не содержит выбора. Практическая граница — доля исключений: меньше 5% обычно чисто, 5–20% зависит от цены исключения, больше 20% означает, что процесс надо сначала переделать. Решения, за которые кто-то отвечает лично, остаются человеку."),
            ("Может ли ИИ заменить менеджера?",
             "Нет, и дело не в качестве моделей. Машина не может нести ответственность, а без ответственности нет гарантий. ИИ может подготовить решение — собрать данные, показать варианты, назвать риски, — но подписывается под ним человек, и именно поэтому шаг останавливается на состоянии «подготовлено»."),
            ("Почему автоматизация решений опаснее автоматизации рутины?",
             "Из-за эффекта, который хорошо видно на найме: объяснимость повышает доверие быстрее, чем точность. Когда человеку показывают, как алгоритм пришёл к выводу, он соглашается сильнее и перестаёт проверять. В результате ошибка в решении не ловится, потому что контроль формально есть, а фактически отключён."),
            ("Когда наём выгоднее автоматизации?",
             "В двух случаях. Первый — работа не повторяется: каждый раз новая форма задачи, автоматизировать нечего. Второй — вы нанимаете человека, который сам уберёт свою рутину; он окупается быстрее любого проекта внедрения, потому что автоматизирует процесс, в котором работает каждый день, и сразу видит исключения."),
            ("Стоит ли автоматизировать в маленькой компании?",
             "Часто нет. Сложная автоматизация окупается объёмом повторов, а в небольшой компании его не хватает, чтобы покрыть стоимость поддержки. Там обычно выигрывает либо наём, либо две-три точечные связки на неделю работы. Стратегически интересной автоматизация становится там, где одна устранённая рутина умножается на десятки людей."),
        ],
        "en": [
            ("How do I tell whether hiring or automating is cheaper?",
             "Cost both sides in full. On the employee side, add employer taxes and contributions, workspace, one to three months of ramp, two to six hours a week of manager time, and the probability of a bad hire — typically one and a half to two times salary, every year. On the automation side, add 10–20% per year of maintenance, exception handling, the risk of silent failure and knowledge loss. Only full figures are comparable, and only over at least three years."),
            ("Which part of the work should be automated?",
             "The part that is reproducible and contains no choice. The practical boundary is the exception rate: under 5% is usually clean, 5–20% depends on how expensive an exception is, and above 20% means the process needs redesigning first. Decisions somebody answers for personally stay with a person."),
            ("Can AI replace a manager?",
             "No, and not because of model quality. A machine cannot carry responsibility, and without responsibility there are no guarantees. AI can prepare a decision — assemble the data, lay out the options, name the risks — but a person signs off on it, which is exactly why the step stops at \"prepared\"."),
            ("Why is automating decisions more dangerous than automating routine?",
             "Because of an effect that is very visible in hiring: explainability raises trust faster than accuracy. Show someone how the algorithm reached its conclusion and they agree more strongly and stop checking. The result is that an error in the decision goes uncaught, because oversight formally exists but has effectively been switched off."),
            ("When is hiring the better deal?",
             "In two cases. First, when the work doesn't repeat: a different shape every time, nothing to automate. Second, when you are hiring someone who will remove their own routine; they pay back faster than any implementation project, because they automate the process they work inside daily and can see the exceptions immediately."),
            ("Is automation worth it in a small company?",
             "Often not. Sophisticated automation pays back through volume of repetition, and a small company doesn't have enough of it to cover maintenance. There, a hire usually wins, or two or three targeted connections built in a week. Automation becomes strategically interesting where one removed routine multiplies across dozens of people."),
        ],
    },
)
