# -*- coding: utf-8 -*-
POST = dict(
    slug="automation-consultant-role",
    date="2026-09-08",
    updated="2026-09-08",
    tag={"en": "Automation & AI", "ru": "Автоматизация и ИИ"},
    title={
        "en": "The Automation Consultant: A Role Companies Are Starting to Need",
        "ru": "Консультант по автоматизации: новая роль",
    },
    h1={
        "en": "The Automation Consultant: The Role Companies Are Starting to Need",
        "ru": "Консультант по автоматизации: роль, которой ещё нет в штатном расписании",
    },
    dek={
        "en": "The valuable AI skill is not knowing how to use it. It is knowing where it should be used — and, more often, where it shouldn't.",
        "ru": "Ценный навык сегодня — не умение пользоваться ИИ. Это умение понимать, где его стоит применять, и, куда чаще, где не стоит.",
    },
    description={
        "en": "Why the all-rounder model stopped adding up, what questions the role asks, and why the answer is increasingly your own infrastructure.",
        "ru": "Почему модель универсального специалиста перестала сходиться, какие вопросы задаёт эта роль и почему ответом всё чаще становится своя инфраструктура, а не подписка.",
    },
    keywords={
        "en": "automation consultant, AI implementation consultant, who redesigns workflows, process automation role, where to apply AI in business, workflow redesign, AI strategy",
        "ru": "консультант по автоматизации, внедрение ИИ в компании, кто перестраивает процессы, роль автоматизатора, где применять ИИ в бизнесе, редизайн процессов, стратегия внедрения ИИ",
    },
    hashtags=["Automation", "AI", "FutureOfWork", "Operations", "Consulting"],
    related=["automation-instead-of-hiring", "when-not-to-automate", "infrastructure-inbreeding"],
    body={
        "ru": [
            ("p", "Довольно долго компании искали универсалов. Человека, который ведёт проекты, разбирается в операционке, говорит со стейкхолдерами, работает с данными, осваивает новые инструменты и решает то, что появилось перед ним сегодня. Логика была понятной: чем шире список навыков, тем больше дыр закрывает один человек."),
            ("p", "ИИ ломает экономику этой модели — не тем, что заменяет людей, а тем, что меняет цену отдельных навыков. Если рутинную и малоценную часть работы всё чаще можно отдать машине, широкий список умений перестаёт быть преимуществом сам по себе. Важнее становится другой вопрос."),
            ("q", "Какие части работы всё ещё должны делать люди?"),
            ("p", "Из этого вопроса вырастает роль, которой в большинстве штатных расписаний пока нет, — <strong>консультант по автоматизации</strong>. Не тот, кто внедряет инструмент, а тот, кто смотрит, как компания устроена на самом деле, и находит места, где технология меняет не скорость работы, а саму её конструкцию."),

            ("h2", "Какие вопросы задаёт эта роль"),
            ("p", "Отличить её от смежных проще всего по вопросам. Интегратор спрашивает, что подключить. Аналитик — что показывают цифры. Консультант по автоматизации спрашивает другое:"),
            ("ul", [
                "какие процессы съедают человеческое время без соразмерной отдачи;",
                "где сотрудники дублируют работу друг друга, не зная об этом;",
                "какие потоки работы вообще поддаются автоматизации, а какие только выглядят так;",
                "какие решения можно поддержать данными, а какие нельзя отдать никому, кроме человека;",
                "какие системы имеет смысл связать между собой, а какие лучше оставить в покое;",
                "и где автоматизация имеет экономический смысл, а где обойдётся дороже, чем сэкономит.",
            ]),
            ("p", "Последний вопрос — главный, и он же чаще всего не задаётся. Как считать обе стороны этой арифметики, подробно разобрано в статье <a href=\"../automation-instead-of-hiring/\">автоматизация вместо найма</a>."),

            ("h2", "Почему это не «специалист по компьютерам» из девяностых"),
            ("p", "Аналогия напрашивается: когда-то были люди, помогавшие компаниям перейти с бумаги на компьютеры. По сути — та же работа: технология новая, процессы старые, кто-то должен соединить одно с другим."),
            ("p", "Но масштаб другой. Тогда автоматизировали отдельные операции: считать в таблице вместо счётов, печатать вместо переписывания от руки. Процесс при этом оставался прежним, менялся инструмент внутри шага."),
            ("p", "Сейчас переделывается сам поток работы. Можно убрать шаг целиком, изменить порядок принятия решений, перенести согласование из встречи в запись, а координацию — из головы менеджера в систему. И это меняет логику управления."),
            ("q", "Вместо «кого нанять, чтобы это делал» компания всё чаще должна спрашивать «должен ли этим вообще заниматься человек»."),

            ("h2", "Где эта роль полезна, а где нет"),
            ("p", "Автоматизация не одинаково ценна везде, и честнее сказать это прямо. Для маленькой компании с простыми процессами сложная система автоматизации обойдётся дороже, чем сэкономит: не хватит объёма повторов, чтобы окупить поддержку."),
            ("p", "А вот в средних и крупных организациях тысячи часов уходят в повторяющуюся отчётность, координацию, ввод данных, согласования, передачу информации между людьми и рутинные решения. Там каждая устранённая рутина умножается на количество людей, которые ею занимались, и автоматизация становится стратегически интересной."),
            ("table", {
                "caption": "Где искать роль и что она должна давать на выходе",
                "head": ["Размер компании", "Что обычно болит", "Что имеет смысл"],
                "rows": [
                    ["До 20 человек", "Один-два процесса, съедающих время основателя", "Две-три точечные связки за неделю работы, без платформы"],
                    ["20–100", "Дублирование между отделами, ручной перенос данных", "Карта процессов и автоматизация трёх-пяти повторяющихся потоков"],
                    ["100+", "Отчётность, согласования, координация как отдельная работа", "Переделка потоков, а не ускорение шагов; отдельный владелец у каждой автоматизации"],
                ],
            }),

            ("h2", "Побочный эффект: инструменты подешевели"),
            ("p", "Есть вторая половина этой истории, о которой говорят реже. Инструменты, ради которых раньше нанимали подрядчика, стали доступны почти всем. Собственный сервер с языковой моделью на борту сегодня укладывается в $500–700 разовых затрат — и на нём же живут файлы, прокси, CRM, трекер задач и «расширенная память» команды."),
            ("p", "Для компании это меняет расклад в трёх местах. Данные не уезжают третьей стороне — а именно утечка чаще всего оказывается настоящим стоп-фактором внедрения. Стоимость перестаёт зависеть от количества пользователей и тарифной политики поставщика. И, что в последние годы стало ощутимо, работа перестаёт зависеть от чужих геополитических решений и доступности чужого сервиса."),
            ("note", "Это не аргумент против облачных моделей: у них своя ниша, и разворачивать сервер ради двух запросов в неделю бессмысленно. Это аргумент за то, чтобы вопрос «где это будет работать» задавался до вопроса «какую модель возьмём», а не после."),
            ("p", "Из того же процесса вырастает более широкий сдвиг: чем доступнее инструменты, тем чаще эпоха больших компаний уступает место соло-бизнесам и небольшим командам, вокруг которых нарастают слои сервисов и платформ, зарабатывающих на том, что помогают другим работать. Рынок внутри рынка внутри рынка."),

            ("h2", "Что должен уметь человек в этой роли"),
            ("p", "Список короче, чем ожидается, и почти не пересекается со списком инструментов."),
            ("steps", [
                ("Описывать процесс так, как он идёт, а не как он описан в регламенте",
                 "Разница между этими двумя версиями и есть основной материал работы. Найти её можно только разговором с теми, кто делает работу руками."),
                ("Отделять рутину от решений",
                 "Рутина воспроизводима и не содержит выбора. Решение — точка, где возможны два исхода и один дороже другого. Смешивать их — самая частая ошибка внедрения."),
                ("Считать полную стоимость обеих сторон",
                 "И сотрудника с налогами и разгоном, и автоматизации с поддержкой и обработкой исключений на три года вперёд."),
                ("Говорить «не надо»",
                 "Роль полезна ровно настолько, насколько её носитель готов сказать, что здесь автоматизировать нечего и лучше починить процесс. Тот, кто этого не говорит, продаёт внедрение, а не решение."),
                ("Оставлять систему поддерживаемой без себя",
                 "Документация, названный владелец и ответ на вопрос «как мы узнаем, что это перестало работать правильно». Без этого автоматизация становится ничьей за один квартал."),
            ]),

            ("h2", "Вопрос, который стоит задавать вместо привычного"),
            ("p", "Публичная дискуссия крутится вокруг «заменит ли ИИ людей». Это плохой вопрос: технологии много раз меняли структуру работы и почти никогда не уничтожали профессии за ночь. Они меняли то, в чём компании нужны сильные люди."),
            ("p", "Более интересная формулировка — <strong>какие специалисты смогут перестроить работу вокруг ИИ</strong>. И самый ценный навык здесь не в том, чтобы уметь пользоваться моделью: пользоваться ею через год будет уметь любой. Ценность в том, чтобы понимать, где её стоит применять и, куда чаще, где не стоит."),
            ("p", "Переход, о котором идёт речь, начался давно и происходит не рывком, а сменой того, за что компании готовы платить. Роль, описанная выше, — просто одно из первых мест, где это стало заметно."),
        ],

        "en": [
            ("p", "For a long time companies looked for all-rounders: someone who could run projects, understand operations, talk to stakeholders, work with data, pick up new tools and solve whatever appeared in front of them. The logic held — the broader the skill list, the more gaps one person covers."),
            ("p", "AI is changing the economics of that model, not by replacing people but by changing what individual skills are worth. If routine and low-value work can increasingly be delegated to a machine, a broad list of skills stops being an advantage in itself. A different question moves to the front."),
            ("q", "Which parts of the work should still be done by people?"),
            ("p", "Out of that question grows a role most org charts don't have yet: <strong>the automation consultant</strong>. Not the person who installs the tool, but the person who looks at how a company actually works and finds the places where technology changes not the speed of the work but its structure."),

            ("h2", "The questions this role asks"),
            ("p", "The easiest way to tell it apart from neighbouring roles is by its questions. An integrator asks what to connect. An analyst asks what the numbers show. An automation consultant asks:"),
            ("ul", [
                "which processes consume human time without a proportionate return;",
                "where employees duplicate each other's work without knowing it;",
                "which workflows can genuinely be automated, and which only look that way;",
                "which decisions can be supported by data, and which cannot be handed to anyone but a person;",
                "which systems are worth connecting, and which are better left alone;",
                "and where automation makes economic sense at all, rather than costing more than it saves.",
            ]),
            ("p", "The last question is the important one, and the one most often skipped. How to cost both sides of that arithmetic is worked through in <a href=\"../automation-instead-of-hiring/\">automate or hire</a>."),

            ("h2", "Why this isn't the computer guy from the nineties"),
            ("p", "The analogy suggests itself: there were once people who helped companies move from paper to computers. Structurally the same job — new technology, old processes, somebody has to connect the two."),
            ("p", "But the scale is different. Back then individual operations were automated: calculate in a spreadsheet rather than by hand, print rather than rewrite. The process itself stayed the same; the tool inside a step changed."),
            ("p", "Now the workflow itself gets redesigned. A step can be removed entirely, the order of decisions can change, an approval can move from a meeting into a record, and coordination can move out of a manager's head into a system. That changes the logic of management."),
            ("q", "Instead of \"who should we hire to do this\", companies increasingly have to ask \"should a person be doing this at all\"."),

            ("h2", "Where the role earns its keep, and where it doesn't"),
            ("p", "Automation is not equally valuable everywhere, and it is more honest to say so plainly. For a small company with simple processes, a sophisticated automation system will cost more than it saves: there isn't enough repetition to pay back the maintenance."),
            ("p", "In medium and large organisations the picture inverts. Thousands of hours disappear into repeated reporting, coordination, data entry, approvals, passing information between people and routine decision-making. There, every removed routine multiplies by the number of people who were doing it, and automation becomes strategically interesting."),
            ("table", {
                "caption": "Where to look for the role and what it should produce",
                "head": ["Company size", "What usually hurts", "What makes sense"],
                "rows": [
                    ["Under 20 people", "One or two processes eating the founder's time", "Two or three targeted connections built in a week — no platform"],
                    ["20–100", "Duplication between departments, manual data transfer", "A process map and automation of three to five repeating flows"],
                    ["100+", "Reporting, approvals and coordination as work in their own right", "Redesigned flows rather than faster steps; a named owner for each automation"],
                ],
            }),

            ("h2", "A side effect: the tools got cheap"),
            ("p", "There is a second half to this story that gets discussed less. The tools people used to hire a supplier for have become available to almost anyone. A personal server with a language model on it now fits into $500–700 of one-off cost — and the same box holds files, a proxy, a CRM, a task tracker and a team's extended memory."),
            ("p", "For a company this shifts three things. Data doesn't leave for a third party — and leakage is usually the real blocker on adoption, not capability. Cost stops depending on seat counts and a vendor's pricing policy. And, noticeably over recent years, the work stops depending on somebody else's geopolitical decisions and somebody else's uptime."),
            ("note", "This is not an argument against cloud models: they have their place, and standing up a server for two queries a week is pointless. It is an argument for asking \"where will this run\" before \"which model shall we use\", rather than after."),
            ("p", "The same process feeds a broader shift: the cheaper the tools, the more often the era of large companies gives way to solo businesses and small teams, around which layers of services and platforms grow that make their money helping others operate. A market inside a market inside a market."),

            ("h2", "What the person in this role has to be able to do"),
            ("p", "The list is shorter than expected and barely overlaps with a list of tools."),
            ("steps", [
                ("Describe the process as it runs, not as the policy describes it",
                 "The gap between those two versions is the raw material of the job. It can only be found by talking to the people who do the work by hand."),
                ("Separate routine from decisions",
                 "Routine is reproducible and contains no choice. A decision is a point where two outcomes are possible and one costs more. Mixing them is the most common implementation error."),
                ("Cost both sides in full",
                 "The employee with taxes and ramp, the automation with maintenance and exception handling, both projected three years out."),
                ("Be willing to say no",
                 "The role is useful exactly to the degree that its holder will say there is nothing here worth automating and the process should be fixed instead. Someone who never says that is selling an implementation, not a solution."),
                ("Leave the system maintainable without you",
                 "Documentation, a named owner, and an answer to \"how would we know if this stopped being correct\". Without those, an automation becomes nobody's within a quarter."),
            ]),

            ("h2", "A better question than the usual one"),
            ("p", "Public discussion circles around whether AI will replace people. It is a poor question: technology has restructured work many times and has almost never eliminated professions overnight. What it changes is what companies need people to be good at."),
            ("p", "The more interesting formulation is <strong>which professionals will be able to redesign work around AI</strong>. And the valuable skill there is not knowing how to use a model — within a year everybody will. The value is in knowing where it should be applied and, far more often, where it shouldn't."),
            ("p", "The transition in question started a long time ago, and it doesn't arrive as a jolt. It arrives as a change in what companies are willing to pay for. The role described above is simply one of the first places it became visible."),
        ],
    },
    takeaways={
        "ru": [
            "ИИ меняет не количество рабочих мест, а цену отдельных навыков: широкий список умений перестаёт быть преимуществом сам по себе.",
            "Роль консультанта по автоматизации отличается от интегратора и аналитика по вопросам: не «что подключить», а «где технология меняет саму конструкцию работы».",
            "Главный вопрос роли — где автоматизация имеет экономический смысл, а где обойдётся дороже, чем сэкономит. Его чаще всего не задают.",
            "Раньше автоматизировали отдельные операции внутри шага; сейчас переделывается сам поток работы, и это меняет логику управления.",
            "В компании до двадцати человек сложная автоматизация обычно не окупается; в организации от ста человек каждая устранённая рутина умножается на число занятых ею людей.",
            "Своя инфраструктура — сервер с моделью за $500–700 — снимает три вопроса разом: утечку данных, зависимость от тарифов поставщика и зависимость от чужих решений.",
            "Ценный навык — не умение пользоваться моделью, а понимание, где её применять и где не стоит.",
        ],
        "en": [
            "AI changes not the number of jobs but the price of individual skills: a broad skill list stops being an advantage on its own.",
            "The automation consultant differs from an integrator or an analyst by the questions asked: not \"what should we connect\" but \"where does technology change the structure of the work\".",
            "The central question of the role is where automation makes economic sense and where it costs more than it saves. It is the one most often skipped.",
            "Earlier waves automated individual operations inside a step; now the workflow itself is redesigned, and that changes the logic of management.",
            "Under twenty people, sophisticated automation usually doesn't pay back; past a hundred, every removed routine multiplies by the number of people doing it.",
            "Your own infrastructure — a server with a model on it for $500–700 — settles three questions at once: data leakage, dependence on vendor pricing, and dependence on someone else's decisions.",
            "The valuable skill is not using a model but knowing where to apply it and where not to.",
        ],
    },
    faq={
        "ru": [
            ("Кто такой консультант по автоматизации и чем он отличается от интегратора?",
             "Интегратор отвечает на вопрос «что подключить» и работает внутри заданной постановки. Консультант по автоматизации сначала выясняет, как компания работает на самом деле, и ищет места, где технология меняет конструкцию процесса, а не скорость отдельного шага. Часто его работа заканчивается выводом, что автоматизировать здесь нечего, а надо переделать процесс."),
            ("Зачем нужна отдельная роль, если есть аналитики и проектные менеджеры?",
             "Аналитик отвечает, что показывают цифры, проектный менеджер — как довести задачу до результата. Ни один из них по должности не отвечает на вопрос, должен ли этот кусок работы вообще выполняться человеком. Пока этот вопрос не задан, автоматизация ускоряет процессы, которые следовало отменить."),
            ("С какого размера компании автоматизация начинает окупаться?",
             "Точной границы нет, есть объём повторов. В компании до двадцати человек сложная система чаще стоит дороже, чем экономит, и выигрывают две-три точечные связки. От ста человек рутина умножается на количество занятых ею людей, и переделка потоков становится стратегически осмысленной."),
            ("Что даёт собственный сервер с языковой моделью?",
             "Три вещи: данные не уезжают третьей стороне, стоимость перестаёт зависеть от количества пользователей и тарифов поставщика, а работа — от доступности чужого сервиса и чужих геополитических решений. Разовые затраты укладываются примерно в $500–700. Ради пары запросов в неделю это бессмысленно; при постоянном потоке и чувствительных данных — обычно да."),
            ("Заменит ли ИИ людей в этих ролях?",
             "Технологии много раз меняли структуру работы и почти никогда не уничтожали профессии за ночь. Меняется то, в чём компаниям нужны сильные люди. Более полезная формулировка вопроса — какие специалисты смогут перестроить работу вокруг ИИ, а не кого он вытеснит."),
            ("Какой навык в работе с ИИ сегодня самый ценный?",
             "Не умение пользоваться моделью: через год им будут владеть все. Ценность в понимании, где её стоит применять и, чаще, где не стоит — и в готовности сказать заказчику, что в этом месте автоматизировать нечего."),
        ],
        "en": [
            ("What is an automation consultant and how do they differ from an integrator?",
             "An integrator answers \"what should we connect\" and works inside a given brief. An automation consultant first establishes how the company actually works and looks for places where technology changes the structure of a process rather than the speed of one step. Often the work ends with the conclusion that there is nothing to automate and the process should be redesigned instead."),
            ("Why a separate role, when there are analysts and project managers?",
             "An analyst answers what the numbers show; a project manager answers how to get the work done. Neither of them is responsible, by job definition, for asking whether this piece of work should be done by a person at all. Until that question is asked, automation speeds up processes that should have been cancelled."),
            ("At what company size does automation start paying back?",
             "There is no exact threshold, only a volume of repetition. Under twenty people a sophisticated system usually costs more than it saves, and two or three targeted connections win. Past a hundred, routine multiplies by the number of people doing it and redesigning flows becomes strategically sensible."),
            ("What does running your own server with a language model give you?",
             "Three things: data doesn't leave for a third party, cost stops depending on seat counts and vendor pricing, and the work stops depending on somebody else's uptime and geopolitical decisions. One-off cost lands around $500–700. For two queries a week it is pointless; with a steady flow and sensitive data it usually pays."),
            ("Will AI replace people in these roles?",
             "Technology has restructured work many times and has almost never eliminated professions overnight. What changes is what companies need people to be good at. The more useful version of the question is which professionals will be able to redesign work around AI, rather than who it will displace."),
            ("What is the most valuable AI skill today?",
             "Not knowing how to use a model — within a year everyone will. The value is in knowing where it should be applied and, more often, where it shouldn't, and in being willing to tell a client that there is nothing here worth automating."),
        ],
    },
)
