# -*- coding: utf-8 -*-
POST = dict(
    slug="how-to-choose-a-consultant",
    date="2026-07-07",
    updated="2026-08-27",
    tag={"en": "Consulting", "ru": "Консалтинг"},
    title={
        "en": 'How to Choose a Business Consultant: 9 Questions',
        "ru": 'Как выбрать бизнес-консультанта: 9 вопросов',
    },
    h1={
        "en": "How to Choose a Business Consultant: 9 Questions That Separate Expertise From a Good Deck",
        "ru": "Как выбрать бизнес-консультанта: 9 вопросов, отделяющих экспертизу от красивой презентации",
    },
    dek={
        "en": "Selection usually fails in the first conversation, not in delivery. These nine questions surface in thirty minutes what a reference call takes weeks to reveal.",
        "ru": "Выбор обычно проваливается в первом разговоре, а не на исполнении. Эти девять вопросов за полчаса вскрывают то, на что у отзывов уходят недели.",
    },
    description={
        "en": "Nine questions to ask before signing, what a good and a bad answer sound like, and how to structure a first engagement that's cheap to walk away from.",
        "ru": 'Девять вопросов до подписания, как звучит хороший и плохой ответ на каждый и как построить первый проект, из которого дёшево выйти.',
    },
    keywords={
        "en": "how to choose a business consultant, hiring a consultant, consultant selection criteria, questions to ask a consultant, vetting consultants, consulting proposal red flags, consultant references, first engagement structure",
        "ru": "как выбрать бизнес-консультанта, наём консультанта, критерии выбора консультанта, вопросы консультанту, проверка консультанта, тревожные признаки в предложении, отзывы о консультанте, первый проект с консультантом",
    },
    hashtags=["ManagementConsulting", "Procurement", "BusinessConsulting", "VendorSelection", "Leadership"],
    related=["how-much-does-business-consulting-cost", "one-person-consulting-studio", "audit-nobody-reads"],
    body={
        "en": [
            ("p", "Most bad consulting engagements were decided in the first thirty-minute call, not during delivery. The selection signal is available early — it's just drowned out by rapport, references and a well-produced deck, all three of which are easy to manufacture."),
            ("p", "What follows is nine questions that are hard to answer well without actually having done the work. For each one, what a good answer sounds like and what a bad one sounds like. <strong>You are not testing knowledge. You are testing whether their judgement survives contact with a specific situation — yours.</strong>"),

            ("h2", "What you're actually selecting for"),
            ("p", "Three properties predict outcomes better than experience, credentials or firm size:"),
            ("ol", [
                "<strong>Willingness to narrow.</strong> Good consultants make your problem smaller and more specific. Selling makes it bigger.",
                "<strong>Willingness to be wrong in public.</strong> Someone who states in advance what would falsify their recommendation is doing analysis. Someone who doesn't is performing.",
                "<strong>Willingness to lose the deal.</strong> The ability to say \"you don't need this\" is the single most reliable quality signal, and it's structurally easier for suppliers without a bench to fill.",
            ]),

            ("h2", "The nine questions"),
            ("table", {
                "caption": "What to ask, and how to read the answer",
                "head": ["Question", "Good answer sounds like", "Bad answer sounds like"],
                "rows": [
                    ["1. What would make you tell me not to do this project?",
                     "A specific scenario: \"If your data isn't in one place yet, this analysis will cost twice what it's worth — fix that first.\"",
                     "\"There's always value in a fresh perspective.\""],
                    ["2. What's the smallest version of this engagement that would still be useful?",
                     "An actual smaller option, priced, with what you'd lose by taking it.",
                     "Reframing the question into why the full scope is necessary."],
                    ["3. Walk me through a project that didn't work. What did you get wrong?",
                     "A named wrong assumption and what they'd change in their own method.",
                     "\"The client wasn't ready\" / \"leadership didn't support it.\""],
                    ["4. Who does the work, and what percentage of their time is on this?",
                     "Names, percentages, and what happens if that changes.",
                     "\"Our senior team oversees all engagements.\""],
                    ["5. What do I own at the end, and in what format?",
                     "Editable models, data, scripts, written reasoning — in your systems.",
                     "A final presentation and a report."],
                    ["6. How will we know in six months whether this worked?",
                     "A metric that exists today, its current value, and the expected direction.",
                     "\"You'll see improved alignment and efficiency.\""],
                    ["7. What do you need from us, and what happens if we don't provide it?",
                     "A concrete list with consequences: \"Without the ticket export, weeks 2–3 become estimates.\"",
                     "\"Just general availability from your team.\""],
                    ["8. What's your view on our problem right now, before any work?",
                     "A tentative hypothesis with stated uncertainty — and a question back.",
                     "Refusal to speculate, or total confidence with no data."],
                    ["9. What happens if you're unavailable for two weeks?",
                     "A named fallback, interim deliverables, work stored in your systems.",
                     "Reassurance without mechanism."],
                ],
            }),
            ("p", "Question 8 is the one that most reliably separates people. A consultant with real experience in your problem type will offer a hypothesis within minutes and immediately name what would change their mind. Total refusal to speculate usually means no pattern library; total certainty usually means a template is already being selected."),
            ("q", "You are not buying answers. You are buying the quality of the reasoning that will produce them — and reasoning is visible in how someone handles a question they can't yet answer."),

            ("h2", "Red flags in the proposal"),
            ("checklist", [
                "<strong>\"Analysis and support\" as a deliverable.</strong> No definition of done, therefore no upper bound.",
                "<strong>No breakdown of days by phase.</strong> Nothing to negotiate but total price.",
                "<strong>Unnamed senior resources.</strong> \"A senior consultant\" is a role, not a commitment.",
                "<strong>Findings promised before discovery.</strong> If the conclusion is in the proposal, you're buying a template.",
                "<strong>Methodology as the main selling point.</strong> Frameworks are how firms make repeat work profitable. That is fine for common problems and a warning sign for unusual ones.",
                "<strong>No change-request definition.</strong> Everything unlisted becomes one.",
                "<strong>Guaranteed outcomes.</strong> Anyone guaranteeing a business result before diagnosis is either uninformed or selling.",
                "<strong>Scope that covers every department.</strong> Breadth is how a report avoids naming a responsible executive — see <a href=\"../audit-nobody-reads/\">the audit nobody reads</a>.",
            ]),

            ("h2", "References: ask the right three questions"),
            ("p", "Reference calls are usually theatre, because the consultant chooses the referee. Three questions still extract signal:"),
            ("ol", [
                "<strong>\"What did you have to do that you didn't expect?\"</strong> Reveals how much of the load actually landed on the client, which is the most commonly understated cost.",
                "<strong>\"What did they get wrong, and how did you find out?\"</strong> Every real engagement contains a wrong turn. A referee who can't name one either didn't engage deeply or is being careful.",
                "<strong>\"Would you use them for a different type of problem?\"</strong> A hesitant yes tells you the boundary of their competence, which is more useful than an enthusiastic one.",
            ]),
            ("p", "If possible, ask for one reference from an engagement that <em>ended early or didn't get renewed</em>. Refusal is not disqualifying, but a supplier who can offer one is telling you something real."),

            ("h2", "Credentials: what matters and what doesn't"),
            ("table", {
                "caption": "Signal value of common credentials",
                "head": ["Credential", "Signal", "Caveat"],
                "rows": [
                    ["Prior work in your specific failure mode", "High", "Ask for the mechanism they saw, not the client name"],
                    ["Domain certifications relevant to the deliverable", "Medium", "Proves knowledge of standards, not judgement"],
                    ["Big-firm background", "Medium", "Tells you about training and process, not about independent problem-solving"],
                    ["Published writing about the problem", "Medium-high", "Cheap to check, hard to fake over time"],
                    ["Client logos", "Low", "Logos are the firm's, not the individual's"],
                    ["Generic business degrees", "Low", "Widely held; explains vocabulary, not capability"],
                    ["Awards", "Very low", "Most are paid or peer-nominated"],
                ],
            }),

            ("h2", "Structure the first engagement to be cheap to exit"),
            ("steps", [
                ("Buy a paid diagnostic first",
                 "A short, priced piece of work that ends in a scoped plan. You're buying an estimate rather than guessing at one, and you get to watch them work before committing."),
                ("Require an interim deliverable inside two weeks",
                 "Whatever it is, it should be reviewable. This caps your exposure and gives you a real basis for the continue-or-stop decision."),
                ("Agree the stop point in writing",
                 "\"At the end of phase one we decide whether to proceed; no notice period, no assumption of continuation.\" Easy to agree at the start, awkward to introduce later."),
                ("Keep the deliverables in your systems",
                 "From day one, not at handover. If the relationship ends, you keep everything produced."),
                ("Name your own owner",
                 "Someone internal who is accountable for acting on the output. An engagement with no internal owner produces a document, regardless of who you hired."),
            ]),
            ("note", "If a supplier resists a paid diagnostic with a genuine stop point, that's the answer to question 1 in a different form: they are unwilling to be evaluated on a small piece before the large one."),

            ("h2", "One practical sequence"),
            ("p", "For a bounded problem, this takes about a week: write the question in one sentence; send it to three suppliers of deliberately different shapes (an independent, a boutique, a larger firm — the trade-offs are laid out in <a href=\"../one-person-consulting-studio/\">this comparison</a>); run the nine questions in a 30-minute call each; compare the three proposals structurally rather than on price, using the pricing factors in <a href=\"../how-much-does-business-consulting-cost/\">what consulting actually costs</a>; buy a diagnostic from one."),
            ("p", "The point of talking to three deliberately different suppliers isn't to create competition on price. It's that their disagreements about your problem are free information — and often more valuable than any single proposal."),
        ],
        "ru": [
            ("p", "Большинство неудачных консалтинговых проектов решается в первом получасовом разговоре, а не на исполнении. Сигнал доступен рано — просто он заглушается симпатией, отзывами и хорошо сделанной презентацией, а всё это несложно изготовить."),
            ("p", "Ниже девять вопросов, на которые трудно ответить хорошо, не сделав работу по-настоящему. К каждому — как звучит хороший ответ и как плохой. <strong>Вы проверяете не знания. Вы проверяете, выживает ли суждение при столкновении с конкретной ситуацией — вашей.</strong>"),

            ("h2", "Что вы на самом деле выбираете"),
            ("p", "Три свойства предсказывают результат лучше, чем опыт, регалии или размер компании:"),
            ("ol", [
                "<strong>Готовность сужать.</strong> Хорошие консультанты делают вашу задачу меньше и конкретнее. Продажа делает её больше.",
                "<strong>Готовность публично ошибиться.</strong> Тот, кто заранее говорит, что опровергнет его рекомендацию, занимается анализом. Тот, кто не говорит, — выступает.",
                "<strong>Готовность потерять сделку.</strong> Способность сказать «вам это не нужно» — самый надёжный сигнал качества, и структурно она легче даётся подрядчикам без скамейки, которую надо занять.",
            ]),

            ("h2", "Девять вопросов"),
            ("table", {
                "caption": "Что спрашивать и как читать ответ",
                "head": ["Вопрос", "Хороший ответ звучит так", "Плохой ответ звучит так"],
                "rows": [
                    ["1. Что заставило бы вас отговорить меня от этого проекта?",
                     "Конкретный сценарий: «Если ваши данные ещё не в одном месте, анализ обойдётся вдвое дороже, чем стоит, — сначала почините это».",
                     "«Свежий взгляд всегда полезен»."],
                    ["2. Какая минимальная версия этой работы всё ещё была бы полезной?",
                     "Реально меньший вариант с ценой и с тем, что вы при этом потеряете.",
                     "Переформулирование вопроса в объяснение, почему нужен полный объём."],
                    ["3. Расскажите про проект, который не получился. В чём вы ошиблись?",
                     "Названная неверная предпосылка и что бы они изменили в собственном методе.",
                     "«Клиент был не готов» / «руководство не поддержало»."],
                    ["4. Кто делает работу и какую долю их времени она занимает?",
                     "Имена, проценты и что произойдёт, если это изменится.",
                     "«Наша старшая команда курирует все проекты»."],
                    ["5. Что остаётся у меня в конце и в каком виде?",
                     "Редактируемые модели, данные, скрипты, письменная логика — в ваших системах.",
                     "Итоговая презентация и отчёт."],
                    ["6. Как через полгода мы поймём, что это сработало?",
                     "Метрика, существующая сегодня, её текущее значение и ожидаемое направление.",
                     "«Вы увидите рост согласованности и эффективности»."],
                    ["7. Что вам нужно от нас и что будет, если мы этого не дадим?",
                     "Конкретный список с последствиями: «Без выгрузки из тикет-системы вторая и третья недели станут оценками».",
                     "«Просто общая доступность вашей команды»."],
                    ["8. Какое у вас мнение о нашей проблеме прямо сейчас, до работы?",
                     "Предварительная гипотеза с обозначенной неопределённостью — и встречный вопрос.",
                     "Отказ предполагать или полная уверенность без данных."],
                    ["9. Что будет, если вы окажетесь недоступны две недели?",
                     "Названный запасной исполнитель, промежуточные результаты, работа в ваших системах.",
                     "Заверения без механизма."],
                ],
            }),
            ("p", "Восьмой вопрос надёжнее всего разделяет людей. Консультант с реальным опытом в задачах вашего типа выдаст гипотезу за минуты и сразу назовёт, что заставило бы его передумать. Полный отказ предполагать обычно означает отсутствие библиотеки сценариев; полная уверенность обычно означает, что шаблон уже выбирается."),
            ("q", "Вы покупаете не ответы. Вы покупаете качество рассуждения, которое эти ответы произведёт, — а рассуждение видно по тому, как человек обращается с вопросом, на который ответа пока нет."),

            ("h2", "Тревожные признаки в предложении"),
            ("checklist", [
                "<strong>«Анализ и сопровождение» в качестве результата.</strong> Нет определения готовности — значит, нет верхней границы.",
                "<strong>Нет разбивки дней по этапам.</strong> Обсуждать нечего, кроме итоговой суммы.",
                "<strong>Безымянные старшие специалисты.</strong> «Старший консультант» — это роль, а не обязательство.",
                "<strong>Выводы обещаны до исследования.</strong> Если заключение уже в предложении, вы покупаете шаблон.",
                "<strong>Методология как главный аргумент.</strong> Фреймворки — это то, как компании делают повторную работу прибыльной. Для типовых задач нормально, для нетиповых тревожный знак.",
                "<strong>Нет определения допсоглашения.</strong> Всё неперечисленное им и станет.",
                "<strong>Гарантированный результат.</strong> Тот, кто гарантирует бизнес-результат до диагностики, либо не разбирается, либо продаёт.",
                "<strong>Объём, покрывающий все подразделения.</strong> Широта — это способ отчёта не называть ответственного руководителя, см. <a href=\"../audit-nobody-reads/\">аудит, который никто не читает</a>.",
            ]),

            ("h2", "Отзывы: три правильных вопроса"),
            ("p", "Разговоры с рекомендателями обычно театр, потому что рекомендателя выбирает консультант. Три вопроса всё же вытаскивают сигнал:"),
            ("ol", [
                "<strong>«Что вам пришлось делать самим, чего вы не ожидали?»</strong> Показывает, какая часть нагрузки на самом деле легла на клиента, — это самая часто занижаемая статья расходов.",
                "<strong>«В чём они ошиблись и как вы это обнаружили?»</strong> В любом настоящем проекте есть неверный поворот. Рекомендатель, который не может его назвать, либо не был глубоко вовлечён, либо осторожничает.",
                "<strong>«Позвали бы вы их на задачу другого типа?»</strong> Неуверенное «да» показывает границу компетенции, а это полезнее восторженного согласия.",
            ]),
            ("p", "Если получится, попросите отзыв о проекте, который <em>завершился досрочно или не был продлён</em>. Отказ не дисквалифицирует, но подрядчик, способный такой отзыв дать, сообщает вам что-то настоящее."),

            ("h2", "Регалии: что важно, а что нет"),
            ("table", {
                "caption": "Сигнальная ценность типичных регалий",
                "head": ["Регалия", "Сигнал", "Оговорка"],
                "rows": [
                    ["Опыт именно в вашем сценарии отказа", "Высокий", "Спрашивайте про механизм, который они видели, а не про имя клиента"],
                    ["Отраслевые сертификаты по теме результата", "Средний", "Доказывает знание стандартов, а не суждение"],
                    ["Опыт в крупной компании", "Средний", "Говорит о школе и процессе, а не о самостоятельном решении задач"],
                    ["Публикации по теме проблемы", "Средне-высокий", "Дёшево проверить, трудно подделать на длинной дистанции"],
                    ["Логотипы клиентов", "Низкий", "Логотипы принадлежат компании, а не человеку"],
                    ["Общие бизнес-дипломы", "Низкий", "Есть у многих; объясняют словарь, а не способности"],
                    ["Награды", "Очень низкий", "Большинство платные или по номинации коллег"],
                ],
            }),

            ("h2", "Стройте первый проект так, чтобы из него было дёшево выйти"),
            ("steps", [
                ("Сначала купите платную диагностику",
                 "Короткая оплаченная работа, заканчивающаяся проработанным планом. Вы покупаете оценку вместо того, чтобы её угадывать, и заодно смотрите, как человек работает, до крупных обязательств."),
                ("Требуйте промежуточный результат в первые две недели",
                 "Любой, но пригодный к разбору. Это ограничивает вашу уязвимость и даёт реальное основание для решения «продолжать или остановиться»."),
                ("Пропишите точку остановки письменно",
                 "«По окончании первого этапа мы решаем, продолжаем ли; без срока уведомления и без предположения о продолжении». Легко согласовать на старте, неловко вводить потом."),
                ("Держите результаты в своих системах",
                 "С первого дня, а не при передаче. Если отношения закончатся, всё сделанное останется у вас."),
                ("Назначьте собственного владельца",
                 "Внутренний человек, отвечающий за применение результата. Проект без внутреннего владельца производит документ, кого бы вы ни наняли."),
            ]),
            ("note", "Если подрядчик сопротивляется платной диагностике с настоящей точкой остановки — это ответ на первый вопрос в другой форме: он не готов, чтобы его оценили на маленьком куске до большого."),

            ("h2", "Практическая последовательность"),
            ("p", "Для ограниченной задачи это занимает около недели: сформулируйте вопрос одним предложением; отправьте его трём подрядчикам сознательно разного формата (независимый, бутик, компания покрупнее — компромиссы разобраны в <a href=\"../one-person-consulting-studio/\">этом сравнении</a>); проведите девять вопросов на тридцатиминутном созвоне с каждым; сравните три предложения структурно, а не по цене, опираясь на факторы из статьи <a href=\"../how-much-does-business-consulting-cost/\">сколько на самом деле стоит консалтинг</a>; купите диагностику у одного."),
            ("p", "Смысл разговора с тремя сознательно разными подрядчиками не в том, чтобы создать конкуренцию по цене. Смысл в том, что их расхождения по поводу вашей задачи — бесплатная информация, и часто она ценнее любого отдельного предложения."),
        ],
    },
    takeaways={
        "en": [
            "Three properties predict outcomes better than credentials: willingness to narrow the problem, to state what would falsify their recommendation, and to lose the deal.",
            "The most diagnostic question is \"what's your view on our problem right now?\" — a hypothesis with stated uncertainty beats both refusal and certainty.",
            "Proposal red flags: \"analysis and support\" as a deliverable, unnamed senior resources, findings promised before discovery, and scope covering every department.",
            "On reference calls ask what the client had to do unexpectedly, what the consultant got wrong, and whether they'd use them for a different problem type.",
            "Prior experience of your specific failure mode and published writing are high-signal; logos, degrees and awards are not.",
            "De-risk the first engagement: paid diagnostic, interim deliverable within two weeks, written stop point, deliverables in your systems, and a named internal owner.",
        ],
        "ru": [
            "Три свойства предсказывают результат лучше регалий: готовность сузить задачу, назвать условия опровержения своей рекомендации и потерять сделку.",
            "Самый диагностичный вопрос — «какое у вас мнение о нашей проблеме прямо сейчас»: гипотеза с обозначенной неопределённостью лучше и отказа, и уверенности.",
            "Тревожные признаки предложения: «анализ и сопровождение» как результат, безымянные старшие специалисты, выводы до исследования и объём на все подразделения.",
            "У рекомендателей спрашивайте, что им неожиданно пришлось делать самим, в чём консультант ошибся и позвали бы они его на задачу другого типа.",
            "Опыт именно в вашем сценарии отказа и публикации по теме — сильные сигналы; логотипы, дипломы и награды — нет.",
            "Снизьте риск первого проекта: платная диагностика, промежуточный результат в две недели, письменная точка остановки, результаты в ваших системах и названный внутренний владелец.",
        ],
    },
    faq={
        "en": [
            ("What is the single best question to ask a consultant before hiring them?",
             "\"What would make you tell me not to do this project?\" A specific scenario means they have a real threshold for usefulness. \"There's always value in a fresh perspective\" means they have none, and you will be sold whatever you ask for."),
            ("How do I check a consultant's experience without relying on client logos?",
             "Ask them to describe the mechanism of a failure they have seen in your problem type — not the client, the mechanism. Someone who has been there will describe how the thing went wrong step by step. Published writing on the topic is also cheap to verify and hard to fake over time."),
            ("Should I ask for references, and what should I ask them?",
             "Yes, while remembering the consultant chose them. Ask what the client had to do that they didn't expect, what the consultant got wrong and how it was discovered, and whether they'd use them for a different type of problem. If possible, request a reference from an engagement that ended early."),
            ("What are the biggest red flags in a consulting proposal?",
             "\"Analysis and support\" as the deliverable, no breakdown of days by phase, unnamed senior resources, conclusions stated before any discovery, guaranteed business outcomes, no definition of what triggers a change request, and a scope that covers every department."),
            ("How can I reduce the risk of hiring the wrong consultant?",
             "Buy a small paid diagnostic first with a written stop point, require a reviewable interim deliverable within two weeks, keep all work in your own systems from day one, and appoint an internal owner accountable for acting on the output."),
            ("Should I talk to more than one consultant?",
             "Talk to three of deliberately different shapes — an independent, a boutique and a larger firm. Not to create price competition, but because their disagreements about your problem are free diagnostic information, often more valuable than any single proposal."),
        ],
        "ru": [
            ("Какой один вопрос лучше всего задать консультанту до найма?",
             "«Что заставило бы вас отговорить меня от этого проекта?» Конкретный сценарий означает, что у человека есть реальный порог полезности. «Свежий взгляд всегда полезен» означает, что порога нет, и вам продадут то, что вы попросите."),
            ("Как проверить опыт консультанта, не полагаясь на логотипы клиентов?",
             "Попросите описать механизм провала, который он видел в задачах вашего типа, — не клиента, а механизм. Тот, кто там был, разложит по шагам, как именно всё пошло не так. Публикации по теме тоже дёшево проверить и трудно подделать на дистанции."),
            ("Нужно ли просить отзывы и что у них спрашивать?",
             "Нужно, помня, что рекомендателя выбрал консультант. Спросите, что клиенту неожиданно пришлось делать самому, в чём консультант ошибся и как это обнаружилось, и позвали бы его на задачу другого типа. По возможности запросите отзыв о проекте, завершившемся досрочно."),
            ("Какие главные тревожные признаки в коммерческом предложении?",
             "«Анализ и сопровождение» как результат, отсутствие разбивки дней по этапам, безымянные старшие специалисты, выводы до какого-либо исследования, гарантированный бизнес-результат, отсутствие определения допсоглашений и объём, покрывающий все подразделения."),
            ("Как снизить риск нанять не того консультанта?",
             "Купите сначала небольшую платную диагностику с письменной точкой остановки, требуйте пригодный к разбору промежуточный результат в течение двух недель, держите всю работу в своих системах с первого дня и назначьте внутреннего владельца, отвечающего за применение результата."),
            ("Стоит ли говорить больше чем с одним консультантом?",
             "Поговорите с тремя сознательно разного формата — независимым, бутиком и компанией покрупнее. Не ради конкуренции по цене, а потому что их расхождения по поводу вашей задачи — бесплатная диагностическая информация, часто более ценная, чем любое отдельное предложение."),
        ],
    },
)
