# -*- coding: utf-8 -*-
POST = dict(
    slug="informal-org-structures",
    date="2026-09-22",
    updated="2026-09-22",
    tag={"en": "Management", "ru": "Управление"},
    title={
        "en": "The Organisation That Isn't on the Chart",
        "ru": "Организация, которой нет на схеме",
    },
    h1={
        "en": "The Organisation That Isn't on the Chart: Informal Structures and How Work Really Flows",
        "ru": "Организация, которой нет на схеме: неформальные структуры и реальная топология работы",
    },
    dek={
        "en": "Informal structures aren't a sign of a sick company. They appear in any sufficiently complex system. The danger starts when the organisation can't see them.",
        "ru": "Неформальные структуры — не признак больной компании. Они появляются в любой достаточно сложной системе. Опасность начинается там, где компания их не видит.",
    },
    description={
        "en": "Why the org chart never matches how work flows, what informal delegation costs, and how to map the real topology without a witch hunt.",
        "ru": "Почему схема никогда не совпадает с тем, как идёт работа, и как увидеть реальную топологию, не устраивая охоту на ведьм.",
    },
    keywords={
        "en": "informal organizational structures, shadow org chart, hidden dependencies, key person risk, real production topology, informal delegation, organizational observability",
        "ru": "неформальная структура организации, теневая оргструктура, скрытые зависимости, риск ключевого человека, реальная топология работы, неформальное делегирование, наблюдаемость организации",
    },
    hashtags=["Management", "Organization", "Risk", "Operations", "Leadership"],
    related=["infrastructure-inbreeding", "silent-failure-mode", "audit-nobody-reads"],
    body={
        "ru": [
            ("p", "В некоторых организациях складываются структуры, которые нигде формально не описаны, но определяют, как реально делается работа. Сотрудник — менеджер, архитектор, разработчик, продюсер, проектный менеджер — постепенно выстраивает вокруг себя микросистему."),
            ("p", "Приводит помощников. Отдаёт часть работы подрядчикам. Опирается на доверенных людей за пределами компании. Создаёт неформальные каналы исполнения и принятия решений. Формально в схеме ничего не меняется. Фактически появляется ещё один узел, о котором компания не знает."),
            ("q", "Формальная схема почти никогда не совпадает с реальной архитектурой работы. Вопрос только в том, знает ли об этом организация."),

            ("h2", "Одно и то же явление в разных костюмах"),
            ("p", "Обычно это вспоминают по историям про американских разработчиков, тайком отдававших свои задачи исполнителям в Китае. История яркая, но частная, а сам класс явлений шире и включает вещи, которые интуитивно кажутся несвязанными."),
            ("ul", [
                "<strong>Вынос работы за пределы компании.</strong> Подрядчики, помощники, знакомые — оплаченные из своего кармана и невидимые для бюджета.",
                "<strong>Использование ИИ в работе, о котором не сказано.</strong> Функционально это тот же вынос исполнения наружу, просто исполнитель не человек.",
                "<strong>Люди, научившиеся проходить собеседования лучше, чем работать.</strong> Разрыв закрывается той же микросистемой — кем-то, кто делает работу вместо них.",
                "<strong>Влияние снизу вверх.</strong> Сотрудник ниже по иерархии, способный устойчиво определять решения, которые формально принимаются выше.",
            ]),
            ("p", "Я сознательно кладу их в одну аналитическую категорию. Не потому, что они одинаково этичны — это разные вещи, — а потому что для организации они создают одинаковый эффект: <strong>реальная схема исполнения расходится с формальной, и расхождение нигде не зафиксировано</strong>."),

            ("h2", "Почему это возникает само"),
            ("p", "Компании часто относятся к таким структурам как к чему-то подозрительному и нездоровому. Но появляются они не от испорченности людей, а от устройства системы."),
            ("p", "Причина простая: формальная схема описывает подчинение, а работа идёт не по подчинению. Когда растут давление, сложность и скорость, люди естественным образом создают локальные структуры адаптации:"),
            ("ul", [
                "личные каналы делегирования — кому реально можно отдать задачу и получить результат;",
                "собственные сети знаний — к кому идти за ответом, минуя того, кто отвечает по должности;",
                "неформальные пути эскалации — как донести проблему, не проходя три согласования;",
                "доверенные операционные узлы — люди, через которых почему-то проходит непропорционально много работы.",
            ]),
            ("p", "Каждая из этих структур решает настоящую проблему. Именно поэтому запретами они не убираются: запрет убирает канал, а не потребность, и через месяц появляется новый, ещё менее заметный."),
            ("note", "Проверка, которая почти всегда работает: спросите, кто уйдёт в отпуск на три недели так, что это заметят все. Ответ почти никогда не совпадает со схемой подчинения — и это и есть карта реальных узлов."),

            ("h2", "Проблема не в существовании, а в невидимости"),
            ("p", "Стоит различать два разных утверждения. «В компании есть неформальные структуры» — это нормально и неизбежно. «Компания не знает, какие именно» — это риск, и вот из чего он состоит."),
            ("table", {
                "caption": "Что происходит, когда реальная топология работы не видна",
                "head": ["Эффект", "Как проявляется", "Когда обнаруживается"],
                "rows": [
                    ["Производственная система частично невидима", "Часть работы делается не теми и не там, где считается", "При попытке масштабировать или воспроизвести процесс"],
                    ["Размывается владение", "На вопрос «кто отвечает» есть формальный ответ и фактический, и они разные", "Когда что-то сломалось и надо спросить"],
                    ["Скрытые зависимости от знания", "Процесс держится на человеке, который нигде не записан как критичный", "В момент его ухода или отпуска"],
                    ["Неучтённые точки отказа", "Узел, о котором никто не думал, потому что его нет в схеме", "Одновременно с отказом"],
                    ["Критические потоки вне наблюдаемости", "Работа идёт через людей и инструменты за периметром компании", "При аудите, инциденте или проверке"],
                ],
            }),
            ("p", "Последняя строка — самая дорогая. Если существенная часть исполнения физически происходит за пределами компании, то у компании нет ни контроля качества над ней, ни правовой рамки, ни возможности узнать, что данные ушли туда, куда не должны были."),

            ("h2", "Как увидеть реальную топологию"),
            ("p", "Ключевой момент: это задача наблюдения, а не расследования. Как только сотрудники понимают, что идёт поиск виноватых, картина искажается необратимо — по тем же причинам, что описаны в статье про <a href=\"../silent-failure-mode/\">тихий отказ</a>: система перестаёт пропускать сигнал, и вы ослепляете себя надолго."),
            ("steps", [
                ("Спросите про поток, а не про подчинение",
                 "Не «кто ваш руководитель», а «через кого проходит эта задача от появления до готовности». Второй вопрос даёт реальную последовательность, первый — оргсхему, которая у вас и так есть."),
                ("Найдите узлы по нагрузке, а не по должности",
                 "Кому пишут чаще, чем предполагает роль? Без кого встают три процесса сразу? Кого спрашивают вместо того, кто отвечает формально?"),
                ("Разберитесь, какую проблему решает каждый неформальный канал",
                 "Канал существует, потому что формальный путь дорог или не работает. Пока причина не устранена, канал воспроизведётся."),
                ("Легализуйте то, что работает",
                 "Если человек фактически стал координационным центром — назовите это и дайте полномочия. Если работа реально уходит подрядчику — оформите отношения. Легализация превращает риск в структуру."),
                ("Закройте то, что создаёт настоящий риск",
                 "Данные за периметром, исполнение без договора, зависимость от одного человека без замены. Здесь нужен не разговор, а решение."),
            ]),
            ("p", "Разница между легализацией и запретом принципиальная. Запрет убирает видимость, оставляя явление. Легализация оставляет явление, добавляя видимость — а видимая зависимость управляема."),

            ("h2", "Устойчивость, которая на самом деле хрупкость"),
            ("p", "Интересное свойство таких организаций в том, что снаружи они выглядят исключительно стабильными. Процессы идут гладко, люди понимают правила игры, руководители говорят на одном языке."),
            ("p", "Но эта же стабильность может скрывать растущую уязвимость: система начинает воспроизводить себя, а не адаптироваться к среде. Механизм тот же, что и у <a href=\"../infrastructure-inbreeding/\">инфраструктурного инбридинга</a>, только на уровне не управленческого контура, а исполнения. Там закрывается приток идей, здесь — видимость того, кто и как работает."),
            ("q", "Компания, не знающая своей реальной топологии, рано или поздно начинает управлять организацией, которой на практике уже не существует."),
            ("p", "Практический вывод скромнее, чем звучит вывод общий. Не нужно строить систему тотального контроля и не нужно бороться с неформальными связями — они и есть признак того, что люди пытаются работать в неудобных условиях. Нужно знать <strong>кто на самом деле принимает решения, как на самом деле идёт работа, где находятся скрытые координационные центры и какие неформальные структуры сейчас тихо держат систему</strong>. Этого знания достаточно, чтобы перестать удивляться."),
            ("p", "Заготовка для фиксации того, кто и что решил, — <a href=\"{{HOME}}templates/decision-record/\">шаблон протокола решения</a>."),
        ],

        "en": [
            ("p", "Some organisations develop structures that are nowhere formally documented yet determine how work actually gets done. An employee — a manager, architect, developer, producer, project manager — gradually builds a micro-system around themselves."),
            ("p", "They bring in assistants. They pass part of the work to contractors. They rely on trusted people outside the company. They create informal channels for execution and decision-making. Formally, nothing on the chart changes. In practice, another node appears that the company doesn't know about."),
            ("q", "The formal chart almost never matches the real architecture of work. The only question is whether the organisation knows it."),

            ("h2", "The same phenomenon in different costumes"),
            ("p", "People usually recall this through stories about US developers quietly outsourcing their tasks to developers in China. A vivid story, but a narrow one — the class of phenomena is broader and includes things that feel unrelated."),
            ("ul", [
                "<strong>Work moved outside the company.</strong> Contractors, assistants, acquaintances — paid out of pocket and invisible to any budget.",
                "<strong>Undeclared use of AI in the work.</strong> Functionally the same externalisation of execution; the executor simply isn't a person.",
                "<strong>People who learned to pass interviews better than to do the job.</strong> The gap gets closed by the same micro-system — somebody doing the work for them.",
                "<strong>Upward influence.</strong> Someone lower in the hierarchy who reliably shapes decisions that are formally made above them.",
            ]),
            ("p", "I place these in one analytical category deliberately. Not because they are equally ethical — they aren't — but because for the organisation they produce the same effect: <strong>the real execution structure diverges from the formal one, and the divergence is recorded nowhere</strong>."),

            ("h2", "Why it appears on its own"),
            ("p", "Companies often treat such structures as suspicious or inherently unhealthy. But they emerge not from bad character, but from how the system is built."),
            ("p", "The reason is simple: a formal chart describes reporting lines, and work does not flow along reporting lines. As pressure, complexity and speed increase, people naturally create local adaptation structures:"),
            ("ul", [
                "personal delegation channels — who can actually be handed a task and return a result;",
                "their own knowledge networks — who to ask, bypassing whoever formally owns the answer;",
                "informal escalation paths — how to raise a problem without three rounds of approval;",
                "trusted operational nodes — people through whom a disproportionate amount of work somehow passes.",
            ]),
            ("p", "Each of these solves a real problem. That is exactly why prohibition doesn't remove them: a ban removes the channel, not the need, and within a month a new and less visible one appears."),
            ("note", "A test that nearly always works: ask who could take three weeks off in a way everyone would notice. The answer almost never matches the reporting chart — and that is your map of the real nodes."),

            ("h2", "The problem isn't that they exist — it's that they're invisible"),
            ("p", "Two different statements are worth separating. \"This company has informal structures\" is normal and inevitable. \"This company doesn't know which ones\" is a risk, and here is what it consists of."),
            ("table", {
                "caption": "What happens when the real production topology isn't visible",
                "head": ["Effect", "How it shows up", "When it is discovered"],
                "rows": [
                    ["The production system is partly invisible", "Part of the work is done by people and in places nobody accounts for", "When trying to scale or reproduce the process"],
                    ["Ownership blurs", "\"Who is responsible\" has a formal answer and an actual one, and they differ", "When something breaks and somebody has to be asked"],
                    ["Hidden knowledge dependencies", "A process rests on a person nobody recorded as critical", "The moment they leave or take holiday"],
                    ["Untracked points of failure", "A node nobody considered, because it isn't on the chart", "Simultaneously with the failure"],
                    ["Critical flows outside observability", "Work runs through people and tools beyond the company perimeter", "At an audit, an incident, or a review"],
                ],
            }),
            ("p", "The last row is the expensive one. If a meaningful share of execution physically happens outside the company, the company has no quality control over it, no legal frame around it, and no way of knowing that data went somewhere it shouldn't have."),

            ("h2", "How to see the real topology"),
            ("p", "The key point: this is an observation task, not an investigation. The moment people conclude that blame is being assigned, the picture distorts irreversibly — for the same reasons described in <a href=\"../silent-failure-mode/\">the silent failure mode</a>: the system stops letting the signal through and you blind yourself for a long time."),
            ("steps", [
                ("Ask about flow, not about reporting",
                 "Not \"who is your manager\" but \"who does this task pass through, from appearing to being done\". The second question gives you the real sequence; the first gives you the org chart you already have."),
                ("Find nodes by load, not by title",
                 "Who gets messaged more than their role implies? Without whom do three processes stall at once? Who gets asked instead of whoever formally owns the answer?"),
                ("Work out which problem each informal channel solves",
                 "The channel exists because the formal route is expensive or broken. Until the cause is removed, the channel will reappear."),
                ("Legalise what works",
                 "If a person has in fact become a coordination centre, name it and give them the authority. If work genuinely goes to a contractor, put it under contract. Legalising turns a risk into a structure."),
                ("Close what creates real risk",
                 "Data outside the perimeter, execution without a contract, dependence on one person with no substitute. This part needs a decision, not a conversation."),
            ]),
            ("p", "The difference between legalising and banning is fundamental. A ban removes the visibility and leaves the phenomenon. Legalising leaves the phenomenon and adds visibility — and a visible dependency is a manageable one."),

            ("h2", "Stability that is actually fragility"),
            ("p", "An interesting property of such organisations is that from outside they look exceptionally stable. Processes run smoothly, people understand the rules of the game, leaders speak the same language."),
            ("p", "But that same stability can conceal a growing vulnerability: the system starts reproducing itself rather than adapting to its environment. The mechanism is the same as in <a href=\"../infrastructure-inbreeding/\">infrastructure inbreeding</a>, one level down — there the inflow of ideas closes, here the visibility of who does what and how."),
            ("q", "A company that doesn't know its real topology eventually ends up managing an organisation that no longer exists in practice."),
            ("p", "The practical conclusion is more modest than the general one sounds. You don't need total surveillance, and you don't need to fight informal connections — they are the sign that people are trying to work under awkward conditions. You need to know <strong>who really makes decisions, how work actually flows, where the hidden coordination centres are, and which informal structures are quietly holding the system together</strong>. That much knowledge is enough to stop being surprised."),
            ("p", "A starting point for recording who decided what is <a href=\"{{HOME}}templates/decision-record/\">the decision record template</a>."),
        ],
    },
    takeaways={
        "ru": [
            "Формальная схема описывает подчинение, а работа идёт не по подчинению — расхождение есть в любой достаточно сложной организации.",
            "Вынос работы наружу, необъявленное использование ИИ, умение проходить собеседования вместо умения работать и влияние снизу вверх дают организации один и тот же эффект: реальная схема исполнения не совпадает с формальной.",
            "Неформальные структуры решают настоящие проблемы, поэтому запрет убирает канал, а не потребность: через месяц появляется новый и менее заметный.",
            "Риск не в существовании таких структур, а в их невидимости: размытое владение, скрытые зависимости от знания, неучтённые точки отказа и критические потоки за периметром наблюдаемости.",
            "Проверка на реальные узлы: кто может уйти в отпуск на три недели так, что это заметят все. Ответ почти никогда не совпадает со схемой.",
            "Это задача наблюдения, а не расследования: как только начинается поиск виноватых, картина искажается необратимо.",
            "Легализация превращает риск в структуру, запрет — в невидимость. Видимая зависимость управляема, невидимая нет.",
        ],
        "en": [
            "A formal chart describes reporting lines, and work doesn't flow along reporting lines — the divergence exists in any sufficiently complex organisation.",
            "Externalised work, undeclared AI use, interview skill in place of job skill, and upward influence all produce the same effect for the organisation: the real execution structure diverges from the formal one.",
            "Informal structures solve real problems, so a ban removes the channel rather than the need: within a month a new and less visible one appears.",
            "The risk isn't that they exist but that they're invisible: blurred ownership, hidden knowledge dependencies, untracked failure points, and critical flows beyond observability.",
            "A test for real nodes: who could take three weeks off in a way everyone would notice. The answer almost never matches the chart.",
            "This is an observation task, not an investigation: the moment blame enters, the picture distorts irreversibly.",
            "Legalising turns a risk into a structure; banning turns it into invisibility. A visible dependency is manageable, an invisible one is not.",
        ],
    },
    faq={
        "ru": [
            ("Что такое неформальная структура в организации?",
             "Устойчивый порядок исполнения и принятия решений, который сложился помимо оргсхемы: личные каналы делегирования, собственные сети знаний, обходные пути эскалации и люди, через которых проходит непропорционально много работы. Формально их нет, фактически именно они определяют, как делается работа."),
            ("Это признак проблем в компании?",
             "Само по себе нет. Такие структуры возникают почти в любой достаточно сложной системе, потому что формальная схема описывает подчинение, а работа идёт не по подчинению. Они появляются как ответ на давление, сложность и скорость. Проблемой становится не их наличие, а отсутствие у компании представления о том, какие именно есть."),
            ("Чем это опасно, если работа при этом делается?",
             "Пятью вещами: часть производственной системы становится невидимой, размывается владение, появляются скрытые зависимости от конкретных людей, возникают точки отказа, о которых никто не знает, и критические потоки уходят за периметр наблюдаемости. Последнее опаснее всего: если исполнение физически идёт вне компании, у неё нет ни контроля качества, ни правовой рамки, ни возможности узнать об утечке данных."),
            ("Как обнаружить такие структуры, не устраивая слежку?",
             "Спрашивать про поток, а не про подчинение: через кого проходит задача от появления до готовности. Искать узлы по нагрузке, а не по должности: кому пишут чаще, чем предполагает роль, без кого встают сразу несколько процессов. Простая проверка — кто может уйти в отпуск на три недели так, что это заметят все."),
            ("Что делать с найденным — запрещать?",
             "Запрет убирает канал, но не потребность, которая его породила, поэтому канал воспроизводится в менее заметном виде. Работающее лучше легализовать: если человек стал координационным центром — дать ему полномочия, если работа уходит подрядчику — оформить отношения. Закрывать решением стоит только то, что создаёт настоящий риск: данные за периметром, исполнение без договора, зависимость от одного человека без замены."),
            ("Почему такие компании выглядят стабильными?",
             "Потому что локально всё работает: процессы идут гладко, люди понимают правила, руководители говорят на одном языке. Эта стабильность и есть симптом — система начинает воспроизводить себя вместо того, чтобы адаптироваться. Механизм тот же, что у инфраструктурного инбридинга, только на уровне исполнения, а не управленческого контура."),
        ],
        "en": [
            ("What is an informal structure in an organisation?",
             "A stable pattern of execution and decision-making that formed outside the org chart: personal delegation channels, private knowledge networks, bypass escalation routes, and people through whom a disproportionate amount of work passes. Formally they don't exist; in practice they determine how work gets done."),
            ("Is it a sign of a troubled company?",
             "Not in itself. Such structures arise in almost any sufficiently complex system, because a formal chart describes reporting lines and work doesn't flow along them. They appear as a response to pressure, complexity and speed. What becomes a problem is not their existence but the company having no idea which ones it has."),
            ("What's the danger if the work still gets done?",
             "Five things: part of the production system becomes invisible, ownership blurs, hidden dependencies on specific people appear, failure points emerge that nobody knows about, and critical flows move beyond observability. The last is the worst: if execution physically happens outside the company, there is no quality control, no legal frame, and no way to learn that data went where it shouldn't."),
            ("How do I find these structures without surveillance?",
             "Ask about flow rather than reporting: who does a task pass through from appearing to being done. Find nodes by load rather than title: who gets messaged more than their role implies, without whom several processes stall at once. A simple test — who could take three weeks off in a way everyone would notice."),
            ("What should I do with what I find — ban it?",
             "A ban removes the channel but not the need that created it, so the channel reappears in a less visible form. What works is better legalised: if a person has become a coordination centre, give them the authority; if work goes to a contractor, put it under contract. Only what creates real risk should be closed by decision: data outside the perimeter, execution without a contract, dependence on one person with no substitute."),
            ("Why do such companies look stable?",
             "Because locally everything works: processes run smoothly, people understand the rules, leaders speak the same language. That stability is itself the symptom — the system starts reproducing itself instead of adapting. The mechanism is the same as infrastructure inbreeding, one level down: at the level of execution rather than the leadership pipeline."),
        ],
    },
)
