# -*- coding: utf-8 -*-
POST = dict(
    slug="infrastructure-inbreeding",
    date="2026-06-02",
    updated="2026-08-27",
    tag={"en": "Leadership", "ru": "Управление"},
    title={
        "en": "Infrastructure Inbreeding: Why Promoting Only From Within Puts Your Company at Risk",
        "ru": "Инфраструктурный инбридинг: почему повышать только своих — риск для компании",
    },
    h1={
        "en": "Infrastructure Inbreeding: Why Promoting Only From Within Puts Your Company at Risk",
        "ru": "Инфраструктурный инбридинг: почему повышать только своих — риск для компании",
    },
    dek={
        "en": "Universities have a name for hiring only their own graduates. Most companies have the same problem — they just don't have a name for it, so nobody manages it.",
        "ru": "У университетов есть название для найма только своих выпускников. У компаний та же проблема — просто без названия, поэтому ей никто не управляет.",
    },
    description={
        "en": "Why a closed leadership pipeline quietly erodes a company's ability to adapt, the five symptoms that show up before the numbers move, and a diagnostic you can run on your own org chart in 20 minutes.",
        "ru": "Почему закрытый управленческий контур незаметно убивает способность компании адаптироваться, пять симптомов, которые появляются раньше плохих цифр, и диагностика оргструктуры за 20 минут.",
    },
    keywords={
        "en": "internal promotion vs external hiring, organizational inbreeding, leadership pipeline, succession planning risk, groupthink in management, executive hiring strategy, organizational design, closed talent pipeline",
        "ru": "внутреннее повышение или внешний найм, организационный инбридинг, кадровый резерв, риски преемственности, групповое мышление в управлении, найм руководителей, организационный дизайн, закрытый кадровый контур",
    },
    hashtags=["OrganizationalDesign", "Leadership", "CorporateCulture", "TalentStrategy", "ExecutiveHiring"],
    related=["audit-nobody-reads", "lidl-digital-transformation-failure", "how-to-choose-a-consultant"],
    body={
        "en": [
            ("p", "Universities have a name for hiring almost exclusively their own graduates: <strong>academic inbreeding</strong>. Fewer competing ideas, more replication of the same approach, slow intellectual isolation. It is studied, measured, and in many countries actively regulated."),
            ("p", "Companies have exactly the same pattern at the leadership level. They just don't have a name for it — which is why nobody owns it, nobody measures it, and it never appears on a risk register."),
            ("p", "Short version: <strong>promoting from within is not the problem. A pipeline that closes almost entirely is.</strong> The practical line sits somewhere around one in four to one in three senior roles being filled from outside. Below that, an organization gradually stops importing new reference points, and calm becomes the main symptom."),

            ("h2", "What infrastructure inbreeding actually means"),
            ("p", "Infrastructure inbreeding is the state where most of the people who decide how a company works learned how a company works <em>at that company</em>. Not a hiring policy — an accumulated outcome. Nobody signs off on it. It happens because internal promotion is cheaper, faster, less risky per decision, and easier to defend in a room."),
            ("p", "Each individual promotion is defensible. The aggregate is what does the damage: after enough of them, the entire senior layer shares one reference set. The same escalation habits. The same idea of what \"normal\" looks like. The same blind spots — held with the confidence of consensus, because everyone in the room genuinely agrees."),
            ("p", "That last part is what makes it hard to see from the inside. Inbreeding doesn't feel like a lack of diversity. It feels like alignment."),

            ("h2", "Why internal promotion is still the right default"),
            ("p", "It would be easy — and wrong — to read this as an argument for hiring outsiders into every senior seat. Internal promotion earns its place:"),
            ("ul", [
                "<strong>Context transfer is free.</strong> A promoted director already knows which systems lie, which team is overloaded, and which customer nobody wants to lose.",
                "<strong>Ramp time is short.</strong> An outside hire at the director level typically needs two to three quarters before their decisions are better than a coin flip; an internal one is productive immediately.",
                "<strong>Retention.</strong> A visible internal path keeps the people you'd hate to replace.",
                "<strong>Cultural continuity.</strong> Someone who already believes what the company believes doesn't have to be convinced of it under deadline pressure.",
            ]),
            ("p", "So the question is never \"internal or external.\" It is: <em>what share of your senior decision-making capacity was formed somewhere else?</em> That is a ratio, and ratios can be managed."),

            ("h2", "Five symptoms that show up before the numbers move"),
            ("p", "Financial damage from a closed pipeline arrives late — usually two to four years after the pipeline actually closed. These show up first:"),
            ("ol", [
                "<strong>New ideas get processed as loyalty tests.</strong> A proposal that contradicts existing practice is discussed in terms of who suggested it and what it implies about current leadership, not in terms of whether it's right.",
                "<strong>Every comparison is internal.</strong> Performance conversations reference last year's version of the company. Nobody in the room can say with authority \"at my previous company, this took four days, not three weeks\" — because nobody has a previous company.",
                "<strong>Post-mortems converge on process, never on premise.</strong> Failures produce a new checkpoint or approval step; they rarely produce the conclusion that the underlying approach was wrong.",
                "<strong>Outside candidates get filed as \"culture fit\" rejections.</strong> Specifically at senior levels, and specifically the ones with unfamiliar experience. Check your own rejection notes for the phrase.",
                "<strong>Vendor and consultant selection favours agreement.</strong> The contractor who confirms the plan wins over the one who questions the premise — even when the second one is cheaper.",
            ]),
            ("q", "The organization stops adapting to its environment and starts reproducing itself. From the inside, that feels like maturity."),

            ("h2", "Why the calm is the dangerous part"),
            ("p", "Companies in this state usually look excellent on the outside. Processes run. Meetings are short. Handovers are clean. Everyone uses the same vocabulary, so communication overhead is genuinely low. Employee survey scores on \"clarity\" and \"alignment\" are often high."),
            ("p", "All of that is real. It is also exactly what a system looks like when it has optimized itself against a version of the market that existed three years ago. Friction inside an organization is not only cost — some of it is the sound of different models of reality being reconciled. Remove all of it and you have removed the mechanism that notices a changed environment."),
            ("p", "This is the same structural failure described in <a href=\"../lidl-digital-transformation-failure/\">the Lidl case</a>: reporting stayed calm and clean while the underlying reality drifted, because the layers that could have raised the alarm shared the same assumptions as the layers receiving the report."),

            ("h2", "What a healthy ratio looks like"),
            ("p", "There is no universal number, and anyone who gives you one without asking about your stage is selling something. But the direction of travel is consistent — the faster your market changes, the more outside reference points your senior layer needs."),
            ("table", {
                "caption": "Rough external-hire share of senior roles by company situation",
                "head": ["Situation", "External share of senior hires", "Why"],
                "rows": [
                    ["Stable market, mature operations, incremental change", "15–25%", "Continuity is worth more than novelty; you mostly need execution consistency."],
                    ["Growing company entering new segments or geographies", "30–40%", "You are entering problems nobody inside has solved before; buying that experience is cheaper than learning it live."],
                    ["Technology or regulatory shift underway", "40–50%", "Your internal reference set is actively expiring. Import people whose defaults were formed in the new environment."],
                    ["Post-crisis or turnaround", "50%+ temporarily", "You need people whose credibility isn't tied to the decisions that caused the crisis."],
                ],
            }),
            ("p", "Two rules matter more than the exact percentage. First, count <em>capacity</em>, not headcount: one external hire in a role with no decision rights doesn't change anything. Second, spread them: five external hires in one department is a beachhead, not diversity of thought."),

            ("h2", "A 20-minute diagnostic on your own org chart"),
            ("p", "You do not need a consulting engagement to find out where you stand. You need your org chart and one honest hour."),
            ("steps", [
                ("List your senior decision-makers", "Everyone who can approve a budget, kill a project, or change a process without asking anyone else. In most companies that's 8–30 people, and the list is shorter than the org chart suggests."),
                ("Mark where each of them learned their trade", "Not where they were hired from — where they formed their working defaults. Someone hired from outside eleven years ago is an internal reference point now."),
                ("Calculate the share formed elsewhere within the last 5 years", "This is your live external ratio. Under 20% in a moving market is the warning zone."),
                ("Check the distribution", "Are the externally-formed people concentrated in one function, and is that function one that touches strategy — or is it all in sales?"),
                ("Look at your last five senior rejections", "Read the actual rejection reasons. Count how many reduce to \"would not fit how we work.\" That's your intake filter, in writing."),
                ("Look at your last three reversed decisions", "Who raised the objection first, and how long did it take to be heard? If the answer is \"the same two people, and months,\" your dissent capacity is a single point of failure."),
            ]),

            ("h2", "If the diagnostic comes back badly"),
            ("p", "The instinct is to hire an outsider into a big seat. That's the most expensive and least reliable fix — a single senior outside hire dropped into a closed system usually leaves within eighteen months, having changed nothing, which then gets cited as proof that outsiders don't work here."),
            ("p", "Cheaper moves, in order of what tends to work:"),
            ("ul", [
                "<strong>Hire externally two levels below the seat you're worried about</strong> — where the person has real work to do, has time to build credibility, and isn't fighting the whole system on day one.",
                "<strong>Put an outside reference point in the room without hiring one.</strong> An advisor, a fixed-scope external review, a peer from another industry on a quarterly call. The point is a voice with no stake in past decisions.",
                "<strong>Change what post-mortems are allowed to conclude.</strong> Explicitly require every review to answer \"was the premise wrong?\" before it is allowed to propose a new checkpoint.",
                "<strong>Separate the objection from the objector.</strong> Collect written positions before the meeting, discuss them unattributed. Cheap, awkward, and effective.",
                "<strong>Track the ratio as an actual metric.</strong> Anything that isn't measured drifts back. Put it in the same review as headcount and attrition.",
            ]),
            ("note", "If you only do one of these, do the third. Changing what a post-mortem is permitted to conclude costs nothing and immediately surfaces whether the system can question its own premises."),

            ("h2", "The honest counter-argument"),
            ("p", "External hiring has its own failure mode, and pretending otherwise would make this article useless. Outside senior hires fail often — the commonly cited range is somewhere around a third to a half not lasting two years. The causes are consistent: they arrive with a playbook from a different context, apply it before understanding why the current one exists, lose the middle layer, and leave."),
            ("p", "Which means the goal is not \"more outsiders.\" It's <strong>more reference points, deliberately placed, with enough time and authority to matter</strong>. A company that hires externally and then ignores what the hire says has paid full price for zero diversity of thought — and has generated internal evidence for closing the pipeline further."),
            ("p", "That is the actual risk of infrastructure inbreeding: not that it makes bad decisions, but that it removes the mechanism that would have caught them."),
        ],
        "ru": [
            ("p", "У университетов есть название для найма почти исключительно своих выпускников: <strong>академический инбридинг</strong>. Меньше конкурирующих идей, больше копирования одного и того же подхода, медленная интеллектуальная изоляция. Это изучают, измеряют, а в ряде стран прямо регулируют."),
            ("p", "У компаний ровно тот же паттерн на уровне руководства. Просто без названия — поэтому за него никто не отвечает, его никто не измеряет и он никогда не попадает в реестр рисков."),
            ("p", "Коротко: <strong>повышать своих — не проблема. Проблема — когда контур закрывается почти полностью.</strong> Практическая граница проходит где-то на уровне «каждая четвёртая–третья руководящая позиция закрывается снаружи». Ниже — организация постепенно перестаёт получать новые точки отсчёта, и главным симптомом становится спокойствие."),

            ("h2", "Что такое инфраструктурный инбридинг"),
            ("p", "Инфраструктурный инбридинг — это состояние, когда большинство людей, определяющих, как работает компания, научились работать <em>в этой же компании</em>. Это не кадровая политика, а накопленный результат. Никто его не утверждал. Он возникает, потому что внутреннее повышение дешевле, быстрее, менее рискованно в каждом отдельном случае и его проще защитить на совещании."),
            ("p", "Каждое отдельное повышение обосновано. Вредит сумма: после достаточного их количества весь верхний слой разделяет один набор представлений. Одинаковые привычки эскалации. Одинаковое понимание того, что считать нормой. Одинаковые слепые зоны — с уверенностью консенсуса, потому что все в комнате искренне согласны."),
            ("p", "Именно это и мешает увидеть проблему изнутри. Инбридинг не ощущается как нехватка разнообразия. Он ощущается как слаженность."),

            ("h2", "Почему внутреннее повышение всё-таки правильный вариант по умолчанию"),
            ("p", "Прочитать это как призыв сажать внешних людей на каждое руководящее кресло было бы легко — и неверно. Внутреннее повышение своё место заслужило:"),
            ("ul", [
                "<strong>Контекст передаётся бесплатно.</strong> Повышенный директор уже знает, какие отчёты врут, какая команда перегружена и какого клиента нельзя потерять.",
                "<strong>Короткий разгон.</strong> Внешнему руководителю уровня директора обычно нужно два–три квартала, прежде чем его решения станут лучше подбрасывания монеты; внутренний продуктивен сразу.",
                "<strong>Удержание.</strong> Видимый внутренний путь удерживает тех, кого крайне не хочется заменять.",
                "<strong>Культурная непрерывность.</strong> Человека, который уже разделяет ценности компании, не придётся убеждать в них под давлением дедлайна.",
            ]),
            ("p", "Поэтому вопрос никогда не звучит как «свой или чужой». Он звучит так: <em>какая доля вашей управленческой способности принимать решения сформировалась где-то ещё?</em> Это соотношение, а соотношением можно управлять."),

            ("h2", "Пять симптомов, которые появляются раньше плохих цифр"),
            ("p", "Финансовый ущерб от закрытого контура приходит поздно — обычно через два-четыре года после того, как контур реально закрылся. А вот это видно сразу:"),
            ("ol", [
                "<strong>Новые идеи обрабатываются как проверка на лояльность.</strong> Предложение, противоречащее текущей практике, обсуждается в терминах «кто это предложил и что это говорит о нынешнем руководстве», а не в терминах «верно ли это».",
                "<strong>Любое сравнение — внутреннее.</strong> На разборе результатов ссылаются на прошлогоднюю версию самой компании. Никто в комнате не может авторитетно сказать «на прежнем месте это занимало четыре дня, а не три недели» — потому что прежнего места ни у кого нет.",
                "<strong>Разборы полётов всегда упираются в процесс и никогда — в предпосылку.</strong> Провал порождает новую точку контроля или согласование; он почти никогда не приводит к выводу, что сам подход был неверным.",
                "<strong>Внешние кандидаты отсеиваются с формулировкой «не наш человек».</strong> Именно на старших позициях и именно те, у кого непривычный опыт. Проверьте собственные отказы на эту формулировку.",
                "<strong>Подрядчиков и консультантов выбирают по согласию.</strong> Побеждает тот, кто подтверждает план, а не тот, кто ставит под сомнение предпосылку — даже когда второй дешевле.",
            ]),
            ("q", "Организация перестаёт адаптироваться к среде и начинает воспроизводить саму себя. Изнутри это ощущается как зрелость."),

            ("h2", "Чем опасно спокойствие"),
            ("p", "Компании в этом состоянии обычно отлично выглядят снаружи. Процессы работают. Совещания короткие. Передача задач чистая. Все говорят на одном языке, поэтому накладные расходы на коммуникацию действительно низкие. Опросы сотрудников по пунктам «ясность» и «согласованность» часто показывают высокие баллы."),
            ("p", "Всё это правда. И ровно так же выглядит система, которая оптимизировала себя под рынок трёхлетней давности. Трение внутри организации — не только издержка; часть его — это звук сверки разных моделей реальности. Уберите его целиком, и вы уберёте механизм, замечающий, что среда изменилась."),
            ("p", "Это тот же структурный сбой, что описан в <a href=\"../lidl-digital-transformation-failure/\">разборе кейса Lidl</a>: отчётность оставалась спокойной и чистой, пока реальность уезжала в сторону, потому что слои, способные поднять тревогу, разделяли те же предпосылки, что и слои, принимающие отчёт."),

            ("h2", "Как выглядит здоровое соотношение"),
            ("p", "Универсального числа нет, и тот, кто называет его, не спросив о вашей стадии, что-то вам продаёт. Но направление устойчиво: чем быстрее меняется ваш рынок, тем больше внешних точек отсчёта нужно верхнему слою."),
            ("table", {
                "caption": "Ориентировочная доля внешнего найма на руководящие позиции",
                "head": ["Ситуация", "Доля внешнего найма", "Почему"],
                "rows": [
                    ["Стабильный рынок, зрелые операции, постепенные изменения", "15–25%", "Непрерывность ценнее новизны; нужна в первую очередь ровность исполнения."],
                    ["Рост, выход в новые сегменты или страны", "30–40%", "Вы входите в задачи, которых внутри никто не решал; купить этот опыт дешевле, чем осваивать его на живом проекте."],
                    ["Идёт технологический или регуляторный сдвиг", "40–50%", "Внутренний набор представлений активно устаревает. Нужны люди, чьи установки сформировались уже в новой среде."],
                    ["Кризис или разворот", "временно 50%+", "Нужны люди, чья репутация не связана с решениями, которые привели к кризису."],
                ],
            }),
            ("p", "Два правила важнее точного процента. Первое: считайте <em>полномочия</em>, а не головы — один внешний человек на позиции без права решения не меняет ничего. Второе: распределяйте — пять внешних наймов в одном отделе это плацдарм, а не разнообразие мышления."),

            ("h2", "Диагностика оргструктуры за 20 минут"),
            ("p", "Чтобы понять, где вы находитесь, консалтинговый проект не нужен. Нужна оргструктура и один честный час."),
            ("steps", [
                ("Выпишите тех, кто реально принимает решения", "Все, кто может утвердить бюджет, закрыть проект или изменить процесс, ни у кого не спрашивая. В большинстве компаний это 8–30 человек, и список короче, чем кажется по оргструктуре."),
                ("Отметьте, где каждый научился профессии", "Не откуда его наняли, а где сформировались его рабочие установки. Человек, пришедший снаружи одиннадцать лет назад, сегодня — внутренняя точка отсчёта."),
                ("Посчитайте долю тех, кто сформировался вне компании за последние 5 лет", "Это ваш живой внешний коэффициент. Меньше 20% на подвижном рынке — зона предупреждения."),
                ("Проверьте распределение", "Внешние люди сконцентрированы в одной функции? И эта функция влияет на стратегию — или это всё продажи?"),
                ("Посмотрите последние пять отказов на старших позициях", "Прочитайте реальные причины отказа. Посчитайте, сколько сводится к «не впишется в то, как мы работаем». Это ваш фильтр на входе, в письменном виде."),
                ("Посмотрите последние три отменённых решения", "Кто первым высказал возражение и сколько времени понадобилось, чтобы его услышали? Если ответ «те же два человека, и месяцы» — ваша способность к несогласию держится на одной точке отказа."),
            ]),

            ("h2", "Что делать, если диагностика прошла плохо"),
            ("p", "Первый инстинкт — нанять чужого на большую должность. Это самое дорогое и наименее надёжное решение: один внешний руководитель, посаженный в закрытую систему, обычно уходит в течение полутора лет, ничего не изменив, — и это потом цитируют как доказательство того, что «чужие у нас не приживаются»."),
            ("p", "Более дешёвые ходы, в порядке того, что обычно срабатывает:"),
            ("ul", [
                "<strong>Нанимайте снаружи на два уровня ниже проблемной позиции</strong> — там у человека есть реальная работа, время наработать репутацию и нет необходимости воевать со всей системой с первого дня.",
                "<strong>Поставьте внешнюю точку отсчёта в комнату, не нанимая её.</strong> Советник, внешний обзор с фиксированным объёмом, коллега из другой отрасли на ежеквартальном созвоне. Смысл в голосе, не заинтересованном в прошлых решениях.",
                "<strong>Измените, к каким выводам вообще разрешено приходить на разборе.</strong> Прямо требуйте отвечать на вопрос «была ли неверна сама предпосылка?» прежде, чем разрешать предлагать новую точку контроля.",
                "<strong>Отделите возражение от возражающего.</strong> Собирайте письменные позиции до совещания и обсуждайте их без авторства. Дёшево, неловко и работает.",
                "<strong>Ведите соотношение как настоящую метрику.</strong> То, что не измеряется, откатывается назад. Поставьте его в один отчёт с численностью и текучестью.",
            ]),
            ("note", "Если делать что-то одно — делайте третье. Изменить, к каким выводам разрешено приходить на разборе полётов, стоит ноль и сразу показывает, способна ли система усомниться в собственных предпосылках."),

            ("h2", "Честный контраргумент"),
            ("p", "У внешнего найма есть свой режим отказа, и умалчивать о нём — значит обесценить всю статью. Внешние руководители проваливаются часто: обычно называют цифры от трети до половины, не доживающих до двух лет. Причины устойчивы: человек приходит со сценарием из другого контекста, применяет его раньше, чем понял, почему здесь устроено иначе, теряет средний слой и уходит."),
            ("p", "Значит, цель не «больше чужих». Цель — <strong>больше точек отсчёта, размещённых осознанно, с достаточным временем и полномочиями, чтобы это имело значение</strong>. Компания, которая нанимает снаружи, а потом игнорирует то, что человек говорит, заплатила полную цену за нулевое разнообразие мышления — и заодно произвела внутреннее доказательство в пользу того, чтобы закрыть контур ещё сильнее."),
            ("p", "В этом и состоит настоящий риск инфраструктурного инбридинга: не в том, что система принимает плохие решения, а в том, что она лишается механизма, который эти решения поймал бы."),
        ],
    },
    takeaways={
        "en": [
            "Internal promotion isn't the risk; a pipeline where fewer than one in five senior decision-makers formed their judgement elsewhere is.",
            "The first symptoms are behavioural, not financial: post-mortems that only ever change process, and \"culture fit\" as a rejection reason at senior level.",
            "Unusual calm and very low internal friction are diagnostic signals, not achievements.",
            "Count decision-making authority, not headcount — and spread external hires across functions rather than concentrating them.",
            "The cheapest effective intervention is changing what a post-mortem is allowed to conclude.",
            "External hiring fails often too; the goal is more reference points with real authority, not more outsiders.",
        ],
        "ru": [
            "Риск не в повышении своих, а в контуре, где меньше одного из пяти принимающих решения сформировался вне компании.",
            "Первые симптомы поведенческие, а не финансовые: разборы, которые меняют только процесс, и «не наш человек» как причина отказа на старших позициях.",
            "Непривычное спокойствие и очень низкое внутреннее трение — это диагностический признак, а не достижение.",
            "Считайте полномочия, а не головы, и распределяйте внешний найм по функциям, а не концентрируйте в одной.",
            "Самое дешёвое работающее вмешательство — изменить, к каким выводам разрешено приходить на разборе полётов.",
            "Внешний найм тоже часто проваливается; цель — больше точек отсчёта с реальными полномочиями, а не больше чужих.",
        ],
    },
    faq={
        "en": [
            ("What is organizational or infrastructure inbreeding?",
             "It is the state where most of a company's senior decision-makers formed their professional judgement inside that same company. It is not a policy but an accumulated outcome of many individually reasonable promotions, and its main effect is that the organization loses the outside reference points it needs to notice when its environment has changed."),
            ("What percentage of senior hires should come from outside?",
             "There is no universal figure. As a working range: 15–25% in a stable market with mature operations, 30–40% for a company entering new segments or geographies, 40–50% during a technology or regulatory shift, and temporarily above 50% in a turnaround. Distribution matters as much as the number — external hires concentrated in one function do not create diversity of thought."),
            ("How do I tell the difference between a strong culture and inbreeding?",
             "A strong culture survives disagreement; inbreeding avoids it. The practical test is your last three reversed decisions: if the objection came from the same one or two people every time and took months to be heard, you are looking at inbreeding wearing culture's clothes."),
            ("Isn't hiring outsiders into senior roles risky?",
             "Yes — a third to a half of senior external hires do not last two years, usually because they apply a playbook from a different context before understanding the current one. That is an argument for hiring externally lower down, giving new arrivals real authority and time, and adding outside reference points through advisors or fixed-scope reviews — not for closing the pipeline."),
            ("What is the cheapest way to add an outside perspective without hiring?",
             "A fixed-scope external review or an advisor with no stake in past decisions. The value is not the deliverable; it is having one voice in the room whose credibility does not depend on last year's choices being correct."),
            ("How long does it take before a closed pipeline shows up in results?",
             "Typically two to four years. Behavioural symptoms appear much earlier, which is why the diagnostic in this article looks at decision behaviour and rejection reasons rather than at financial metrics."),
        ],
        "ru": [
            ("Что такое организационный (инфраструктурный) инбридинг?",
             "Это состояние, при котором большинство принимающих решения руководителей сформировали профессиональные установки внутри той же компании. Это не политика, а накопленный результат множества по отдельности разумных повышений. Главный эффект — организация теряет внешние точки отсчёта, без которых не замечает, что среда изменилась."),
            ("Какая доля руководителей должна приходить извне?",
             "Универсальной цифры нет. Рабочий ориентир: 15–25% на стабильном рынке со зрелыми операциями, 30–40% при выходе в новые сегменты или страны, 40–50% при технологическом или регуляторном сдвиге и временно больше 50% при развороте. Распределение важно не меньше цифры: внешние наймы, собранные в одной функции, разнообразия мышления не создают."),
            ("Как отличить сильную культуру от инбридинга?",
             "Сильная культура выдерживает несогласие, инбридинг его избегает. Практическая проверка — три последних отменённых решения: если возражение каждый раз исходило от одних и тех же одного-двух человек и его слышали месяцами, перед вами инбридинг в одежде культуры."),
            ("Разве нанимать чужих на руководящие позиции не рискованно?",
             "Рискованно: от трети до половины внешних руководителей не доживают до двух лет, обычно потому что применяют сценарий из другого контекста раньше, чем разобрались в текущем. Это довод за то, чтобы нанимать снаружи на уровень-два ниже, давать пришедшим реальные полномочия и время и добавлять внешние точки зрения через советников и обзоры с фиксированным объёмом, — а не за то, чтобы закрывать контур."),
            ("Как дёшево добавить внешний взгляд, не нанимая человека?",
             "Внешний обзор с фиксированным объёмом или советник, не заинтересованный в прошлых решениях. Ценность не в отчёте, а в наличии голоса, чья репутация не зависит от того, были ли прошлогодние решения правильными."),
            ("Через сколько закрытый контур проявится в результатах?",
             "Обычно через два-четыре года. Поведенческие симптомы видны гораздо раньше — поэтому диагностика в этой статье смотрит на поведение при принятии решений и на причины отказов, а не на финансовые метрики."),
        ],
    },
)
