# -*- coding: utf-8 -*-
POST = dict(
    slug="lidl-digital-transformation-failure",
    date="2026-06-16",
    updated="2026-08-27",
    tag={"en": "Case Study", "ru": "Разбор кейса"},
    title={
        "en": "How Lidl Lost €500 Million: A Case Study in Digital Transformation Failure",
        "ru": "Как Lidl потерял €500 млн: разбор провала цифровой трансформации",
    },
    h1={
        "en": "How Lidl Lost €500 Million: A Case Study in Digital Transformation Failure",
        "ru": "Как Lidl потерял €500 млн: разбор провала цифровой трансформации",
    },
    dek={
        "en": "The eLWIS project didn't fail in a single moment. It drifted for seven years — until keeping it alive cost more than admitting it was dead.",
        "ru": "Проект eLWIS не провалился в один момент. Он уезжал в сторону семь лет — пока поддерживать его не стало дороже, чем признать мёртвым.",
    },
    description={
        "en": "A breakdown of Lidl's abandoned SAP rollout: how customising software instead of changing one process, plus a widening gap between reports and reality, burned roughly €500 million — and the five checks that catch the same drift early.",
        "ru": "Разбор отменённого внедрения SAP в Lidl: как доработка системы вместо изменения одного процесса и растущий разрыв между отчётами и реальностью сожгли около €500 млн — и пять проверок, ловящих тот же сценарий заранее.",
    },
    keywords={
        "en": "Lidl SAP failure, eLWIS project, digital transformation failure case study, ERP implementation failure, SAP customization risk, change management failure, IT project governance, sunk cost in IT projects",
        "ru": "провал SAP в Lidl, проект eLWIS, кейс провала цифровой трансформации, провал внедрения ERP, риски доработки SAP, управление изменениями, управление ИТ-проектами, невозвратные издержки в ИТ",
    },
    hashtags=["DigitalTransformation", "ProjectManagement", "ChangeManagement", "ERP", "RiskManagement"],
    related=["erp-implementation-failure-reasons", "infrastructure-inbreeding", "audit-nobody-reads"],
    body={
        "en": [
            ("p", "In 2011 Lidl started eLWIS — an SAP for Retail programme meant to replace its in-house merchandise management system across a business operating in around 30 countries. In 2018 the company cancelled it and went back to the old system. Publicly reported cost: roughly <strong>€500 million</strong>."),
            ("p", "The short version of what went wrong is not \"SAP is bad\" and not \"Lidl was incompetent.\" It is this: <strong>the company chose to bend the software around one existing process rather than change the process, and then spent seven years paying compound interest on that decision</strong> while its reporting stayed calm."),
            ("p", "That combination — a customisation taken to protect a competitive advantage, plus a governance layer that couldn't see the cost accumulating — is the most common way large transformations die. Below is what actually happened, why each step looked reasonable at the time, and the five checks that would have surfaced it years earlier."),

            ("h2", "The timeline, briefly"),
            ("table", {
                "caption": "Lidl eLWIS — publicly reported milestones",
                "head": ["Period", "What happened"],
                "rows": [
                    ["2011", "Programme starts. Goal: replace the legacy in-house merchandise management system with SAP for Retail across the group."],
                    ["2011–2016", "Multi-year build with heavy customisation. Deadlines move. Scope stays."],
                    ["~2017", "Limited rollouts reported in smaller markets — Austria, Northern Ireland, the United States. CEO Sven Seidel leaves after less than three years; senior IT leadership changes around the same time."],
                    ["2018", "Programme cancelled. Lidl returns to the legacy system. Reported spend ≈ €500 million."],
                ],
            }),
            ("p", "Note the shape of that table. There is no disaster in it. No outage, no breach, no single catastrophic go-live. The failure is entirely made of time."),

            ("h2", "The decision that set the direction: inventory valuation"),
            ("p", "The widely reported technical root is unglamorous. Lidl valued inventory at <strong>purchase price</strong>. SAP's retail standard is built around <strong>retail price</strong> valuation. Two defensible accounting conventions, incompatible defaults."),
            ("p", "Lidl had a real reason to keep its convention: purchase-price logic was woven into how the company negotiated, priced and measured itself, and leadership was unwilling to give up something it treated as a competitive edge. So the decision was made to adapt the software to the process instead of the process to the software."),
            ("p", "Read in isolation, that is a reasonable business call. The problem is what it implies structurally:"),
            ("ul", [
                "A core valuation change is not a setting. It reaches into procurement, replenishment, pricing, store operations and reporting — so the customisation is not one change, it is a permanent branch line running through the whole system.",
                "Every standard-product update now has to be re-reconciled against that branch. Upgrade cost stops being an event and becomes a running tax.",
                "The system can no longer be tested against the vendor's reference behaviour, because it no longer behaves like the reference. You lose the cheapest source of truth you had.",
                "The people who understand the branch become a bottleneck — and, over seven years, they change jobs.",
            ]),
            ("q", "Customisation is not a cost. It is a subscription, and nobody puts the renewal price on the business case."),
            ("p", "This is the general rule the case illustrates: <em>the expensive part of a customisation is never the customisation. It is everything that afterwards has to be reconciled with it, forever.</em>"),

            ("h2", "Why nobody stopped it"),
            ("p", "Seven years is a long time to not stop something. It is worth being precise about why that happens, because the mechanism is the transferable part."),
            ("h3", "1. Every increment was locally rational"),
            ("p", "No one ever approved \"spend €500m and cancel.\" They approved a sequence of small, sensible-looking things: this integration, that reconciliation, one more quarter of stabilisation. Each was cheaper than stopping. That is the defining property of drift — at every single decision point, continuing is the cheaper option, right up until the whole thing is written off."),
            ("h3", "2. Reporting measured activity, not viability"),
            ("p", "Status reporting on programmes like this tracks deliverables completed, tickets closed, modules configured, milestones passed. All of those can be green while the answer to \"will this system run our largest markets at real volume?\" is quietly getting worse. Deployments reportedly worked in smaller markets; the larger, higher-intensity ones were where the customised design ran out of road."),
            ("h3", "3. The escalation path had a filter on it"),
            ("p", "Engineers raised architecture and scalability concerns. The gap between what dashboards showed and what practitioners saw kept widening. Signals that survive four layers of \"let's not escalate that yet\" arrive as adjectives, not as decisions. This is the same structural problem described in <a href=\"../infrastructure-inbreeding/\">infrastructure inbreeding</a>: when the layer raising the alarm and the layer receiving it share assumptions and incentives, the alarm becomes noise."),
            ("h3", "4. Sunk cost had a face"),
            ("p", "By year five, cancelling meant a named executive publicly owning a nine-figure write-off. The CEO left in 2017 amid reported strategy disagreements; senior IT leadership turned over. It is notably common that a programme becomes cancellable only after the people identified with it are gone — which is an organisational fact, not a technical one."),

            ("h2", "What Lidl actually got right"),
            ("p", "Two things, and skipping them would make this a morality tale rather than a case study."),
            ("ul", [
                "<strong>They stopped.</strong> Writing off €500 million and returning to the legacy system was the correct decision, made late. Plenty of comparable programmes never reach that decision at all and keep bleeding.",
                "<strong>They kept the fallback alive.</strong> The old in-house system still worked, which is the only reason cancellation was survivable. Retiring your fallback before the replacement has proven itself at full volume is how a project failure becomes an operational crisis.",
            ]),

            ("h2", "Five checks that catch this pattern early"),
            ("p", "None of these require a consultant, a new tool, or a re-planning exercise. All of them can be run on an existing programme this month."),
            ("steps", [
                ("Write down every deviation from standard, with its permanent owner",
                 "Not a list of change requests — a list of behaviours that will differ from the vendor's product forever. If that list has more than a handful of entries touching core data models, you have chosen a branch line, whether or not anyone said so out loud."),
                ("Price the second upgrade, not the first",
                 "Ask what it will cost to apply the vendor's next two major releases on top of your deviations. If nobody can answer, that number is unbounded and it is already in your budget."),
                ("Define the kill criteria before the next milestone, in writing",
                 "\"If by date X we cannot process the volume of our three largest markets in a production-equivalent test, we stop and reassess.\" Written before the date, by the person who will be in the room after it. Kill criteria written after a slip are negotiations, not criteria."),
                ("Test where it actually hurts, not where it's convenient",
                 "Pilots in small markets are useful for change management and useless for capacity proof. Whatever your equivalent of \"largest, highest-intensity market\" is, that is the only pilot that answers the viability question."),
                ("Ask the practitioners directly, once per quarter, off the reporting line",
                 "One question: \"What would you tell me if there were no consequences?\" Asked by someone senior enough to act and structured so the answer doesn't route through the layer being evaluated. This is the cheapest early-warning system that exists and almost nobody runs it."),
            ]),
            ("note", "A useful rule of thumb: if your programme cannot name a condition under which it would be stopped, it is not a project — it is a commitment. Commitments do not get cancelled; they get written off."),

            ("h2", "The transferable version, for a company that isn't Lidl"),
            ("p", "Most readers are not rolling out SAP across 30 countries. The mechanism scales down perfectly:"),
            ("ul", [
                "You buy a CRM and configure it around your existing sales stages instead of examining whether those stages are right. Two years later, every integration has an exception for you.",
                "You automate an approval chain exactly as it exists, because changing it would require a conversation with a department head. Now the awkward step is faster, permanent and invisible — the failure mode described in <a href=\"../when-not-to-automate/\">when not to automate</a>.",
                "You commission a website rebuild that reproduces the current structure because \"users are used to it,\" then spend the next three years working around a navigation nobody defends.",
            ]),
            ("p", "In every version, the same trade happens: a short, uncomfortable conversation about changing a process is avoided, and its cost is converted into a long, quiet stream of technical debt that never appears as a line item."),
            ("p", "Large transformations rarely break from one bad decision. They break from the accumulated distance between what is actually happening and what people feel safe saying out loud — and that distance is measurable, if anyone is willing to ask."),
        ],
        "ru": [
            ("p", "В 2011 году Lidl запустил eLWIS — программу на SAP for Retail, которая должна была заменить собственную систему товародвижения в бизнесе, работающем примерно в 30 странах. В 2018 году компания отменила проект и вернулась на старую систему. Публично называемая стоимость — около <strong>€500 млн</strong>."),
            ("p", "Короткая версия произошедшего — это не «SAP плохой» и не «в Lidl сидели некомпетентные люди». Это вот что: <strong>компания решила подогнать систему под один существующий процесс вместо того, чтобы изменить процесс, и следующие семь лет платила по этому решению сложный процент</strong>, пока отчётность оставалась спокойной."),
            ("p", "Сочетание «доработка ради защиты конкурентного преимущества» плюс «управляющий слой, не видящий, как накапливается цена» — самый частый способ умирания больших трансформаций. Ниже: что происходило на самом деле, почему каждый шаг выглядел разумным в моменте и пять проверок, которые вскрыли бы это на годы раньше."),

            ("h2", "Хронология, коротко"),
            ("table", {
                "caption": "Lidl eLWIS — публично известные вехи",
                "head": ["Период", "Что происходило"],
                "rows": [
                    ["2011", "Старт программы. Цель — заменить унаследованную собственную систему товародвижения на SAP for Retail по всей группе."],
                    ["2011–2016", "Многолетняя разработка с большим объёмом доработок. Сроки сдвигаются. Объём остаётся."],
                    ["≈2017", "Сообщается об ограниченных запусках на небольших рынках — Австрия, Северная Ирландия, США. CEO Свен Зайдель уходит, проработав меньше трёх лет; примерно тогда же меняется руководство ИТ."],
                    ["2018", "Программа отменена. Lidl возвращается на прежнюю систему. Заявленные расходы ≈ €500 млн."],
                ],
            }),
            ("p", "Обратите внимание на форму этой таблицы. В ней нет катастрофы. Ни аварии, ни утечки, ни одного провального запуска. Провал целиком состоит из времени."),

            ("h2", "Решение, задавшее направление: оценка запасов"),
            ("p", "Широко описанная техническая первопричина совсем не эффектна. Lidl оценивал запасы по <strong>закупочной цене</strong>. Розничный стандарт SAP построен вокруг оценки по <strong>розничной цене</strong>. Две защитимые учётные конвенции с несовместимыми настройками по умолчанию."),
            ("p", "У Lidl была реальная причина держаться за свою: логика закупочной цены была вплетена в то, как компания вела переговоры, формировала цены и оценивала себя, и руководство не собиралось отказываться от того, что считало конкурентным преимуществом. Поэтому решили адаптировать систему под процесс, а не процесс под систему."),
            ("p", "Само по себе это разумное бизнес-решение. Проблема в том, что оно означает структурно:"),
            ("ul", [
                "Изменение базовой логики оценки — это не настройка. Оно тянется в закупки, пополнение, ценообразование, операции магазинов и отчётность, поэтому доработка становится не одним изменением, а постоянной боковой веткой, проходящей через всю систему.",
                "Каждое обновление стандартного продукта теперь нужно заново сводить с этой веткой. Стоимость обновления перестаёт быть событием и превращается в постоянный налог.",
                "Систему больше нельзя проверять по эталонному поведению вендора, потому что она ведёт себя иначе. Вы теряете самый дешёвый источник истины, который у вас был.",
                "Люди, понимающие эту ветку, становятся узким местом — и за семь лет они меняют работу.",
            ]),
            ("q", "Доработка — это не расход. Это подписка, и цену продления никто не вписывает в обоснование проекта."),
            ("p", "Отсюда общее правило, которое иллюстрирует кейс: <em>дорогая часть доработки — никогда не сама доработка. Дорого стоит всё, что потом придётся с ней сводить, и так навсегда.</em>"),

            ("h2", "Почему никто не остановил"),
            ("p", "Семь лет — долгий срок, чтобы что-то не остановить. Здесь важно быть точным, потому что переносимая часть кейса — именно механизм."),
            ("h3", "1. Каждый шаг был локально рациональным"),
            ("p", "Никто никогда не утверждал решение «потратить €500 млн и отменить». Утверждали последовательность мелких разумных вещей: вот эту интеграцию, вон ту сверку, ещё квартал стабилизации. Каждая была дешевле, чем остановиться. Это и есть определяющее свойство дрейфа: в каждой отдельной точке продолжать дешевле — вплоть до момента, когда всё списывается целиком."),
            ("h3", "2. Отчётность мерила активность, а не жизнеспособность"),
            ("p", "Статус таких программ отслеживает закрытые задачи, сконфигурированные модули, пройденные вехи. Всё это может быть зелёным, пока ответ на вопрос «выдержит ли система наши крупнейшие рынки на реальных объёмах?» тихо ухудшается. Запуски, по сообщениям, работали на небольших рынках; именно на крупных и нагруженных доработанная архитектура упёрлась в потолок."),
            ("h3", "3. На пути эскалации стоял фильтр"),
            ("p", "Инженеры поднимали вопросы архитектуры и масштабируемости. Разрыв между тем, что показывали дашборды, и тем, что видели практики, продолжал расти. Сигнал, прошедший через четыре слоя «давайте пока не будем эскалировать», доходит наверх в виде прилагательных, а не решений. Это тот же структурный сбой, что описан в статье про <a href=\"../infrastructure-inbreeding/\">инфраструктурный инбридинг</a>: когда слой, поднимающий тревогу, и слой, её принимающий, разделяют одни предпосылки и одни стимулы, тревога превращается в шум."),
            ("h3", "4. У невозвратных издержек было лицо"),
            ("p", "К пятому году отмена означала, что конкретный руководитель публично признаёт списание девятизначной суммы. CEO ушёл в 2017-м на фоне сообщений о расхождениях по стратегии, руководство ИТ сменилось. Показательно частый сюжет: программа становится отменяемой только после ухода людей, с которыми она отождествлялась. Это организационный факт, а не технический."),

            ("h2", "Что Lidl сделал правильно"),
            ("p", "Две вещи, и без них это была бы притча, а не разбор."),
            ("ul", [
                "<strong>Они остановились.</strong> Списать €500 млн и вернуться на прежнюю систему было верным решением, принятым поздно. Множество похожих программ до этого решения не доходят вообще и продолжают кровоточить.",
                "<strong>Они сохранили запасной вариант.</strong> Старая собственная система продолжала работать — только поэтому отмена оказалась переживаемой. Выключить запасной контур раньше, чем замена доказала себя на полном объёме, — это как раз способ превратить провал проекта в операционный кризис.",
            ]),

            ("h2", "Пять проверок, которые ловят этот сценарий заранее"),
            ("p", "Ни одна из них не требует консультанта, нового инструмента или перепланирования. Все можно применить к текущей программе в этом месяце."),
            ("steps", [
                ("Выпишите все отклонения от стандарта и постоянного владельца каждого",
                 "Не список запросов на изменение, а список поведений, которые навсегда будут отличаться от продукта вендора. Если в этом списке больше нескольких пунктов, затрагивающих базовые модели данных, вы выбрали боковую ветку — независимо от того, произнёс это кто-нибудь вслух или нет."),
                ("Посчитайте стоимость второго обновления, а не первого",
                 "Спросите, во что обойдётся накатить два следующих мажорных релиза вендора поверх ваших отклонений. Если ответа нет ни у кого — эта цифра не ограничена, и она уже сидит в вашем бюджете."),
                ("Определите условия остановки до следующей вехи, письменно",
                 "«Если к дате X мы не сможем обработать объём трёх крупнейших рынков на тесте, эквивалентном продуктиву, мы останавливаемся и пересматриваем». Написано до наступления даты и тем, кто будет в комнате после неё. Критерии остановки, написанные после срыва срока, — это переговоры, а не критерии."),
                ("Тестируйте там, где больно, а не там, где удобно",
                 "Пилоты на маленьких рынках полезны для управления изменениями и бесполезны для доказательства пропускной способности. Ваш аналог «самого крупного и нагруженного рынка» — единственный пилот, отвечающий на вопрос о жизнеспособности."),
                ("Спрашивайте практиков напрямую раз в квартал, мимо отчётной вертикали",
                 "Один вопрос: «Что бы вы мне сказали, если бы за это ничего не было?» Задаёт человек с достаточными полномочиями, и ответ не проходит через слой, который оценивают. Это самая дешёвая система раннего предупреждения из существующих, и её почти никто не использует."),
            ]),
            ("note", "Полезное практическое правило: если программа не может назвать условие, при котором её остановят, — это не проект, а обязательство. Обязательства не отменяют, их списывают."),

            ("h2", "Переносимая версия — для компании, которая не Lidl"),
            ("p", "Большинство читателей не внедряют SAP в 30 странах. Механизм отлично масштабируется вниз:"),
            ("ul", [
                "Вы покупаете CRM и настраиваете её под существующие стадии продаж, не проверив, правильные ли это стадии. Через два года у каждой интеграции есть исключение специально для вас.",
                "Вы автоматизируете цепочку согласований ровно в том виде, в каком она есть, потому что менять её означало бы разговор с руководителем отдела. Теперь неудобный шаг стал быстрым, постоянным и невидимым — это сценарий, описанный в статье <a href=\"../when-not-to-automate/\">когда не нужно автоматизировать</a>.",
                "Вы заказываете переделку сайта, которая воспроизводит текущую структуру, потому что «пользователи привыкли», и следующие три года обходите навигацию, которую никто не защищает.",
            ]),
            ("p", "В каждой версии происходит одна и та же сделка: короткий неприятный разговор об изменении процесса заменяется на длинный тихий поток технического долга, который никогда не появляется отдельной строкой."),
            ("p", "Большие трансформации редко ломаются от одного плохого решения. Они ломаются от накопленного расстояния между тем, что происходит на самом деле, и тем, что люди считают безопасным произнести вслух. И это расстояние измеримо — если кто-то готов спросить."),
        ],
    },
    takeaways={
        "en": [
            "The failure was made of time, not of a single catastrophic event: seven years of locally rational decisions, each cheaper than stopping.",
            "A customisation to core logic (purchase-price vs retail-price valuation) is not a cost, it is a permanent tax on every future upgrade.",
            "Status reporting measured activity while viability quietly degraded; small-market pilots proved change management, not capacity.",
            "Write kill criteria before the milestone, not after the slip — otherwise they are negotiations.",
            "Keep the fallback system alive until the replacement has proven itself at full production volume.",
            "Ask practitioners one consequence-free question per quarter, off the normal reporting line. It is the cheapest early-warning system there is.",
        ],
        "ru": [
            "Провал состоял из времени, а не из одной катастрофы: семь лет локально рациональных решений, каждое из которых было дешевле остановки.",
            "Доработка базовой логики (оценка по закупочной цене вместо розничной) — не расход, а постоянный налог на каждое будущее обновление.",
            "Отчётность мерила активность, пока жизнеспособность тихо ухудшалась; пилоты на малых рынках доказали управляемость изменениями, но не пропускную способность.",
            "Пишите условия остановки до вехи, а не после срыва срока — иначе это переговоры.",
            "Держите запасную систему живой, пока замена не докажет себя на полном продуктивном объёме.",
            "Раз в квартал задавайте практикам один вопрос без последствий, мимо обычной отчётной вертикали. Это самая дешёвая система раннего предупреждения.",
        ],
    },
    faq={
        "en": [
            ("Why did Lidl's SAP implementation fail?",
             "The most widely reported root cause is that Lidl valued inventory at purchase price while SAP's retail standard is built around retail-price valuation. Rather than change the process, Lidl customised the software. That deviation touched procurement, pricing, replenishment and reporting, made every future upgrade more expensive, and combined with reporting that tracked activity rather than viability, allowed the programme to drift for seven years."),
            ("How much did the Lidl eLWIS project cost?",
             "Approximately €500 million (some sources quote a figure closer to $580–600 million) over roughly seven years, from the 2011 start to the 2018 cancellation, after which Lidl returned to its legacy in-house merchandise management system."),
            ("Was this SAP's fault?",
             "No. The system behaved as designed; the conflict was between a standard product's assumptions and a business process the company chose not to change. The same outcome is reachable with any major platform. The decision to customise rather than adapt is where the risk was created."),
            ("What is the single best early-warning check for a programme like this?",
             "Written kill criteria agreed before the next milestone: a specific, measurable condition under which the programme stops. If a programme cannot name such a condition, it is a commitment rather than a project, and commitments get written off rather than cancelled."),
            ("Does this only apply to large enterprises?",
             "No. The same mechanism appears at any scale: configuring a CRM around unexamined sales stages, automating an approval chain exactly as it exists, or rebuilding a website on a structure nobody defends. In each case a short uncomfortable process conversation is exchanged for a long quiet stream of technical debt."),
            ("When is customising standard software actually justified?",
             "When the deviation is genuinely the source of competitive advantage, is isolated from core data models, has a named permanent owner, and the cost of applying the vendor's next two major releases on top of it has been estimated and accepted. If any of those four is missing, the customisation is being bought on credit."),
        ],
        "ru": [
            ("Почему провалилось внедрение SAP в Lidl?",
             "Наиболее широко описанная первопричина: Lidl оценивал запасы по закупочной цене, тогда как розничный стандарт SAP построен вокруг оценки по розничной. Вместо изменения процесса компания доработала систему. Это отклонение затронуло закупки, ценообразование, пополнение и отчётность, сделало дороже каждое будущее обновление и вместе с отчётностью, мерившей активность вместо жизнеспособности, позволило программе дрейфовать семь лет."),
            ("Сколько стоил проект eLWIS?",
             "Около €500 млн (часть источников называет цифры ближе к $580–600 млн) примерно за семь лет — со старта в 2011 году до отмены в 2018-м, после которой Lidl вернулся на собственную унаследованную систему товародвижения."),
            ("Это вина SAP?",
             "Нет. Система работала так, как спроектирована; конфликт был между предпосылками стандартного продукта и процессом, который компания решила не менять. Тот же результат достижим на любой крупной платформе. Риск возник в момент решения дорабатывать, а не адаптироваться."),
            ("Какая проверка лучше всего предупреждает о таком сценарии?",
             "Письменные условия остановки, согласованные до следующей вехи: конкретное измеримое условие, при котором программу прекращают. Если программа не может назвать такое условие, это не проект, а обязательство, — а обязательства не отменяют, их списывают."),
            ("Это относится только к крупным компаниям?",
             "Нет. Механизм работает на любом масштабе: настройка CRM под непроверенные стадии продаж, автоматизация цепочки согласований ровно в текущем виде, переделка сайта на структуре, которую никто не защищает. В каждом случае короткий неприятный разговор о процессе меняется на длинный тихий поток технического долга."),
            ("Когда доработка стандартной системы всё-таки оправдана?",
             "Когда отклонение действительно является источником конкурентного преимущества, изолировано от базовых моделей данных, имеет названного постоянного владельца, а стоимость накатывания двух следующих мажорных релизов вендора поверх него посчитана и принята. Если отсутствует хотя бы один из четырёх пунктов — доработка покупается в кредит."),
        ],
    },
)
