# -*- coding: utf-8 -*-
POST = dict(
    slug="multilingual-website-not-converting",
    date="2026-08-13",
    updated="2026-08-27",
    tag={"en": "Web Development", "ru": "Веб-разработка"},
    title={
        "en": "Why Your Multilingual Website Isn't Converting (It's Not About Translation)",
        "ru": "Почему многоязычный сайт не конвертирует (дело не в переводе)",
    },
    h1={
        "en": "Why Your Multilingual Website Isn't Converting (It's Not About Translation)",
        "ru": "Почему многоязычный сайт не конвертирует (дело не в переводе)",
    },
    dek={
        "en": "Translation is the easy 20% of localisation. The 80% that decides whether a site converts has almost nothing to do with words.",
        "ru": "Перевод — простые 20% локализации. Оставшиеся 80%, которые решают, конвертирует ли сайт, к словам почти не относятся.",
    },
    description={
        "en": "Layout that breaks on longer strings, trust signals that don't transfer, payment expectations, hreflang mistakes that hide half your site from search — the technical and cultural reasons a translated site still doesn't sell.",
        "ru": "Ломающаяся вёрстка на длинных строках, непереносимые сигналы доверия, ожидания по оплате, ошибки hreflang, скрывающие половину сайта от поиска, — технические и культурные причины, по которым переведённый сайт всё равно не продаёт.",
    },
    keywords={
        "en": "multilingual website, website localization, hreflang implementation, international SEO, multi-market conversion, RTL layout, localization mistakes, translated website not converting",
        "ru": "многоязычный сайт, локализация сайта, hreflang настройка, международное SEO, конверсия на разных рынках, RTL вёрстка, ошибки локализации, переведённый сайт не продаёт",
    },
    hashtags=["WebDevelopment", "Localization", "InternationalBusiness", "UXDesign", "GlobalMarketing"],
    related=["when-not-to-automate", "how-to-choose-a-consultant", "audit-nobody-reads"],
    body={
        "en": [
            ("p", "Most companies localise a website by translating it. That is the easy 20% of the problem, and it's the part everyone gets right."),
            ("p", "The other 80% — the part that decides whether a visitor from that market actually buys — is layout, trust signals, transactional expectations and search visibility. <strong>A site can read perfectly in a language and still feel imported</strong>, and visitors rarely articulate why. They just leave faster."),
            ("p", "Here is what actually breaks, in the order it typically costs you money."),

            ("h2", "1. The layout was designed around one language's string lengths"),
            ("p", "Text length changes substantially between languages. German and Russian expand relative to English; Chinese and Japanese contract; Finnish produces long unbreakable compounds. Designs built to fit English exactly will fail somewhere."),
            ("p", "Where it shows first:"),
            ("ul", [
                "<strong>Navigation.</strong> A five-item menu that fits English wraps to two lines in German and pushes the CTA below the fold on a laptop.",
                "<strong>Buttons.</strong> Fixed-width buttons truncate or the label wraps mid-word. The primary CTA is the single worst place for this and the most common one.",
                "<strong>Form labels and validation messages.</strong> Usually written last, translated last, and tested never — and they sit directly in the conversion path.",
                "<strong>Tables and pricing grids.</strong> Column widths tuned to short English headers become unreadable with longer ones.",
            ]),
            ("p", "The fix is structural, not linguistic: fluid widths, no fixed-height containers around text, and a test pass with the longest translation you actually have. A pragmatic rule is to design so that any string can grow by about 35% without breaking the layout."),

            ("h2", "2. Reading direction and scanning patterns"),
            ("p", "Right-to-left languages (Arabic, Hebrew, Farsi, Urdu) are not a mirror-image switch. Direction reverses for text flow, layout order and navigation, but numbers, Latin brand names, code, phone numbers and many charts stay left-to-right. Icons with directional meaning — back arrows, progress indicators, sliders — need to flip; logos and clock icons don't."),
            ("p", "Beyond RTL, scanning behaviour differs even between left-to-right markets: how far a reader trusts a page before scrolling, how much density reads as \"serious\" versus \"cluttered\", and whether a wall of text signals credibility or carelessness. A layout that feels confident and airy in one market can read as thin and unserious in another."),
            ("q", "The test isn't \"does it read correctly in this language.\" It's \"would someone who only reads this language assume it was built by someone who only reads this language.\""),

            ("h2", "3. Trust signals don't transfer"),
            ("p", "This is the largest and least technical cause of lost conversion. Every market has its own evidence of legitimacy, and a translated page usually carries over the source market's set — which reads as nothing at all."),
            ("table", {
                "caption": "What tends to build trust in different markets",
                "head": ["Signal", "Why it varies", "Practical implication"],
                "rows": [
                    ["Company registration and legal details", "In some markets a visible legal entity, address and registration number is a baseline expectation; in others it reads as clutter", "Check what local competitors put in the footer, and match the level of disclosure"],
                    ["Contact channel", "Phone, email, WhatsApp, Telegram, LINE, WeChat — the expected default differs sharply", "Offer the local default first, not your home market's default"],
                    ["Reviews and social proof", "Which platform counts as credible is market-specific", "A logo wall from unknown-to-them companies proves nothing; local names or recognisable sectors do"],
                    ["Pricing transparency", "Some markets expect a visible price, others expect \"request a quote\"", "Getting this backwards either kills trust or kills leads"],
                    ["Certifications", "Local certifications and memberships often outrank international ones", "Show the ones that mean something locally, drop the ones that don't"],
                ],
            }),
            ("p", "None of this appears in a translation brief, and all of it is inside the conversion path."),

            ("h2", "4. Transactional expectations"),
            ("p", "The checkout or contact step is where imported assumptions become abandonment:"),
            ("ul", [
                "<strong>Payment methods.</strong> Card-only checkout is normal in some markets and a hard stop in others where bank transfer, local wallets or invoice-on-delivery dominate.",
                "<strong>Address forms.</strong> A form that requires a state and a five-digit ZIP breaks for most of the world. So does forcing a first name / last name split.",
                "<strong>Currency and tax display.</strong> Whether prices are shown with or without VAT is a market convention; getting it wrong makes you look either expensive or evasive.",
                "<strong>Formats.</strong> Dates (12/06 means two different days), decimal separators, phone formats, name order. Each one is a small credibility leak in the exact moment you're asking for money.",
                "<strong>Working hours and response promises.</strong> \"We reply within 24 hours\" means something different across a time-zone gap, and unmet timing promises cost more than vague ones.",
            ]),

            ("h2", "5. Search engines can only see one version of your site"),
            ("p", "This is the failure that hides all the others: you fixed the site, and half of it isn't being indexed. The most common technical mistakes:"),
            ("ol", [
                "<strong>Client-side language switching only.</strong> If both languages live in one URL and JavaScript toggles them, search engines index one version. The other language effectively doesn't exist as a landing page.",
                "<strong>Missing or non-reciprocal hreflang.</strong> Every language version must point to every other one <em>and</em> to itself, with matching URLs on both sides. One-way declarations are ignored.",
                "<strong>Wrong or invented language codes.</strong> Use ISO 639-1 language codes plus optional ISO 3166-1 Alpha-2 region codes. <code>en-GB</code> is valid; <code>en-UK</code> is not.",
                "<strong>No x-default.</strong> Declare which version serves users whose language you don't target.",
                "<strong>Canonical fighting hreflang.</strong> Each language version should be canonical to itself. Pointing every localised page's canonical at the English one removes them from the index — a surprisingly common configuration.",
                "<strong>Automatic IP-based redirects.</strong> Forcing a visitor (or a crawler) into a language version by geography prevents indexing of the others and irritates people who deliberately chose a language.",
            ]),
            ("note", "Practical structure that avoids most of this: one physical URL per language (<code>/</code> and <code>/ru/</code>, or subdomains, or ccTLDs), reciprocal hreflang tags including x-default, self-referencing canonicals, and a language switch that navigates to a real URL rather than silently swapping text. Let users choose; never redirect them by IP."),

            ("h2", "6. The content strategy is a translation, not a market"),
            ("p", "The deepest version of the problem: the page answers the questions your home market asks. Objections differ by market — price sensitivity, contract length, data residency, whether working with a foreign supplier is normal or exotic. A word-perfect translation of the wrong objection handling converts worse than clumsy copy addressing the right one."),
            ("p", "The same applies to search intent. Direct translation of keywords frequently misses how the market actually searches: different phrasing, different level of technicality, sometimes an English loanword that ranks better than the native term. Keyword research has to be redone per language, not translated."),

            ("h2", "A localisation checklist that catches most of it"),
            ("checklist", [
                "Every string can grow 35% without breaking the layout; longest-language pass completed on nav, buttons, forms and tables.",
                "Directional icons flip for RTL; numbers, brand names and code stay LTR.",
                "Footer discloses at the level local competitors do.",
                "The primary contact channel is the market's default, not yours.",
                "Payment methods and address form match local reality; date and number formats localised.",
                "One indexable URL per language, reciprocal hreflang including x-default, self-referencing canonical.",
                "No IP-based forced redirects; language switch changes the URL.",
                "Keyword research redone natively, not translated.",
                "Error and validation messages translated and visually tested.",
                "A native speaker who is also a buyer in that market has reviewed the conversion path — not just the text.",
            ]),

            ("h2", "How to sequence the work"),
            ("steps", [
                ("Fix indexing first",
                 "Nothing else matters if the market can't find the page. URLs, hreflang, canonicals and the switch behaviour are a few days of work with the largest single effect."),
                ("Then fix the conversion path",
                 "Contact method, form, payment, formats. Narrow, measurable, and where the money is lost fastest."),
                ("Then fix trust signals",
                 "Footer disclosure, proof, certifications. Cheap to change, and it compounds with the previous step."),
                ("Then re-do content per market",
                 "Objection handling and keyword targeting. Most expensive, slowest to pay back, and pointless before the first three are done."),
            ]),
            ("p", "Most localisation budgets run this list backwards: they start with content and never reach hreflang. If you only have budget for one step, do the first — a correctly indexed mediocre translation outperforms a beautiful one nobody can find."),
        ],
        "ru": [
            ("p", "Большинство компаний локализует сайт переводом. Это простые 20% задачи, и с ними справляются все."),
            ("p", "Остальные 80% — то, что определяет, купит ли посетитель с этого рынка, — это вёрстка, сигналы доверия, ожидания по сделке и видимость в поиске. <strong>Сайт может безупречно читаться на языке и всё равно ощущаться импортированным</strong>, и посетители редко могут объяснить почему. Они просто уходят быстрее."),
            ("p", "Вот что ломается на самом деле, в порядке того, как быстро это стоит денег."),

            ("h2", "1. Вёрстка спроектирована под длину строк одного языка"),
            ("p", "Длина текста заметно меняется между языками. Немецкий и русский длиннее английского, китайский и японский короче, финский порождает длинные неразрывные составные слова. Макет, подогнанный ровно под английский, где-нибудь сломается."),
            ("p", "Где это проявляется первым:"),
            ("ul", [
                "<strong>Навигация.</strong> Меню из пяти пунктов, помещающееся по-английски, переносится на две строки по-немецки и выталкивает кнопку действия за пределы первого экрана ноутбука.",
                "<strong>Кнопки.</strong> Фиксированная ширина обрезает текст или переносит его посреди слова. Главная кнопка — худшее место для этого и самое частое.",
                "<strong>Подписи полей и сообщения валидации.</strong> Обычно пишутся последними, переводятся последними и не тестируются никогда — а стоят прямо на пути к конверсии.",
                "<strong>Таблицы и тарифные сетки.</strong> Ширины колонок, подогнанные под короткие английские заголовки, становятся нечитаемыми с длинными.",
            ]),
            ("p", "Решение структурное, а не языковое: резиновые ширины, отсутствие контейнеров фиксированной высоты вокруг текста и прогон с самым длинным реально имеющимся переводом. Практическое правило — проектировать так, чтобы любая строка могла вырасти примерно на 35% без поломки макета."),

            ("h2", "2. Направление чтения и способ просмотра"),
            ("p", "Языки справа налево (арабский, иврит, фарси, урду) — это не зеркальное отражение. Направление меняется для текста, порядка блоков и навигации, но числа, латинские названия брендов, код, телефоны и многие графики остаются слева направо. Иконки с направленным смыслом — стрелки «назад», индикаторы прогресса, ползунки — переворачиваются; логотипы и часы — нет."),
            ("p", "Кроме RTL, различается и сам способ просмотра даже между рынками с письмом слева направо: насколько далеко читатель доверяет странице до прокрутки, какая плотность воспринимается как «серьёзно», а какая как «свалка», и читается ли стена текста как основательность или как небрежность. Макет, выглядящий уверенно и воздушно на одном рынке, на другом может показаться пустым и несерьёзным."),
            ("q", "Проверка звучит не как «правильно ли это читается на языке». Она звучит так: «решит ли человек, читающий только на этом языке, что сайт сделан тем, кто тоже читает только на нём»."),

            ("h2", "3. Сигналы доверия не переносятся"),
            ("p", "Это самая крупная и наименее техническая причина потери конверсии. У каждого рынка свои доказательства легитимности, и переведённая страница обычно тащит набор исходного рынка — который читается как ничто."),
            ("table", {
                "caption": "Что формирует доверие на разных рынках",
                "head": ["Сигнал", "Почему различается", "Что делать"],
                "rows": [
                    ["Реквизиты и юридические данные", "На одних рынках видимое юрлицо, адрес и регистрационный номер — базовое ожидание, на других это выглядит как мусор", "Посмотрите, что кладут в подвал местные конкуренты, и дайте тот же уровень раскрытия"],
                    ["Канал связи", "Телефон, почта, WhatsApp, Telegram, LINE, WeChat — ожидаемый по умолчанию канал сильно различается", "Предлагайте местный вариант по умолчанию, а не привычный вам"],
                    ["Отзывы и социальные доказательства", "Какая площадка считается достоверной — вопрос рынка", "Стена логотипов неизвестных здесь компаний не доказывает ничего; местные имена или узнаваемые отрасли — да"],
                    ["Прозрачность цен", "Одни рынки ждут видимую цену, другие — «запросить расчёт»", "Ошибка в любую сторону убивает либо доверие, либо заявки"],
                    ["Сертификации", "Местные сертификаты и членства часто весомее международных", "Показывайте то, что здесь что-то значит, и убирайте остальное"],
                ],
            }),
            ("p", "Ничего из этого не попадает в задание на перевод, и всё это стоит прямо на пути к конверсии."),

            ("h2", "4. Ожидания по сделке"),
            ("p", "Шаг оплаты или контакта — место, где импортированные предпосылки превращаются в отказ:"),
            ("ul", [
                "<strong>Способы оплаты.</strong> Оплата только картой нормальна на одних рынках и жёсткий стоп на других, где доминируют переводы, местные кошельки или счёт по факту.",
                "<strong>Формы адреса.</strong> Форма, требующая штат и пятизначный индекс, ломается для большей части мира. Как и принудительное разделение на имя и фамилию.",
                "<strong>Отображение валюты и налога.</strong> Показывать цены с НДС или без — рыночная конвенция; ошибка делает вас либо дорогим, либо уклончивым.",
                "<strong>Форматы.</strong> Даты (12/06 — это два разных дня), разделители дробей, форматы телефонов, порядок имени. Каждая мелочь — небольшая утечка доверия ровно в момент просьбы о деньгах.",
                "<strong>Часы работы и обещания по ответу.</strong> «Ответим в течение 24 часов» означает разное при разнице часовых поясов, а нарушенное обещание по срокам стоит дороже расплывчатого.",
            ]),

            ("h2", "5. Поисковик видит только одну версию вашего сайта"),
            ("p", "Этот сбой прячет все остальные: вы починили сайт, а половина его не индексируется. Самые частые технические ошибки:"),
            ("ol", [
                "<strong>Переключение языка только на клиенте.</strong> Если оба языка лежат по одному URL и переключаются JavaScript'ом, поисковик проиндексирует одну версию. Вторая фактически не существует как посадочная страница.",
                "<strong>Отсутствующий или невзаимный hreflang.</strong> Каждая языковая версия должна ссылаться на все остальные <em>и на себя</em>, причём URL должны совпадать с обеих сторон. Односторонние объявления игнорируются.",
                "<strong>Неверные или выдуманные коды языка.</strong> Используйте коды языка ISO 639-1 и при необходимости коды региона ISO 3166-1 Alpha-2. <code>en-GB</code> корректен, <code>en-UK</code> — нет.",
                "<strong>Отсутствие x-default.</strong> Объявите версию для пользователей, чей язык вы не таргетируете.",
                "<strong>Canonical, воюющий с hreflang.</strong> Каждая языковая версия должна быть канонической сама себе. Указание canonical всех локализованных страниц на английскую выкидывает их из индекса — на удивление частая конфигурация.",
                "<strong>Автоматические редиректы по IP.</strong> Принудительное перенаправление посетителя (или робота) в языковую версию по географии мешает индексации остальных и раздражает тех, кто язык выбрал осознанно.",
            ]),
            ("note", "Структура, снимающая большую часть проблем: один физический URL на язык (<code>/</code> и <code>/ru/</code>, либо поддомены, либо национальные домены), взаимные теги hreflang вместе с x-default, canonical на самого себя и переключатель языка, ведущий на реальный URL, а не подменяющий текст молча. Дайте пользователю выбрать; никогда не перенаправляйте по IP."),

            ("h2", "6. Контент — перевод, а не рынок"),
            ("p", "Самая глубокая версия проблемы: страница отвечает на вопросы вашего домашнего рынка. Возражения различаются — чувствительность к цене, длина контракта, где хранятся данные, нормально ли здесь вообще работать с иностранным подрядчиком. Безупречный перевод обработки не того возражения конвертирует хуже, чем корявый текст, отвечающий на нужное."),
            ("p", "То же с поисковым намерением. Прямой перевод ключевых слов часто промахивается мимо того, как рынок реально ищет: другая формулировка, другой уровень технической подробности, иногда английское заимствование ранжируется лучше родного термина. Сбор семантики нужно делать заново на каждом языке, а не переводить."),

            ("h2", "Чек-лист локализации, покрывающий бо́льшую часть"),
            ("checklist", [
                "Любая строка может вырасти на 35% без поломки макета; прогон на самом длинном языке сделан для навигации, кнопок, форм и таблиц.",
                "Направленные иконки переворачиваются для RTL; числа, названия брендов и код остаются слева направо.",
                "Подвал раскрывает данные на том же уровне, что у местных конкурентов.",
                "Основной канал связи — принятый на рынке по умолчанию, а не ваш.",
                "Способы оплаты и форма адреса соответствуют местной реальности; форматы дат и чисел локализованы.",
                "Один индексируемый URL на язык, взаимные hreflang с x-default, canonical на самого себя.",
                "Нет принудительных редиректов по IP; переключатель языка меняет URL.",
                "Семантика собрана заново на языке, а не переведена.",
                "Сообщения об ошибках и валидации переведены и проверены визуально.",
                "Носитель языка, который к тому же является покупателем на этом рынке, прошёл весь путь до заявки — не только вычитал текст.",
            ]),

            ("h2", "В каком порядке это делать"),
            ("steps", [
                ("Сначала индексация",
                 "Всё остальное не имеет значения, если рынок не может найти страницу. URL, hreflang, canonical и поведение переключателя — несколько дней работы с наибольшим одиночным эффектом."),
                ("Затем путь к конверсии",
                 "Канал связи, форма, оплата, форматы. Узко, измеримо и там, где деньги теряются быстрее всего."),
                ("Затем сигналы доверия",
                 "Раскрытие в подвале, доказательства, сертификации. Дёшево менять, и эффект складывается с предыдущим шагом."),
                ("Затем контент под рынок",
                 "Работа с возражениями и семантика. Самое дорогое, медленнее всего окупается и бессмысленно до первых трёх шагов."),
            ]),
            ("p", "Большинство бюджетов на локализацию проходят этот список задом наперёд: начинают с контента и не доходят до hreflang. Если бюджета хватает на один шаг — делайте первый: корректно проиндексированный посредственный перевод работает лучше прекрасного, которого никто не находит."),
        ],
    },
    takeaways={
        "en": [
            "Translation is roughly 20% of localisation; layout tolerance, trust signals, transactional expectations and indexing are the rest.",
            "Design so any string can grow ~35% without breaking, and test with your longest language — buttons and form messages fail first.",
            "Trust signals are market-specific: match local competitors' level of disclosure and lead with the market's default contact channel.",
            "The most expensive technical mistake is client-side-only language switching, followed by non-reciprocal hreflang and canonicals pointing at the source language.",
            "Never redirect by IP; let the user choose and make the switch change the URL.",
            "Sequence the work indexing → conversion path → trust signals → content. Most budgets run it backwards.",
        ],
        "ru": [
            "Перевод — примерно 20% локализации; остальное — устойчивость вёрстки, сигналы доверия, ожидания по сделке и индексация.",
            "Проектируйте так, чтобы строка могла вырасти примерно на 35% без поломки, и тестируйте на самом длинном языке — первыми ломаются кнопки и сообщения форм.",
            "Сигналы доверия зависят от рынка: дайте тот же уровень раскрытия, что у местных конкурентов, и ставьте первым принятый здесь канал связи.",
            "Самая дорогая техническая ошибка — переключение языка только на клиенте, затем невзаимный hreflang и canonical, указывающий на исходный язык.",
            "Никогда не перенаправляйте по IP; дайте выбрать пользователю и сделайте так, чтобы переключатель менял URL.",
            "Порядок работ: индексация → путь к конверсии → сигналы доверия → контент. Большинство бюджетов проходит его наоборот.",
        ],
    },
    faq={
        "en": [
            ("Why isn't my translated website converting?",
             "Usually because translation was the only thing that changed. The layout still assumes one language's string lengths, the trust signals are the source market's, the contact and payment options are the ones you use at home, and often half the site isn't indexed because the language switch happens only in the browser."),
            ("What is the correct hreflang setup for a multilingual site?",
             "One indexable URL per language, reciprocal hreflang annotations where every version references every other version and itself, valid ISO 639-1 language codes with optional ISO 3166-1 Alpha-2 region codes, an x-default entry, and a self-referencing canonical on each language version."),
            ("Should I redirect visitors to their language automatically by IP?",
             "No. It prevents search engines from indexing the versions they are not served, and it overrides deliberate user choices. Detect and offer — a dismissible suggestion to switch — but let the user decide, and make the switch change the URL."),
            ("How much extra space should a design leave for translation?",
             "As a working rule, any string should be able to grow by about 35% without breaking the layout. Test with the longest language you actually publish, focusing on navigation, primary buttons, form labels, validation messages and table headers."),
            ("Do I need to redo keyword research for each language?",
             "Yes. Direct translation of keywords regularly misses how a market searches — different phrasing, a different level of technical vocabulary, and sometimes an English loanword that outperforms the native term. Research natively per language rather than translating a keyword list."),
            ("What should I fix first if the budget only covers one thing?",
             "Indexing: URLs, hreflang, canonicals and the language-switch behaviour. A correctly indexed mediocre translation outperforms an excellent one that search engines cannot see."),
        ],
        "ru": [
            ("Почему переведённый сайт не конвертирует?",
             "Обычно потому, что перевод был единственным изменением. Вёрстка по-прежнему рассчитана на длину строк одного языка, сигналы доверия остались от исходного рынка, каналы связи и способы оплаты — ваши домашние, а часто ещё и половина сайта не проиндексирована, потому что язык переключается только в браузере."),
            ("Как правильно настроить hreflang для многоязычного сайта?",
             "Один индексируемый URL на язык, взаимные аннотации hreflang, где каждая версия ссылается на все остальные и на себя, корректные коды языка ISO 639-1 с необязательными кодами региона ISO 3166-1 Alpha-2, запись x-default и canonical на самого себя у каждой языковой версии."),
            ("Нужно ли автоматически перенаправлять по IP на нужный язык?",
             "Нет. Это мешает поисковикам индексировать версии, которые им не отдают, и переопределяет осознанный выбор пользователя. Определяйте и предлагайте — закрываемой подсказкой о переключении, — но решение оставьте пользователю, а переключатель должен менять URL."),
            ("Сколько запаса по месту оставлять в макете под перевод?",
             "Рабочее правило: любая строка должна иметь возможность вырасти примерно на 35% без поломки макета. Тестируйте на самом длинном из публикуемых языков, особенно навигацию, главные кнопки, подписи полей, сообщения валидации и заголовки таблиц."),
            ("Нужно ли собирать семантику заново для каждого языка?",
             "Да. Прямой перевод ключевых слов регулярно промахивается мимо того, как ищет рынок: другая формулировка, другой уровень терминологии, иногда английское заимствование работает лучше родного слова. Собирайте семантику на языке, а не переводите список."),
            ("Что чинить первым, если бюджета хватает на одно?",
             "Индексацию: URL, hreflang, canonical и поведение переключателя языка. Корректно проиндексированный посредственный перевод работает лучше отличного, которого поисковик не видит."),
        ],
    },
)
