# -*- coding: utf-8 -*-
POST = dict(
    slug="one-person-consulting-studio",
    date="2026-07-21",
    updated="2026-08-27",
    tag={"en": "Consulting", "ru": "Консалтинг"},
    title={
        "en": "The One-Person Consulting Studio: When Small Beats Big (and When It Doesn't)",
        "ru": "Студия из одного человека: когда маленький подрядчик лучше большого — и когда нет",
    },
    h1={
        "en": "The One-Person Consulting Studio: When Small Beats Big (and When It Doesn't)",
        "ru": "Студия из одного человека: когда маленький подрядчик лучше большого — и когда нет",
    },
    dek={
        "en": "\"What if you get sick?\" is the standard objection to hiring a solo consultant. It's a fair question — and it's usually pointed at the wrong risk.",
        "ru": "«А если вы заболеете?» — стандартное возражение против консультанта-одиночки. Вопрос честный — и обычно направлен не на тот риск.",
    },
    description={
        "en": "How agency economics create the gap between who sells the work and who does it, where a one-person studio is genuinely better, where it is genuinely worse, and what continuity guarantees to demand from either.",
        "ru": "Как экономика агентства порождает разрыв между тем, кто продаёт работу, и тем, кто её делает; где студия из одного человека действительно лучше, где хуже и какие гарантии непрерывности требовать от обоих.",
    },
    keywords={
        "en": "boutique consulting, solo consultant vs agency, independent consultant risk, consulting firm selection, small consulting studio, accountability in consulting, choosing a consulting partner, bus factor consulting",
        "ru": "бутиковый консалтинг, консультант-одиночка или агентство, риски независимого консультанта, выбор консалтинговой компании, маленькая консалтинговая студия, ответственность в консалтинге, непрерывность работ, фактор автобуса",
    },
    hashtags=["Consulting", "BoutiqueConsulting", "SmallBusiness", "ClientExperience", "Freelance"],
    related=["consulting-retainer-trap", "how-to-choose-a-consultant", "how-much-does-business-consulting-cost"],
    body={
        "en": [
            ("p", "\"What if you get sick?\" is the most common objection to hiring a one-person consulting studio instead of an agency. It is a fair question. It is also usually aimed at the wrong risk."),
            ("p", "The honest answer: <strong>size is not the risk. Diluted accountability is.</strong> A small studio has a real continuity problem and no way to hide it. A large firm has a real dilution problem and an excellent way to hide it. Which one is worse depends entirely on the type of work — and this article sets out where each actually wins."),

            ("h2", "What the question is really asking"),
            ("p", "Underneath \"what if you get sick\" are three separate concerns that deserve separate answers:"),
            ("ol", [
                "<strong>Delivery risk.</strong> Will the work stop if one person is unavailable? Legitimate, and answerable with concrete guarantees rather than reassurance.",
                "<strong>Capability risk.</strong> Can one person cover everything this project needs? Also legitimate, and often the real reason to choose a firm.",
                "<strong>Procurement risk.</strong> If this goes wrong, what does the person who approved it say? This is rarely stated out loud and frequently decisive.",
            ]),
            ("p", "The third one explains a great deal of supplier selection. Nobody was ever fired for hiring a large firm, and everyone knows it. That is a real cost borne by the buyer's organisation, not a quality signal about the supplier."),

            ("h2", "How agency economics actually work"),
            ("p", "This isn't a criticism, it's arithmetic. A consulting firm with employees needs utilisation, and utilisation shapes staffing:"),
            ("ul", [
                "<strong>The person who sells is rarely the person who delivers.</strong> Senior partners are the sales function; their time is the firm's scarcest and most expensive resource. Your project is staffed by whoever is available at a margin that works.",
                "<strong>Leverage is the business model.</strong> Profit comes from senior oversight over junior execution. That ratio is the firm's economics, not a per-project choice, which is why \"more senior involvement\" is difficult to buy even when you offer to pay for it.",
                "<strong>Reassignment is invisible.</strong> If the strong person on your account gets moved to a bigger client, you generally aren't told; you receive a transition and a reassurance.",
                "<strong>Methodology is an asset that must be reused.</strong> A firm's frameworks exist so work is repeatable across clients. That is genuinely valuable for common problems and genuinely limiting for unusual ones — a template will get applied to your problem because that's what makes the economics work.",
            ]),
            ("q", "At a large firm, the gap between who convinced you and who does the work is a feature of the business model. At a one-person studio there's no gap, because there's nowhere for one to hide."),

            ("h2", "Where a one-person studio is genuinely better"),
            ("ul", [
                "<strong>Non-standard problems.</strong> No template exists, so nothing gets templated onto you. This is the whole category of work where a framework produces a wrong answer confidently.",
                "<strong>Short, decision-shaped engagements.</strong> Two to six weeks, one question, a written answer. Firms are structurally bad at these: the overhead of scoping, staffing and QA exceeds the work.",
                "<strong>Direct transmission.</strong> Your context reaches the person analysing it without passing through an account manager and a kickoff deck. Fewer translation layers, fewer wrong assumptions surviving unnoticed.",
                "<strong>Aligned incentives on scope.</strong> A solo consultant with a full pipeline has no reason to extend a project; there is no bench to keep busy. That single fact removes the most common source of scope inflation.",
                "<strong>Willingness to say no.</strong> Turning down work costs a firm a utilisation slot and costs an individual nothing but the fee. It is much easier to hear \"you don't need this project\" from someone with no bench.",
            ]),

            ("h2", "Where a one-person studio is genuinely worse"),
            ("p", "Any article that skips this section is marketing. Pick a firm when:"),
            ("ul", [
                "<strong>The work needs parallel capacity.</strong> Forty interviews across six countries in three weeks is a staffing problem, and one person cannot solve it by being clever.",
                "<strong>It needs several deep specialisms at once.</strong> Tax, employment law and systems architecture in one engagement is a team, not a generalist.",
                "<strong>Continuity over years is the point.</strong> A multi-year programme needs institutional memory that survives an individual's life events.",
                "<strong>Procurement or regulation requires it.</strong> Insurance minimums, supplier audits, ISO certification, panel agreements. These are real constraints, not snobbery, and arguing with them wastes everyone's time.",
                "<strong>You need the name.</strong> Sometimes the deliverable's job is to be credible to a board or a regulator. That's a legitimate requirement — just be honest that you're buying signalling, and price it as such.",
            ]),
            ("table", {
                "caption": "Which shape of supplier fits which engagement",
                "head": ["Engagement", "Better fit", "Why"],
                "rows": [
                    ["One hard decision, 2–6 weeks", "One-person studio", "Overhead of a firm exceeds the work; direct access is the whole value."],
                    ["Non-standard problem with no precedent", "One-person studio", "No template to apply means no template gets applied."],
                    ["Multi-country operational review", "Firm", "Parallel capacity and local presence cannot be substituted."],
                    ["Multi-year transformation programme", "Firm", "Institutional continuity beyond one person's availability."],
                    ["Regulated or audited procurement", "Firm", "Insurance, certification and panel requirements are hard constraints."],
                    ["Board-facing credibility exercise", "Firm", "You are buying the name; that's a valid purchase, priced accordingly."],
                    ["Implementation of one specific solution", "One-person studio", "Fewer handoffs, and the person who designed it builds it."],
                ],
            }),

            ("h2", "Answering the continuity question properly"),
            ("p", "\"I'll be fine\" is not an answer. A solo consultant who takes the objection seriously should be able to offer four things, and a buyer should ask for them explicitly:"),
            ("steps", [
                ("Work stored where you can reach it",
                 "Deliverables and working material in your systems or a shared repository from day one, not delivered at the end. If the studio disappears mid-project, you keep everything produced so far."),
                ("Interim deliverables on a fixed cadence",
                 "Something reviewable every week or two, not a single delivery at the end. This caps your exposure to the length of one cadence instead of the length of the project."),
                ("A named fallback",
                 "A specific person or firm who could take over, named in advance, ideally who has seen the material. Not a promise to find someone."),
                ("Explicit unavailability terms",
                 "What happens to the timeline and the fee if the consultant is unavailable for two weeks. In writing, agreed before starting."),
            ]),
            ("note", "Ask a large firm the equivalent question: \"If the person you're putting on this leaves the firm, what changes for me, and who tells me?\" The answer is often less concrete than a good solo consultant's — and far less binding."),

            ("h2", "Five questions that work on either kind of supplier"),
            ("ol", [
                "<strong>Who exactly does the work, and are they on this call?</strong> Ask for names and the percentage of their time. Write the answer down; it becomes a reference point later.",
                "<strong>How many clients will you have in parallel with mine?</strong> Both answers can be fine. Evasion is the signal, not the number.",
                "<strong>What would make you tell me not to do this project?</strong> Anyone who cannot produce a scenario is selling activity.",
                "<strong>What do I own at the end, and in what format?</strong> A PDF is not ownership. Models, data, scripts and reasoning are.",
                "<strong>What happens if the person doing this becomes unavailable?</strong> The concrete answer beats the reassuring one, regardless of supplier size.",
            ]),
            ("p", "The full version of this checklist, including the questions that expose padded scopes, is in <a href=\"../how-to-choose-a-consultant/\">how to choose a business consultant</a>."),

            ("h2", "The actual trade"),
            ("p", "A large firm sells you redundancy and buys back your access to the person who understands your problem. A one-person studio sells you undiluted access and asks you to accept concentration risk. Both are real trades. Neither is free."),
            ("p", "The mistake is treating firm size as a proxy for quality in either direction. Small is not automatically more careful, and big is not automatically safer — it is safer for the buyer's career and riskier for the buyer's problem."),
            ("p", "So the question worth asking isn't \"what if you get sick.\" It's: <strong>would I rather have 20% of a senior person's attention with institutional backup, or 100% of one person's attention with named fallback arrangements?</strong> For a bounded, non-standard, decision-shaped problem, the second answer wins more often than procurement processes allow."),
        ],
        "ru": [
            ("p", "«А если вы заболеете?» — самое частое возражение против найма студии из одного человека вместо агентства. Вопрос честный. И обычно направлен не на тот риск."),
            ("p", "Честный ответ: <strong>риск не в размере. Риск в размытой ответственности.</strong> У маленькой студии есть реальная проблема непрерывности, и спрятать её негде. У большой компании есть реальная проблема размывания, и спрятать её очень удобно. Что хуже — целиком зависит от типа работы, и эта статья описывает, где выигрывает каждый вариант."),

            ("h2", "О чём на самом деле этот вопрос"),
            ("p", "Под «а если вы заболеете» лежат три разные тревоги, и отвечать на них надо по отдельности:"),
            ("ol", [
                "<strong>Риск исполнения.</strong> Остановится ли работа, если один человек недоступен? Законный вопрос, и отвечать на него нужно конкретными гарантиями, а не заверениями.",
                "<strong>Риск компетенций.</strong> Может ли один человек закрыть всё, что нужно проекту? Тоже законный вопрос и часто настоящая причина выбрать компанию.",
                "<strong>Риск закупки.</strong> Если что-то пойдёт не так, что скажет человек, который это согласовал? Это редко произносят вслух и часто именно это решает.",
            ]),
            ("p", "Третий пункт объясняет очень многое в выборе подрядчиков. Никого никогда не увольняли за наём большой компании, и все это знают. Это реальная цена, которую платит организация заказчика, а не сигнал о качестве подрядчика."),

            ("h2", "Как на самом деле устроена экономика агентства"),
            ("p", "Это не критика, это арифметика. Консалтинговой компании с сотрудниками нужна утилизация, а утилизация определяет, кем укомплектован проект:"),
            ("ul", [
                "<strong>Продаёт редко тот, кто делает.</strong> Старшие партнёры — это функция продаж; их время самый дефицитный и дорогой ресурс компании. Ваш проект укомплектован теми, кто свободен при работающей марже.",
                "<strong>Рычаг — это и есть бизнес-модель.</strong> Прибыль возникает из надзора старших над исполнением младших. Это соотношение — экономика компании, а не выбор под проект; поэтому «больше вовлечения старших» трудно купить, даже когда вы готовы за это платить.",
                "<strong>Замена людей невидима.</strong> Если сильный человек на вашем проекте переходит к более крупному клиенту, вам об этом обычно не скажут: вы получите передачу дел и заверения.",
                "<strong>Методология — актив, который обязан переиспользоваться.</strong> Фреймворки существуют, чтобы работа повторялась от клиента к клиенту. Это реально ценно для типовых задач и реально ограничивает на нетиповых: шаблон применят к вашей задаче, потому что только так сходится экономика.",
            ]),
            ("q", "В большой компании разрыв между тем, кто вас убедил, и тем, кто делает работу, — свойство бизнес-модели. В студии из одного человека разрыва нет, потому что прятаться негде."),

            ("h2", "Где студия из одного человека действительно лучше"),
            ("ul", [
                "<strong>Нетиповые задачи.</strong> Шаблона не существует, поэтому его на вас и не натянут. Это целая категория работ, где фреймворк уверенно выдаёт неверный ответ.",
                "<strong>Короткие проекты под решение.</strong> Две–шесть недель, один вопрос, письменный ответ. Компании структурно плохи в таком: накладные расходы на скоупинг, укомплектование и контроль качества превышают саму работу.",
                "<strong>Прямая передача контекста.</strong> Ваш контекст доходит до человека, который его анализирует, не проходя через аккаунт-менеджера и стартовую презентацию. Меньше слоёв перевода — меньше незамеченных неверных предпосылок.",
                "<strong>Согласованные стимулы по объёму.</strong> У консультанта-одиночки с полным портфелем нет причин растягивать проект: нет «скамейки», которую надо занять. Один этот факт убирает самый частый источник раздувания объёма.",
                "<strong>Готовность сказать «нет».</strong> Отказ от работы стоит компании слота утилизации, а человеку — только гонорара. Услышать «вам этот проект не нужен» гораздо вероятнее от того, у кого нет скамейки.",
            ]),

            ("h2", "Где студия из одного человека действительно хуже"),
            ("p", "Статья, пропускающая этот раздел, — реклама. Выбирайте компанию, когда:"),
            ("ul", [
                "<strong>Нужна параллельная ёмкость.</strong> Сорок интервью в шести странах за три недели — это задача укомплектования, и один человек не решит её сообразительностью.",
                "<strong>Нужны несколько глубоких специализаций одновременно.</strong> Налоги, трудовое право и системная архитектура в одном проекте — это команда, а не универсал.",
                "<strong>Смысл именно в многолетней непрерывности.</strong> Многолетней программе нужна институциональная память, переживающая жизненные обстоятельства отдельного человека.",
                "<strong>Этого требует закупка или регулятор.</strong> Минимальные страховые покрытия, аудиты поставщиков, сертификация ISO, рамочные соглашения. Это реальные ограничения, а не снобизм, и спорить с ними — тратить время всех.",
                "<strong>Вам нужно имя.</strong> Иногда задача документа — быть убедительным для совета директоров или регулятора. Это законное требование; просто честно признайте, что покупаете сигнал, и оцените его как сигнал.",
            ]),
            ("table", {
                "caption": "Какой формат подрядчика под какой проект",
                "head": ["Проект", "Кто подходит", "Почему"],
                "rows": [
                    ["Одно сложное решение, 2–6 недель", "Студия из одного человека", "Накладные расходы компании превышают работу; прямой доступ и есть вся ценность."],
                    ["Нетиповая задача без прецедента", "Студия из одного человека", "Нет шаблона — значит, шаблон и не применят."],
                    ["Операционный обзор в нескольких странах", "Компания", "Параллельную ёмкость и локальное присутствие ничем не заменить."],
                    ["Многолетняя программа трансформации", "Компания", "Институциональная непрерывность вне доступности одного человека."],
                    ["Регулируемая или аудируемая закупка", "Компания", "Страховка, сертификация и рамочные требования — жёсткие ограничения."],
                    ["Документ для совета директоров", "Компания", "Вы покупаете имя; это допустимая покупка, и оценивать её нужно соответственно."],
                    ["Внедрение одного конкретного решения", "Студия из одного человека", "Меньше передач, и делает тот, кто спроектировал."],
                ],
            }),

            ("h2", "Как правильно отвечать на вопрос о непрерывности"),
            ("p", "«Всё будет нормально» — не ответ. Консультант-одиночка, который относится к возражению серьёзно, должен предложить четыре вещи, а заказчик — прямо их потребовать:"),
            ("steps", [
                ("Работа хранится там, где вы её достанете",
                 "Результаты и рабочие материалы в ваших системах или общем репозитории с первого дня, а не отдаются в конце. Если студия исчезнет посреди проекта, всё сделанное останется у вас."),
                ("Промежуточные результаты с фиксированной частотой",
                 "Что-то пригодное к разбору раз в одну–две недели, а не единственная сдача в конце. Это ограничивает вашу уязвимость длиной одного цикла, а не длиной проекта."),
                ("Названный запасной исполнитель",
                 "Конкретный человек или компания, способные подхватить, названные заранее и в идеале видевшие материалы. Не обещание кого-нибудь найти."),
                ("Явные условия на случай недоступности",
                 "Что происходит со сроком и стоимостью, если консультант недоступен две недели. Письменно, согласовано до старта."),
            ]),
            ("note", "Задайте большой компании эквивалентный вопрос: «Если человек, которого вы ставите на проект, уйдёт из компании, что изменится для меня и кто мне об этом скажет?» Ответ часто менее конкретен, чем у хорошего одиночки, и куда менее обязывающий."),

            ("h2", "Пять вопросов, работающих с любым подрядчиком"),
            ("ol", [
                "<strong>Кто именно делает работу и есть ли этот человек на созвоне?</strong> Просите имена и долю их времени. Запишите ответ — он станет точкой отсчёта позже.",
                "<strong>Сколько клиентов будет параллельно с моим?</strong> Оба ответа могут быть нормальными. Сигнал — уклонение, а не число.",
                "<strong>Что заставило бы вас отговорить меня от этого проекта?</strong> Тот, кто не может назвать сценарий, продаёт деятельность.",
                "<strong>Что остаётся у меня в конце и в каком виде?</strong> PDF — не владение. Модели, данные, скрипты и логика рассуждений — да.",
                "<strong>Что будет, если исполнитель станет недоступен?</strong> Конкретный ответ лучше успокаивающего, независимо от размера подрядчика.",
            ]),
            ("p", "Полная версия чек-листа, включая вопросы, вскрывающие раздутый объём, — в статье <a href=\"../how-to-choose-a-consultant/\">как выбрать бизнес-консультанта</a>."),

            ("h2", "В чём настоящая сделка"),
            ("p", "Большая компания продаёт вам избыточность и забирает взамен доступ к человеку, который понимает вашу задачу. Студия из одного человека продаёт неразбавленный доступ и просит принять риск концентрации. Обе сделки реальны. Бесплатной нет ни одной."),
            ("p", "Ошибка — считать размер подрядчика заменителем качества в любую сторону. Маленький не значит автоматически более внимательный, а большой не значит автоматически более безопасный: он безопаснее для карьеры заказчика и рискованнее для задачи заказчика."),
            ("p", "Поэтому стоящий вопрос звучит не «а если вы заболеете». Он звучит так: <strong>что мне нужнее — 20% внимания сильного человека с институциональной подстраховкой или 100% внимания одного человека с прописанным запасным вариантом?</strong> Для ограниченной, нетиповой задачи под решение второй ответ выигрывает чаще, чем позволяют процедуры закупок."),
        ],
    },
    takeaways={
        "en": [
            "Firm size is not a quality signal in either direction: big is safer for the buyer's career, small is often safer for the buyer's problem.",
            "Agency leverage — senior sells, junior delivers — is the business model, which is why more senior time is hard to buy at any price.",
            "Choose a firm for parallel capacity, multiple deep specialisms, multi-year continuity, regulated procurement, or when you're deliberately buying a name.",
            "Choose a one-person studio for bounded, non-standard, decision-shaped work where a template would produce a confident wrong answer.",
            "Demand four continuity guarantees from a solo consultant: work in your systems, interim deliverables, a named fallback, and written unavailability terms.",
            "Ask both kinds of supplier who does the work, what you own at the end, and what would make them advise against the project.",
        ],
        "ru": [
            "Размер подрядчика не является признаком качества ни в ту, ни в другую сторону: большой безопаснее для карьеры заказчика, маленький часто безопаснее для его задачи.",
            "Рычаг агентства — старший продаёт, младший делает — это бизнес-модель, поэтому больше времени старших трудно купить за любые деньги.",
            "Выбирайте компанию под параллельную ёмкость, несколько глубоких специализаций, многолетнюю непрерывность, регулируемую закупку или осознанную покупку имени.",
            "Выбирайте студию из одного человека под ограниченную нетиповую задачу под решение, где шаблон уверенно выдал бы неверный ответ.",
            "Требуйте от одиночки четыре гарантии непрерывности: работа в ваших системах, промежуточные результаты, названный запасной исполнитель, письменные условия на случай недоступности.",
            "Спрашивайте обоих: кто делает работу, что остаётся у вас в конце и что заставило бы их отговорить вас от проекта.",
        ],
    },
    faq={
        "en": [
            ("Is it risky to hire a one-person consulting studio?",
             "There is a real concentration risk, and it should be managed rather than dismissed. Ask for deliverables stored in your systems from day one, interim outputs every one to two weeks, a named fallback person or firm, and written terms covering unavailability. Those four measures reduce your exposure to roughly one delivery cycle instead of the whole project."),
            ("Why would a small studio be better than a large consulting firm?",
             "Because at a firm the person who sells the work is usually not the person who delivers it, and reused methodology is what makes the economics work. For a bounded, non-standard problem that is a disadvantage: a template gets applied confidently to a situation it doesn't fit, and your context passes through translation layers before reaching whoever analyses it."),
            ("When should I definitely choose a firm instead?",
             "When the work needs parallel capacity across locations, several deep specialisms simultaneously, continuity over several years, or when procurement, insurance or regulatory requirements make an individual supplier impossible. Also when the deliverable's job is to carry a recognisable name to a board or regulator."),
            ("How do I check whether a firm will actually staff senior people on my project?",
             "Ask for names and the percentage of their time on your engagement, in writing, and ask what happens if that person leaves or is reassigned, and who informs you. Vagueness here is the signal. Utilisation pressure means reassignment is normal and rarely announced."),
            ("Does a solo consultant cost less than an agency?",
             "The day rate is often comparable; the total is usually lower because there is no account-management layer, no internal QA overhead and less scope inflation. The economics differ more than the rate does — a consultant without a bench to keep busy has no structural reason to extend a project."),
            ("What should I own when the engagement ends?",
             "Not just a PDF. Ask for the underlying models, data, scripts, and the written reasoning behind recommendations, in editable formats, in your own systems. If the only artefact is a presentation, you bought a performance rather than an asset."),
        ],
        "ru": [
            ("Рискованно ли нанимать студию из одного человека?",
             "Риск концентрации реален, и им нужно управлять, а не отмахиваться. Требуйте, чтобы результаты хранились в ваших системах с первого дня, промежуточные материалы выдавались раз в одну–две недели, был назван запасной исполнитель и письменно описаны условия на случай недоступности. Эти четыре меры сокращают вашу уязвимость примерно до одного цикла сдачи вместо всего проекта."),
            ("Чем маленькая студия может быть лучше крупной компании?",
             "Тем, что в компании продаёт работу обычно не тот, кто её делает, а переиспользуемая методология — то, за счёт чего сходится экономика. Для ограниченной нетиповой задачи это минус: шаблон уверенно применяют к ситуации, которой он не подходит, а ваш контекст проходит слои перевода, прежде чем дойти до аналитика."),
            ("Когда точно нужно выбирать компанию?",
             "Когда нужна параллельная ёмкость в нескольких локациях, несколько глубоких специализаций одновременно, непрерывность на годы, либо когда закупка, страхование или регулятор делают работу с физлицом невозможной. А также когда задача документа — нести узнаваемое имя для совета директоров или регулятора."),
            ("Как проверить, что компания реально поставит на проект сильных людей?",
             "Попросите имена и долю их времени на вашем проекте письменно, и спросите, что произойдёт, если этот человек уйдёт или будет переведён, и кто вас об этом уведомит. Сигнал — расплывчатость. Давление утилизации делает переброску людей нормой, о которой редко сообщают."),
            ("Одиночка дешевле агентства?",
             "Дневная ставка часто сопоставима; итоговая сумма обычно ниже, потому что нет слоя аккаунт-менеджмента, нет накладных расходов на внутренний контроль качества и меньше раздувания объёма. Экономика различается сильнее, чем ставка: у консультанта без скамейки нет структурной причины растягивать проект."),
            ("Что должно остаться у меня после проекта?",
             "Не только PDF. Требуйте исходные модели, данные, скрипты и письменную логику рассуждений в редактируемых форматах и в ваших системах. Если единственный артефакт — презентация, вы купили выступление, а не актив."),
        ],
    },
)
