# -*- coding: utf-8 -*-
POST = dict(
    slug="silent-failure-mode",
    date="2026-09-15",
    updated="2026-09-15",
    tag={"en": "Project Management", "ru": "Управление проектами"},
    title={
        "en": "The Silent Failure Mode: Projects Die of Unspoken Problems",
        "ru": "Тихий отказ: проекты рушатся не от неизвестных проблем",
    },
    h1={
        "en": "The Silent Failure Mode: Projects Don't Collapse From Unknown Problems, but From Unspoken Ones",
        "ru": "Тихий отказ: проекты рушатся не от неизвестных проблем, а от невысказанных",
    },
    dek={
        "en": "In almost every post-mortem, somebody knew. The failure isn't that the signal was missing — it's that the system stopped letting it stay visible.",
        "ru": "Почти в каждом разборе провала выясняется, что кто-то знал. Отказ не в том, что сигнала не было, а в том, что система перестала пускать его наверх.",
    },
    description={
        "en": "Why standups degrade into ritual reporting, why one-on-ones turn into perception management, and three interventions that restore visibility before escalation.",
        "ru": "Почему дейли вырождается в ритуальный отчёт, почему один на один превращается в управление впечатлением и три вмешательства, возвращающие видимость.",
    },
    keywords={
        "en": "project failure warning signs, silent failure, daily standup problems, one-on-one meetings, early warning signals, project risk visibility, psychological safety in teams",
        "ru": "признаки провала проекта, ранние сигналы риска, дейли митинг проблемы, встречи один на один, видимость рисков в проекте, почему команда молчит, эскалация проблем",
    },
    hashtags=["ProjectManagement", "Leadership", "Risk", "Teams", "Operations"],
    related=["erp-implementation-failure-reasons", "lidl-digital-transformation-failure", "audit-nobody-reads"],
    body={
        "ru": [
            ("p", "Когда проект разбирают после провала, почти всегда находится человек, который знал. Он заметил риск раньше остальных, усомнился в решении, которое не сходилось, или увидел слабое место в процессе."),
            ("p", "То есть сигнал был. Провал случился позже — в тот момент, когда система перестала позволять этому сигналу оставаться видимым."),
            ("q", "Проекты редко рушатся от проблем, которых никто не знал. Они рушатся от проблем, которые перестали произноситься вслух."),
            ("p", "Это отличается от обычного «плохо управляли рисками». Реестр рисков может быть заполнен, статусы зелёные, отчётность идти вовремя — и ровно поэтому ничего не видно. Хуже всего то, что такая система выглядит стабильной прямо до момента, когда становится поздно."),

            ("h2", "Где сигналы умирают"),
            ("h3", "Дейли, выродившийся в отчёт"),
            ("p", "Ежедневная встреча задумана как место, где всплывают блокеры, риски, зависимости и появившаяся неопределённость. На практике она за несколько недель сползает в ритуал: каждый по очереди сообщает, что всё идёт по плану."),
            ("p", "Механика простая. Сказать «всё в порядке» занимает пять секунд и не влечёт последствий. Сказать «я не уверен, что эта интеграция взлетит» — значит забрать время у восьми человек, вызвать обсуждение и остаться тем, кто задержал встречу. Формат вознаграждает молчание, и через месяц команда сообщает статус, а не состояние."),
            ("h3", "Один на один, превратившийся в управление впечатлением"),
            ("p", "Здесь та же траектория, но менее заметная. Разговор, задуманный как место, где выясняется правда, становится местом, где выстраивается репутация: не поднимать слишком много вопросов, не спорить с решениями слишком прямо, не звучать «негативно» и «тяжело»."),
            ("p", "Причём часто это не страх. Это разумная оценка: человек уже видел, что происходит с теми, кто регулярно приносит плохие новости, и делает вывод. Система не подавляет сигнал — она делает его невыгодным."),
            ("note", "Проверочный вопрос для руководителя: когда вам в последний раз говорили, что ваше решение выглядит неправильным? Если ответ «давно» или «не припомню», это не значит, что решения стали лучше."),

            ("h2", "Локально устойчиво, глобально слепо"),
            ("p", "Со временем такая система приходит в состояние, у которого есть точное описание: <strong>локально устойчива и глобально слепа</strong>. Каждая отдельная встреча проходит гладко, каждый отчёт сходится, каждый участник ведёт себя рационально."),
            ("p", "Мелкие сигналы при этом никуда не деваются — они накапливаются тихо, пока не переходят порог. И тогда проблема появляется как «внезапный» кризис, хотя внезапного в ней ничего не было: она набиралась месяцами из вещей, которые все считали слишком мелкими, чтобы про них говорить."),
            ("p", "Ровно этот механизм лежит в основе большинства сценариев провала внедрений, разобранных в статье <a href=\"../erp-implementation-failure-reasons/\">почему проваливаются внедрения ERP</a>. Там он назван по-другому, но природа одна: ранний признак был, и он был проигнорирован не по злому умыслу, а потому что не имел канала."),

            ("h2", "Работа менеджера ближе к разведке, чем к отчётности"),
            ("p", "Полезно посмотреть на эту задачу так, как на неё смотрят люди, профессионально занимающиеся сбором информации. У руководителя проекта есть ровно три типа источников, и у каждого своя слепая зона."),
            ("table", {
                "caption": "Три источника, из которых складывается картина проекта",
                "head": ["Источник", "Что даёт", "Чем врёт"],
                "rows": [
                    ["Метрики", "Воспроизводимая картина того, что производит проект", "Показывают результат, но не причину; легко оптимизируются под показатель"],
                    ["Люди напрямую", "Контекст, намерения, то, чего нет ни в одной системе", "Неточны и пристрастны — иногда осознанно, чаще нет"],
                    ["Косвенные признаки", "Наблюдения, паттерны, слухи, изменения в поведении", "Неполны и легко трактуются в удобную сторону"],
                ],
            }),
            ("p", "Задача — из трёх источников собрать, что происходит на самом деле, решить, что с этим делать, и зафиксировать решение. Отличие от разведки только в направлении интереса: руководитель проекта работает как внутренняя красная команда в интересах компании, а не против неё. Примерно как отдел качества, который представляется клиентом, чтобы проверить сервис."),

            ("h3", "Почему слежка за сотрудниками — плохой инструмент"),
            ("p", "Есть известный сюжет: руководитель решает выяснить, на что сотрудники тратят рабочее время, чтобы обосновать сокращения, и тем, кого поймали не на том видео, предлагают уйти по собственному желанию."),
            ("p", "Проблема не только этическая. Это <strong>подмена источника</strong>: вместо того чтобы разбираться, что производит проект и где он буксует, измеряется то, что легко измерить. Данные получаются точные и бесполезные — они отвечают на вопрос, который никто не задавал."),
            ("p", "И есть второй эффект, более дорогой. После такой истории все три источника портятся разом: метрики начинают оптимизировать под наблюдение, люди перестают говорить прямо, а косвенные признаки становятся шумом, потому что все ведут себя не так, как обычно. Одним решением руководитель ослепляет себя надолго."),
            ("p", "Часто выясняется и другое: увольнять на самом деле никого не нужно, даже если решение о сокращении уже принято. Нужно внятно объяснить, кто из людей ценен и что компания потеряет, если он уйдёт. В этом интересы руководителя и компании совпадают полностью — сильный отдел выгоден обоим."),

            ("h2", "Что действительно возвращает видимость"),
            ("p", "Три вмешательства, которые дают эффект быстрее остальных и не требуют ни нового инструмента, ни бюджета."),
            ("steps", [
                ("Начинать дейли с блокеров и рисков, а не со статусов",
                 "Порядок пунктов задаёт, что считается содержанием встречи. Если первым спрашивают статус, статусом всё и закончится. Если первым спрашивают, что мешает, — мешающее становится нормальной темой, а не жалобой."),
                ("В один на один задавать вопросы, на которые нельзя ответить «нормально»",
                 "Что вас сейчас беспокоит в проекте? Какие решения кажутся вам хрупкими или неверными? Что тяжело сказать при всех? Последний вопрос — самый продуктивный, потому что прямо признаёт, что групповой формат не всё пропускает."),
                ("Считать повторяющиеся мелочи сигналом, а не шумом",
                 "Одна задержка — случайность. Третья задержка в том же месте — свойство процесса. Ведите список мелких повторяющихся проблем отдельно от реестра рисков: именно там ранние признаки живут до того, как станут кризисом."),
            ]),
            ("p", "И одна вещь, которая работает сильнее любой из трёх: <strong>публично поблагодарить человека, который принёс плохую новость раньше срока</strong>, особенно если новость оказалась верной. Один такой случай меняет расчёт выгод для всей команды надёжнее, чем регламент."),

            ("h2", "Чего это стоит"),
            ("p", "Честно: у прозрачности есть цена, и делать вид, что её нет, бессмысленно."),
            ("ul", [
                "Встречи станут длиннее. Обсуждение блокеров занимает больше времени, чем перечисление статусов.",
                "Картина ухудшится на бумаге. Проблемы, которые были всегда, начнут появляться в отчётах — и со стороны это выглядит как деградация проекта, хотя это её противоположность.",
                "Часть поднятых рисков не реализуется. Это не ошибка сигнализации, это её нормальная работа: пожарная сигнализация, срабатывающая только при настоящем пожаре, никому не нужна.",
                "Кому-то придётся объяснять наверх, почему зелёных статусов стало меньше. Этот разговор проще провести один раз в начале, чем один раз в конце.",
            ]),
            ("q", "Сильные команды отличаются не отсутствием проблем, а непрерывностью их видимости — задолго до того, как понадобится эскалация."),
            ("p", "Всё остальное — следствие. Проблему, которую видно, можно решить дорого или дёшево, вовремя или поздно, самому или с чужой помощью. Проблему, которую не видно, нельзя решить никак — можно только однажды обнаружить её последствия и назвать это внезапным кризисом."),
            ("p", "Готовая форма для этого — <a href=\"{{HOME}}templates/decision-record/\">шаблон протокола решения</a>: три вопроса, блокеры выше статусов и раздел для повторяющихся мелочей."),
        ],

        "en": [
            ("p", "When a project gets taken apart after it fails, there is almost always someone who knew. They noticed the risk early, questioned a decision that didn't hold up, or spotted a structural weakness in the process."),
            ("p", "So the signal existed. The failure happened later — at the moment the system stopped allowing that signal to stay visible."),
            ("q", "Projects rarely collapse from problems nobody knew about. They collapse from problems that stopped being said out loud."),
            ("p", "This is different from ordinary poor risk management. The risk register can be full, the statuses green and the reporting on time — and that is precisely why nothing is visible. The worst part is that such a system looks stable right up until it is too late."),

            ("h2", "Where signals go to die"),
            ("h3", "The standup that degraded into reporting"),
            ("p", "The daily meeting is meant to be where blockers, risks, dependencies and emerging ambiguity surface. In practice it slides into ritual within a few weeks: each person in turn reports that everything is on track."),
            ("p", "The mechanics are simple. Saying \"all fine\" takes five seconds and carries no consequences. Saying \"I'm not convinced this integration will work\" means taking time from eight people, triggering a discussion, and being the one who made the meeting run long. The format rewards silence, and within a month the team reports status rather than state."),
            ("h3", "The one-on-one that became perception management"),
            ("p", "Same trajectory, less visible. A conversation meant for discovering the truth becomes a place where reputation is managed: don't raise too many concerns, don't challenge decisions too directly, don't sound \"negative\" or \"difficult\"."),
            ("p", "Often this isn't fear. It is a reasonable assessment: the person has already watched what happens to people who regularly bring bad news, and drawn a conclusion. The system doesn't suppress the signal — it makes carrying it unprofitable."),
            ("note", "A test question for any manager: when did somebody last tell you your decision looked wrong? If the answer is \"a while ago\" or \"can't recall\", that does not mean the decisions got better."),

            ("h2", "Locally stable, globally blind"),
            ("p", "Over time such a system reaches a state with a precise description: <strong>locally stable and globally blind</strong>. Every individual meeting runs smoothly, every report reconciles, every participant behaves rationally."),
            ("p", "The small signals don't go anywhere — they accumulate quietly until they cross a threshold. Then the problem appears as a \"sudden\" crisis, though there was nothing sudden about it: it assembled itself over months out of things everyone considered too minor to mention."),
            ("p", "This exact mechanism sits under most of the implementation failure scenarios in <a href=\"../erp-implementation-failure-reasons/\">why ERP implementations fail</a>. It is named differently there, but the nature is the same: an early signal existed and was ignored — not maliciously, but because it had no channel."),

            ("h2", "A manager's job is closer to intelligence work than to reporting"),
            ("p", "It helps to look at this the way people who gather information professionally look at it. A project manager has exactly three kinds of source, each with its own blind spot."),
            ("table", {
                "caption": "The three sources a picture of a project is assembled from",
                "head": ["Source", "What it gives", "How it lies"],
                "rows": [
                    ["Metrics", "A reproducible picture of what the project produces", "Show the result, not the cause; easily optimised toward the measure"],
                    ["People, directly", "Context, intent, everything that is in no system", "Inaccurate and biased — sometimes knowingly, more often not"],
                    ["Indirect signals", "Observations, patterns, rumours, changes in behaviour", "Incomplete and easily read in whichever direction suits"],
                ],
            }),
            ("p", "The job is to assemble what is actually happening from all three, decide what to do about it, and record the decision. The only difference from intelligence work is the direction of interest: a project manager operates as an internal red team acting in the company's interest, not against it. Rather like a quality team posing as customers to check the service."),

            ("h3", "Why monitoring employees is a bad instrument"),
            ("p", "There is a well-known story: a manager decides to investigate how employees spend their working hours in order to justify layoffs, and those caught watching the wrong kind of video are encouraged to resign."),
            ("p", "The problem isn't only ethical. It is a <strong>substitution of source</strong>: instead of working out what the project produces and where it stalls, the manager measures what is easy to measure. The data comes out precise and useless — it answers a question nobody asked."),
            ("p", "And there is a second, more expensive effect. After an episode like that, all three sources degrade at once: metrics start being optimised for observation, people stop speaking plainly, and indirect signals turn into noise because everybody is behaving unusually. With one decision the manager blinds himself for a long time."),
            ("p", "It also frequently turns out that nobody actually needs to be fired, even when a headcount decision has already been made. What is needed is a clear account of which people are valuable and what the company would lose if they left. Here the manager's interest and the company's align perfectly — a strong department is good for both."),

            ("h2", "What actually restores visibility"),
            ("p", "Three interventions that shift the dynamic faster than anything else, and need neither a new tool nor a budget."),
            ("steps", [
                ("Start the standup with blockers and risks, not status",
                 "The order of items defines what counts as the content of the meeting. If status is asked first, status is what you get. If what's in the way is asked first, obstruction becomes a normal topic rather than a complaint."),
                ("In one-on-ones, ask questions that can't be answered with \"fine\"",
                 "What is worrying you about the project right now? Which decisions feel fragile or wrong to you? What feels hard to say in a group? The last one is the most productive, because it openly admits the group format doesn't let everything through."),
                ("Treat recurring small issues as signal, not noise",
                 "One delay is chance. A third delay in the same place is a property of the process. Keep a list of small recurring problems separately from the risk register: that is where early warnings live before they become a crisis."),
            ]),
            ("p", "And one thing that works harder than all three: <strong>publicly thank the person who brought bad news early</strong>, especially when the news turns out to be right. A single instance changes the payoff calculation for the whole team more reliably than any policy."),

            ("h2", "What it costs"),
            ("p", "Honestly: transparency has a price, and pretending otherwise is pointless."),
            ("ul", [
                "Meetings get longer. Discussing blockers takes more time than listing statuses.",
                "The picture gets worse on paper. Problems that were always there start appearing in reports, and from outside that looks like a project degrading, when it is the opposite.",
                "Some raised risks never materialise. That is not a fault in the alarm; it is the alarm working. A fire alarm that only goes off during actual fires is of no use to anyone.",
                "Somebody will have to explain upward why there are fewer green statuses. That conversation is easier to have once at the start than once at the end.",
            ]),
            ("q", "Strong teams are not defined by the absence of problems, but by the continuity of problem visibility — long before escalation becomes necessary."),
            ("p", "Everything else follows from that. A visible problem can be solved expensively or cheaply, early or late, alone or with help. An invisible problem cannot be solved at all — you can only discover its consequences one day and call that a sudden crisis."),
            ("p", "A ready-made form for this is <a href=\"{{HOME}}templates/decision-record/\">the decision record template</a>: three questions, blockers above statuses, and a section for recurring small things."),
        ],
    },
    takeaways={
        "ru": [
            "В большинстве разборов провала находится человек, который знал заранее. Отказ не в отсутствии сигнала, а в том, что система перестала его пропускать.",
            "Дейли вырождается в ритуальный отчёт, потому что формат вознаграждает молчание: «всё в порядке» стоит пять секунд, а сомнение — времени восьми человек.",
            "Один на один превращается в управление впечатлением не от страха, а от разумной оценки того, что происходит с людьми, регулярно приносящими плохие новости.",
            "Такая система локально устойчива и глобально слепа: каждая встреча проходит гладко, а мелкие сигналы копятся до порога и всплывают как «внезапный» кризис.",
            "У руководителя три источника — метрики, люди, косвенные признаки — и у каждого своя слепая зона; работа в том, чтобы собрать из них происходящее, а не выбрать удобный.",
            "Слежка за сотрудниками портит все три источника разом и отвечает на вопрос, которого никто не задавал.",
            "Возвращают видимость три вещи: начинать дейли с блокеров, спрашивать в один на один то, на что нельзя ответить «нормально», и вести повторяющиеся мелочи отдельным списком.",
        ],
        "en": [
            "In most failure post-mortems there is someone who knew in advance. The failure is not a missing signal but a system that stopped letting it through.",
            "Standups degrade into ritual reporting because the format rewards silence: \"all fine\" costs five seconds, a doubt costs eight people's time.",
            "One-on-ones become perception management not out of fear but from a reasonable read of what happens to people who regularly bring bad news.",
            "Such a system is locally stable and globally blind: every meeting runs smoothly while small signals accumulate to a threshold and surface as a \"sudden\" crisis.",
            "A manager has three sources — metrics, people, indirect signals — each with its own blind spot; the job is to assemble reality from all three rather than pick the convenient one.",
            "Monitoring employees degrades all three sources at once and answers a question nobody asked.",
            "Three things restore visibility: open the standup with blockers, ask one-on-one questions that can't be answered with \"fine\", and keep recurring small issues as a separate list.",
        ],
    },
    faq={
        "ru": [
            ("Почему команда молчит о проблемах, хотя её никто не наказывает?",
             "Чаще всего дело не в страхе, а в расчёте. Сказать «всё в порядке» стоит пять секунд и не имеет последствий; поднять сомнение — значит забрать время у всей встречи и остаться тем, кто её задержал. Даже без единого наказания формат делает молчание выгодным, и через месяц команда сообщает статус вместо состояния."),
            ("Как понять, что дейли выродился в ритуал?",
             "По содержанию ответов. Если на встрече звучат почти исключительно статусы и почти никогда — блокеры, зависимости и сомнения, встреча уже не выполняет свою функцию. Второй признак: обсуждение проблемы воспринимается как задержка встречи, а не как её смысл."),
            ("Что спрашивать на встрече один на один, чтобы услышать правду?",
             "Вопросы, на которые нельзя ответить «нормально». Что вас сейчас беспокоит в проекте? Какие решения кажутся хрупкими или неверными? Что тяжело сказать при всех? Последний работает лучше остальных, потому что прямо признаёт: групповой формат пропускает не всё."),
            ("Стоит ли следить за тем, чем сотрудники заняты в рабочее время?",
             "Как инструмент управления проектом — нет. Это подмена источника: измеряется то, что легко измерить, вместо того, что производит проект. Хуже того, после такой истории портятся все три источника сразу — метрики начинают оптимизировать под наблюдение, люди перестают говорить прямо, а поведение перестаёт быть показательным."),
            ("Чем ранние признаки отличаются от обычного реестра рисков?",
             "Реестр содержит риски, которые уже назвали и оценили. Ранние признаки — это повторяющиеся мелочи, которые каждая по отдельности слишком незначительна, чтобы попасть в реестр: третья задержка в том же месте, второй вопрос без ответа от того же отдела. Их стоит вести отдельным списком именно потому, что фильтр значимости их отсекает."),
            ("Сколько стоит сделать проблемы видимыми?",
             "Встречи станут длиннее, а отчётность — хуже на бумаге, потому что существовавшие всегда проблемы начнут в неё попадать. Часть поднятых рисков не реализуется, и это нормальная работа сигнализации, а не ложное срабатывание. Главная цена — один разговор с руководством о том, почему зелёных статусов стало меньше; его проще провести в начале, чем в конце."),
        ],
        "en": [
            ("Why does a team stay quiet about problems when nobody punishes them?",
             "Usually it isn't fear but arithmetic. Saying \"all fine\" costs five seconds and carries no consequences; raising a doubt takes time from the whole meeting and makes you the person who ran it long. Without a single punishment the format makes silence profitable, and within a month the team reports status instead of state."),
            ("How do I know a standup has degraded into ritual?",
             "By the content of the answers. If the meeting produces almost only statuses and almost never blockers, dependencies or doubts, it has stopped doing its job. Second sign: discussing a problem is treated as delaying the meeting rather than being its purpose."),
            ("What should I ask in a one-on-one to hear the truth?",
             "Questions that can't be answered with \"fine\". What is worrying you about the project right now? Which decisions feel fragile or wrong? What feels hard to say in a group? The last works best because it openly admits that the group format doesn't let everything through."),
            ("Should I monitor what employees do during working hours?",
             "As a project management instrument, no. It substitutes the source: it measures what is easy to measure instead of what the project produces. Worse, after an episode like that all three sources degrade at once — metrics get optimised for observation, people stop speaking plainly, and behaviour stops being informative."),
            ("How do early warnings differ from a normal risk register?",
             "A register holds risks that have already been named and assessed. Early warnings are recurring small things, each individually too minor to qualify: a third delay in the same place, a second unanswered question from the same department. They deserve a separate list precisely because the significance filter screens them out."),
            ("What does making problems visible cost?",
             "Meetings get longer and reporting looks worse on paper, because problems that were always there start appearing in it. Some raised risks never materialise, and that is the alarm working rather than a false positive. The main price is one conversation with leadership about why there are fewer green statuses — easier to have at the start than at the end."),
        ],
    },
)
