# -*- coding: utf-8 -*-
POST = dict(
    slug="when-not-to-automate",
    date="2026-08-04",
    updated="2026-08-27",
    tag={"en": "Automation & AI", "ru": "Автоматизация и ИИ"},
    title={
        "en": 'When Not to Automate: The Risk of Broken Processes',
        "ru": 'Когда не нужно автоматизировать: скрытые риски',
    },
    h1={
        "en": "When Not to Automate: The Hidden Risk of Automating Broken Processes",
        "ru": "Когда не нужно автоматизировать: скрытый риск автоматизации сломанных процессов",
    },
    dek={
        "en": "Automating a broken process doesn't fix it. It makes the broken version run faster, more consistently, and much harder to notice.",
        "ru": "Автоматизация сломанного процесса его не чинит. Она заставляет сломанную версию работать быстрее, стабильнее и гораздо незаметнее.",
    },
    description={
        "en": 'Six kinds of process you should not automate, the costs missing from every business case, and a scorecard for deciding what deserves to survive.',
        "ru": 'Шесть категорий процессов, которые не стоит автоматизировать, издержки, отсутствующие в обоснованиях, и таблица для решения, что оставить.',
    },
    keywords={
        "en": "when not to automate, process automation risks, automating broken processes, AI automation mistakes, business process automation, hidden costs of automation, workflow automation strategy, RPA failure",
        "ru": "когда не нужно автоматизировать, риски автоматизации процессов, автоматизация сломанных процессов, ошибки внедрения ИИ, автоматизация бизнес-процессов, скрытые издержки автоматизации, стратегия автоматизации, провал RPA",
    },
    hashtags=["Automation", "AI", "ProcessOptimization", "DigitalTransformation", "Efficiency"],
    related=["small-business-automation-guide", "lidl-digital-transformation-failure", "audit-nobody-reads"],
    body={
        "en": [
            ("p", "Every automation pitch sounds the same: \"we'll save you X hours a week.\" Almost none of them ask whether the process being automated should still exist."),
            ("p", "That gap is where most automation money goes to die. <strong>Automating a broken process doesn't fix it. It makes the broken version run faster, more consistently, and far harder to notice</strong> — because nobody has to suffer through it manually any more, and manual suffering was the only signal that it was bad."),
            ("p", "This article is about the second question, the one that comes before \"can this be automated\": <em>does this process deserve to survive in its current form at all?</em>"),

            ("h2", "Why manual pain is a feature"),
            ("p", "A bad manual process generates continuous, distributed complaint. Someone re-types data between two systems and mentions it. Someone chases three approvals and mentions it. The friction is annoying and it is also your only running measurement of how bad the design is."),
            ("p", "Automate it as-is and the complaints stop overnight. Nothing improved — you removed the sensor. The process is now:"),
            ("ul", [
                "<strong>Faster</strong>, so it produces more of whatever it produces, including errors.",
                "<strong>More consistent</strong>, so the errors are systematic instead of random, which makes them harder to spot and easier to build on top of.",
                "<strong>Invisible</strong>, because nobody touches it and nobody thinks about it.",
                "<strong>Load-bearing</strong>, because within two quarters other things depend on its output.",
            ]),
            ("p", "That last one is the expensive part. A bad manual process can be changed with a conversation. A bad automated process that three other systems now consume is a migration project."),
            ("q", "Manual friction is expensive and honest. Automated friction is cheap and silent. Silent is worse."),

            ("h2", "Six things not to automate"),
            ("h3", "1. A process nobody can currently describe end to end"),
            ("p", "If three people give you three different accounts of what happens after step four, you don't have a process — you have a habit with local variations. Automating it freezes one arbitrary version, usually the one belonging to whoever was in the room during requirements gathering. Map first. Half the time the mapping itself removes the need for the automation."),
            ("h3", "2. A process that only exists because of another broken process"),
            ("p", "Reconciliation steps are the classic example. A team spends six hours a week matching two reports that disagree. Automating the matching is a real saving and a permanent commitment to the disagreement. Fix the source and the process disappears entirely — that's a 100% saving, not an 80% one."),
            ("h3", "3. Judgement work wearing a repetitive costume"),
            ("p", "Some tasks look repetitive from a distance and contain a handful of high-consequence decisions in the middle. Classifying an unusual customer complaint, deciding whether a shipment exception is worth escalating, approving a non-standard discount. Volume looks like repetition. The distribution of consequences is what matters, not the average case."),
            ("h3", "4. A process about to change for external reasons"),
            ("p", "New regulation, a system migration, a pricing model change in the next two quarters. Automation built against a spec with a known expiry date is technical debt purchased deliberately."),
            ("h3", "5. Anything where the exception rate is above roughly 20%"),
            ("p", "Above that threshold, the exception handling becomes the actual system: you build automation, then build a manual process to catch what it can't do, then a reconciliation between the two. Three processes where there was one. Below 5% exceptions, automation is usually clean; between 5 and 20% it depends on how expensive an exception is; above 20%, redesign before you automate."),
            ("h3", "6. Anything whose output nobody checks"),
            ("p", "If no human currently reads the result, automation removes the last opportunity for the error to be noticed. Before automating, ask who looks at the output and what they would do if it were wrong. If the honest answer is \"nobody\" and \"nothing,\" you're about to industrialise an unmonitored process."),

            ("h2", "A worked example: the AI manager that didn't happen"),
            ("p", "We once evaluated replacing a full-time coordinator role with an AI-driven assistant handling estimates, document preparation and logistics coordination. On paper it was a strong case: high volume, repetitive-looking, clearly defined inputs."),
            ("p", "What the process map showed:"),
            ("ul", [
                "Roughly 80% of the work was genuine repetition — pulling numbers into a template, formatting documents, sending standard follow-ups, chasing status.",
                "Around 20% was a small number of judgement calls: which supplier exception to accept, when a client's request needed a different commercial answer, when a delay was worth escalating and to whom.",
                "Almost all of the <em>risk</em> lived in that 20%. The repetitive part being wrong caused rework. The judgement part being wrong lost money or lost a client.",
            ]),
            ("p", "So the honest answer wasn't \"yes, automate the role.\" It was: automate the 80% that was pure repetition, leave the 20% exactly where it was, and — importantly — make the automated portion produce a visible queue for the human, so the judgement calls arrive with context instead of being buried."),
            ("p", "The saving was smaller than the original pitch and it held up. A full automation would have produced a larger number in the business case and a worse outcome in the second quarter."),

            ("h2", "The costs that never make it into the business case"),
            ("table", {
                "caption": "Automation costs that are real, recurring, and routinely omitted",
                "head": ["Cost", "Why it's missed", "Rough size"],
                "rows": [
                    ["Maintenance when an upstream system changes", "It's someone else's release note", "10–20% of build cost per year, forever"],
                    ["Exception handling", "Estimated from the happy path", "Often exceeds the build itself when exceptions >10%"],
                    ["Silent failure", "Nobody budgets for the thing that doesn't announce itself", "Unbounded until discovered; grows with time-to-detection"],
                    ["Knowledge loss", "The people who understood the manual version stop doing it", "Appears 12–24 months later as inability to change the process"],
                    ["Ownership", "Nobody is named at handover", "The automation quietly becomes nobody's job and rots"],
                    ["Model drift (AI-based steps)", "Accuracy at launch is treated as a constant", "Requires ongoing sampling and re-evaluation, not a one-off test"],
                ],
            }),
            ("note", "One rule that prevents most of this: no automation goes live without a named owner and a monitoring answer to \"how would we know if this stopped being correct?\" If neither exists, you're not deploying automation, you're deploying an unmonitored dependency."),

            ("h2", "A scorecard for deciding"),
            ("p", "Before building anything, score the process from 0 to 2 on each line. Anything below 7 out of 12 means redesign first."),
            ("checklist", [
                "<strong>Stability:</strong> will this process be materially the same in 18 months? (0 = a change is already scheduled)",
                "<strong>Definition:</strong> can two people independently describe it identically? (0 = accounts diverge after step three)",
                "<strong>Exception rate:</strong> under 5% = 2, 5–20% = 1, over 20% = 0",
                "<strong>Consequence distribution:</strong> is a wrong output cheap to fix? (0 = a wrong output costs a client or a fine)",
                "<strong>Verification:</strong> does someone read the output and could they tell it was wrong? (0 = nobody looks)",
                "<strong>Necessity:</strong> would this process still be needed if the upstream problem were fixed? (0 = it exists only to compensate)",
            ]),
            ("p", "The scorecard's real function is to make one specific conversation happen: the one where somebody has to say out loud that the process only exists because of a decision nobody wants to revisit. That conversation is what the LIDL case in <a href=\"../lidl-digital-transformation-failure/\">the €500 million article</a> was avoided at scale."),

            ("h2", "How to automate the part that should be automated"),
            ("steps", [
                ("Map the current process by observation, not by interview",
                 "Watch it happen or read the logs. What people describe and what people do differ in exactly the places that break automation."),
                ("Split repetition from judgement explicitly",
                 "Draw the line and get the people who do the work to argue about where it sits. That argument is the requirements document."),
                ("Delete before you build",
                 "For each step, ask what happens if it simply stops. Steps that survive that question honestly are usually fewer than the map suggests."),
                ("Automate the repetition and route the judgement, with context",
                 "The human should receive a decision with everything needed to make it, not a notification that something needs attention."),
                ("Instrument the output before go-live",
                 "Define the signal that tells you it's still working — a sampled check, a volume anomaly alert, a weekly review of exceptions. Automation without a detector is a bet that nothing will change."),
                ("Name an owner and a review date",
                 "Six months out, someone re-examines whether the process still deserves to exist. Put it in a calendar, not in a document."),
            ]),

            ("h2", "When automation is clearly right"),
            ("p", "None of this is an argument against automation — the same discipline is what makes it work. Automate confidently when the process is stable, describable, low-exception, verifiable, and would still be needed in a well-run version of the company. Under those conditions, the savings are real, they compound, and the maintenance cost stays proportionate. The <a href=\"../small-business-automation-guide/\">small business automation guide</a> covers what to do first when that's your situation."),
            ("p", "The question worth asking before any automation project isn't \"can this be automated.\" It's: <strong>if I automated this exactly as it exists today, would I be proud of what I shipped?</strong>"),
        ],
        "ru": [
            ("p", "Любое предложение по автоматизации звучит одинаково: «сэкономим вам X часов в неделю». Почти ни одно из них не спрашивает, должен ли автоматизируемый процесс вообще существовать."),
            ("p", "Именно в этом разрыве и умирает большая часть денег на автоматизацию. <strong>Автоматизация сломанного процесса его не чинит. Она заставляет сломанную версию работать быстрее, стабильнее и куда незаметнее</strong> — потому что теперь никому не приходится страдать вручную, а ручное страдание было единственным сигналом, что всё плохо."),
            ("p", "Эта статья про второй вопрос, который идёт до «можно ли это автоматизировать»: <em>заслуживает ли процесс существовать в текущем виде вообще?</em>"),

            ("h2", "Почему ручная боль — это функция"),
            ("p", "Плохой ручной процесс генерирует непрерывный распределённый поток жалоб. Кто-то перебивает данные между двумя системами и говорит об этом. Кто-то бегает за тремя согласованиями и говорит об этом. Трение раздражает — и одновременно является вашим единственным работающим измерением того, насколько плоха конструкция."),
            ("p", "Автоматизируйте его как есть — и жалобы прекратятся за ночь. Ничего не улучшилось: вы убрали датчик. Теперь процесс:"),
            ("ul", [
                "<strong>Быстрее</strong> — значит, производит больше того, что производит, включая ошибки.",
                "<strong>Стабильнее</strong> — значит, ошибки стали систематическими вместо случайных, а такие заметить труднее и надстроить над ними проще.",
                "<strong>Невидим</strong> — потому что его никто не трогает и о нём никто не думает.",
                "<strong>Несущий</strong> — потому что за пару кварталов от его результата начинают зависеть другие вещи.",
            ]),
            ("p", "Последний пункт — самый дорогой. Плохой ручной процесс меняется разговором. Плохой автоматизированный процесс, результат которого потребляют три другие системы, — это проект миграции."),
            ("q", "Ручное трение дорогое и честное. Автоматизированное трение дешёвое и молчаливое. Молчаливое хуже."),

            ("h2", "Шесть вещей, которые не надо автоматизировать"),
            ("h3", "1. Процесс, который никто не может описать целиком"),
            ("p", "Если три человека дают три разные версии того, что происходит после четвёртого шага, у вас не процесс, а привычка с местными вариациями. Автоматизация замораживает одну произвольную версию — обычно ту, чей носитель был в комнате при сборе требований. Сначала карта. В половине случаев само составление карты снимает потребность в автоматизации."),
            ("h3", "2. Процесс, существующий только из-за другого сломанного процесса"),
            ("p", "Классика — шаги сверки. Команда тратит шесть часов в неделю на сопоставление двух отчётов, которые расходятся. Автоматизация сопоставления — реальная экономия и одновременно постоянное обязательство сохранять расхождение. Почините источник, и процесс исчезнет целиком: это экономия 100%, а не 80%."),
            ("h3", "3. Работа с суждением, переодетая в рутину"),
            ("p", "Некоторые задачи издалека выглядят повторяющимися, а внутри содержат несколько решений с высокими последствиями. Классификация необычной жалобы, решение о том, стоит ли эскалировать исключение по поставке, согласование нестандартной скидки. Объём выглядит как повторяемость. Значение имеет распределение последствий, а не средний случай."),
            ("h3", "4. Процесс, который вот-вот изменится по внешним причинам"),
            ("p", "Новое регулирование, миграция системы, смена ценовой модели в ближайшие два квартала. Автоматизация, построенная под спецификацию с известным сроком годности, — это осознанно купленный технический долг."),
            ("h3", "5. Всё, где доля исключений выше примерно 20%"),
            ("p", "Выше этого порога обработка исключений становится самой системой: вы строите автоматизацию, потом ручной процесс для того, что она не умеет, потом сверку между ними. Три процесса вместо одного. Ниже 5% исключений автоматизация обычно чистая; между 5 и 20% всё зависит от цены исключения; выше 20% — сначала переработайте процесс."),
            ("h3", "6. Всё, чей результат никто не проверяет"),
            ("p", "Если сейчас результат не читает ни один человек, автоматизация убирает последнюю возможность заметить ошибку. Перед автоматизацией спросите, кто смотрит на выход и что он сделает, если там будет неправильно. Если честный ответ «никто» и «ничего» — вы собираетесь поставить на поток неконтролируемый процесс."),

            ("h2", "Разобранный пример: ИИ-менеджер, которого не стали делать"),
            ("p", "Мы однажды оценивали замену штатного координатора на ИИ-ассистента, который вёл бы расчёты, подготовку документов и координацию логистики. На бумаге кейс был сильный: большой объём, внешне рутинная работа, ясно определённые входы."),
            ("p", "Что показала карта процесса:"),
            ("ul", [
                "Около 80% работы было настоящей рутиной — подставить цифры в шаблон, отформатировать документы, отправить стандартные напоминания, узнать статус.",
                "Примерно 20% — небольшое число решений: какое исключение поставщика принять, когда запрос клиента требует другого коммерческого ответа, когда задержку нужно эскалировать и кому.",
                "Практически весь <em>риск</em> жил в этих 20%. Ошибка в рутинной части приводила к переделке. Ошибка в решении стоила денег или клиента.",
            ]),
            ("p", "Поэтому честный ответ был не «да, автоматизируем роль». Он был такой: автоматизировать 80% чистой рутины, оставить 20% ровно там, где они были, и — что важно — сделать так, чтобы автоматизированная часть формировала видимую очередь для человека: решения приходят с контекстом, а не тонут."),
            ("p", "Экономия оказалась меньше, чем в исходном предложении, и она выдержала проверку временем. Полная автоматизация дала бы более красивую цифру в обосновании и худший результат во втором квартале."),

            ("h2", "Издержки, которые никогда не попадают в обоснование"),
            ("table", {
                "caption": "Реальные, повторяющиеся и обычно пропускаемые издержки автоматизации",
                "head": ["Издержка", "Почему её пропускают", "Примерный размер"],
                "rows": [
                    ["Поддержка при изменениях в смежных системах", "Это чужие release notes", "10–20% стоимости разработки в год, постоянно"],
                    ["Обработка исключений", "Оценивается по счастливому пути", "Часто превышает саму разработку при доле исключений >10%"],
                    ["Тихий отказ", "Никто не закладывает бюджет на то, что о себе не сообщает", "Не ограничена до момента обнаружения; растёт со временем детекции"],
                    ["Потеря знания", "Люди, понимавшие ручную версию, перестают ею заниматься", "Проявляется через 12–24 месяца как невозможность изменить процесс"],
                    ["Владение", "При передаче никто не назначен", "Автоматизация тихо становится ничьей задачей и гниёт"],
                    ["Дрейф модели (шаги на ИИ)", "Точность на старте считается константой", "Требует регулярных выборочных проверок, а не разового теста"],
                ],
            }),
            ("note", "Одно правило снимает большую часть этого: ничто не выходит в продуктив без названного владельца и ответа на вопрос «как мы узнаем, что это перестало быть верным?». Если ни того, ни другого нет — вы разворачиваете не автоматизацию, а неконтролируемую зависимость."),

            ("h2", "Оценочная таблица для решения"),
            ("p", "Перед тем как что-либо строить, оцените процесс от 0 до 2 по каждой строке. Меньше 7 из 12 — сначала переработка."),
            ("checklist", [
                "<strong>Стабильность:</strong> будет ли процесс по существу таким же через 18 месяцев? (0 — изменение уже запланировано)",
                "<strong>Определённость:</strong> могут ли два человека независимо описать его одинаково? (0 — версии расходятся после третьего шага)",
                "<strong>Доля исключений:</strong> меньше 5% = 2, 5–20% = 1, больше 20% = 0",
                "<strong>Распределение последствий:</strong> дёшево ли исправить неверный результат? (0 — неверный результат стоит клиента или штрафа)",
                "<strong>Проверяемость:</strong> читает ли кто-то результат и заметит ли ошибку? (0 — не смотрит никто)",
                "<strong>Необходимость:</strong> был бы нужен процесс, если бы починили источник проблемы? (0 — существует только как компенсация)",
            ]),
            ("p", "Настоящая функция этой таблицы — заставить произойти один конкретный разговор: тот, где кто-то вслух говорит, что процесс существует только из-за решения, которое никто не хочет пересматривать. Именно этого разговора в масштабе избежали в кейсе из статьи <a href=\"../lidl-digital-transformation-failure/\">про €500 миллионов</a>."),

            ("h2", "Как автоматизировать то, что автоматизировать нужно"),
            ("steps", [
                ("Составьте карту процесса наблюдением, а не интервью",
                 "Смотрите, как это происходит, или читайте логи. То, что люди описывают, и то, что люди делают, расходятся ровно в тех местах, где ломается автоматизация."),
                ("Явно разделите рутину и суждение",
                 "Проведите линию и дайте людям, которые делают работу, поспорить о том, где она проходит. Этот спор и есть документ требований."),
                ("Удаляйте до того, как строить",
                 "По каждому шагу спросите, что будет, если он просто перестанет выполняться. Шагов, честно переживающих этот вопрос, обычно меньше, чем на карте."),
                ("Автоматизируйте рутину и маршрутизируйте решения вместе с контекстом",
                 "Человек должен получать решение со всем необходимым, чтобы его принять, а не уведомление о том, что что-то требует внимания."),
                ("Настройте наблюдаемость до запуска",
                 "Определите сигнал, показывающий, что всё ещё работает: выборочная проверка, оповещение об аномалии объёма, еженедельный разбор исключений. Автоматизация без детектора — это ставка на то, что ничего не изменится."),
                ("Назначьте владельца и дату пересмотра",
                 "Через полгода кто-то заново проверяет, заслуживает ли процесс существовать. Ставьте это в календарь, а не в документ."),
            ]),

            ("h2", "Когда автоматизация точно уместна"),
            ("p", "Всё вышесказанное — не аргумент против автоматизации: именно эта дисциплина и делает её работающей. Автоматизируйте уверенно, когда процесс стабилен, описуем, с малой долей исключений, проверяем и был бы нужен даже в хорошо устроенной версии компании. При этих условиях экономия реальна, накапливается, а стоимость поддержки остаётся соразмерной. Что делать в первую очередь в такой ситуации — в <a href=\"../small-business-automation-guide/\">руководстве по автоматизации малого бизнеса</a>."),
            ("p", "Вопрос, который стоит задать перед любым проектом автоматизации, звучит не «можно ли это автоматизировать». Он звучит так: <strong>если я автоматизирую это ровно в том виде, в каком оно есть сегодня, буду ли я гордиться тем, что выпустил?</strong>"),
        ],
    },
    takeaways={
        "en": [
            "Manual friction is the only running measurement of how bad a process design is; automating it as-is removes the sensor, not the problem.",
            "Don't automate a process nobody can describe end to end, one that exists only to compensate for another broken process, or judgement work that looks repetitive from a distance.",
            "Exception rate is the practical threshold: under 5% is usually clean, over 20% means redesign before automating.",
            "The costs missing from every business case are maintenance, exception handling, silent failure, knowledge loss, ownership and model drift.",
            "Automate the repetitive 80% and route the judgement 20% to a human with full context rather than a bare notification.",
            "Nothing goes live without a named owner and an answer to \"how would we know if this stopped being correct?\"",
        ],
        "ru": [
            "Ручное трение — единственное работающее измерение того, насколько плоха конструкция процесса; автоматизация как есть убирает датчик, а не проблему.",
            "Не автоматизируйте процесс, который никто не может описать целиком, процесс, существующий только как компенсация другого сломанного, и работу с суждением, издалека похожую на рутину.",
            "Практический порог — доля исключений: меньше 5% обычно чисто, больше 20% означает переработку до автоматизации.",
            "Издержки, отсутствующие в любом обосновании: поддержка, обработка исключений, тихий отказ, потеря знания, владение и дрейф модели.",
            "Автоматизируйте рутинные 80% и направляйте оставшиеся 20% человеку вместе с полным контекстом, а не голым уведомлением.",
            "Ничто не выходит в продуктив без названного владельца и ответа на вопрос «как мы узнаем, что это перестало быть верным?».",
        ],
    },
    faq={
        "en": [
            ("What happens if you automate a broken process?",
             "It runs faster, produces errors systematically rather than randomly, and stops generating the complaints that told you it was badly designed. Within a couple of quarters other systems start consuming its output, so fixing it changes from a conversation into a migration project."),
            ("How do I know whether a process should be automated?",
             "Score it on six dimensions: stability over the next 18 months, whether two people describe it identically, exception rate, cost of a wrong output, whether anyone verifies the output, and whether the process would still be needed if the upstream problem were fixed. Weak scores mean redesign first."),
            ("What exception rate makes automation a bad idea?",
             "As a working rule: under 5% is usually clean, 5–20% depends on how expensive an exception is, and above 20% you will end up building three processes — the automation, the manual fallback, and a reconciliation between them."),
            ("Should AI change this calculation?",
             "It changes what is technically automatable, not what is worth automating. AI-based steps also add a cost the classic business case omits: accuracy at launch is not a constant, so you need ongoing sampling and re-evaluation rather than a one-off acceptance test."),
            ("What is the biggest hidden cost of automation?",
             "Silent failure. Every other cost is bounded and roughly estimable; a process that stops being correct without announcing it accumulates damage until someone happens to notice. This is why a monitoring answer should be a precondition for go-live."),
            ("Is it ever right to automate a process you plan to change?",
             "Rarely, and only when the automation is deliberately disposable and priced as such. Building against a specification with a known expiry date is technical debt purchased on purpose — acceptable if everyone says so out loud, damaging when it's presented as a permanent solution."),
        ],
        "ru": [
            ("Что происходит, если автоматизировать сломанный процесс?",
             "Он начинает работать быстрее, ошибается систематически, а не случайно, и перестаёт порождать жалобы, которые и сообщали о плохой конструкции. За пару кварталов его результат начинают потреблять другие системы, и починка превращается из разговора в проект миграции."),
            ("Как понять, стоит ли автоматизировать процесс?",
             "Оцените его по шести измерениям: стабильность в ближайшие 18 месяцев, одинаково ли его описывают два человека, доля исключений, цена неверного результата, проверяет ли кто-то выход и был бы нужен процесс, если бы починили источник проблемы. Низкие оценки означают сначала переработку."),
            ("При какой доле исключений автоматизация — плохая идея?",
             "Рабочее правило: меньше 5% обычно чисто, 5–20% зависит от цены исключения, выше 20% вы построите три процесса — автоматизацию, ручной запасной путь и сверку между ними."),
            ("Меняет ли ИИ эти расчёты?",
             "Он меняет то, что технически автоматизируемо, а не то, что стоит автоматизировать. Шаги на ИИ добавляют издержку, которой нет в классическом обосновании: точность на старте не константа, поэтому нужны регулярные выборочные проверки, а не разовый приёмочный тест."),
            ("Какая скрытая издержка автоматизации самая опасная?",
             "Тихий отказ. Все прочие издержки ограничены и примерно оцениваемы; процесс, переставший быть верным и не сообщивший об этом, накапливает ущерб, пока кто-нибудь случайно не заметит. Поэтому ответ про мониторинг должен быть условием выхода в продуктив."),
            ("Бывает ли правильным автоматизировать процесс, который планируется менять?",
             "Редко и только если автоматизация сознательно одноразовая и оценена как таковая. Разработка под спецификацию с известным сроком годности — это осознанно купленный технический долг: допустимо, когда об этом сказано вслух, и вредно, когда подаётся как постоянное решение."),
        ],
    },
)
