# -*- coding: utf-8 -*-
POST = dict(
    slug="why-startups-need-consulting",
    date="2026-06-30",
    updated="2026-08-27",
    tag={"en": "Startups", "ru": "Стартапы"},
    title={
        "en": "Why Startups Need Consulting (Even the Ones That Think They Can't Afford It)",
        "ru": "Зачем стартапу консалтинг, даже если кажется, что денег на него нет",
    },
    h1={
        "en": "Why Startups Need Consulting (Even the Ones That Think They Can't Afford It)",
        "ru": "Зачем стартапу консалтинг, даже если кажется, что денег на него нет",
    },
    dek={
        "en": "Consulting isn't for companies big enough to afford being slow. It's most useful exactly when you're too small to afford being wrong.",
        "ru": "Консалтинг нужен не тем, кто достаточно велик, чтобы позволить себе медлительность. Он полезнее всего тем, кто слишком мал, чтобы позволить себе ошибку.",
    },
    description={
        "en": "The runway maths behind hiring outside expertise at seed stage, the four moments when it pays for itself, how to scope an engagement so it can't drift into a retainer, and when a founder genuinely shouldn't hire anyone.",
        "ru": "Арифметика ранвея за наймом внешней экспертизы на ранней стадии, четыре момента, когда это окупается, как ограничить проект, чтобы он не превратился в абонентку, и когда основателю действительно не нужен консультант.",
    },
    keywords={
        "en": "consulting for startups, startup advisory, when to hire a consultant, seed stage decisions, founder decision making, startup runway management, outside expertise, fractional expertise for founders",
        "ru": "консалтинг для стартапов, консультант для основателя, когда нанимать консультанта, решения на ранней стадии, управление ранвеем стартапа, внешняя экспертиза, советник стартапа, консультант вместо найма",
    },
    hashtags=["StartupAdvice", "Founders", "BusinessConsulting", "Entrepreneurship", "StartupGrowth"],
    related=["consulting-retainer-trap", "how-much-does-business-consulting-cost", "how-to-choose-a-consultant"],
    body={
        "en": [
            ("p", "Most founders think consulting is something you buy once you're big enough to afford being slow. It is the opposite. <strong>Consulting is most valuable exactly when you're too small to absorb a wrong decision.</strong>"),
            ("p", "A 200-person company can survive a bad six-month bet on the wrong process, the wrong automation, the wrong senior hire. It shows up as a rounding error and a slightly awkward retro. A seven-person startup cannot: one wrong call burns a quarter of the runway, and runway does not come back."),
            ("p", "This article is the practical version of that argument: the actual arithmetic, the four moments where outside input reliably pays for itself, how to scope an engagement so it can't quietly become a subscription, and — because it matters — the cases where a founder should not hire anyone at all."),

            ("h2", "The asymmetry nobody prices correctly"),
            ("p", "Founders are good at pricing spend and bad at pricing <em>elapsed time on the wrong path</em>. Compare two costs that feel very different and are not:"),
            ("table", {
                "caption": "What a decision actually costs at different company sizes",
                "head": ["", "7-person startup", "200-person company"],
                "rows": [
                    ["A wrong three-month build", "≈25% of annual engineering capacity; often the difference between reaching the next milestone and not", "One team's quarter; absorbed into a roadmap review"],
                    ["A wrong senior hire", "3–6 months of salary plus the decisions they made while there — frequently the largest single cash mistake at seed stage", "A performance process and a backfill"],
                    ["A wrong platform choice", "Migration cost lands during the exact quarter you're raising", "Scheduled as a two-year modernisation programme"],
                    ["Two months of indecision", "Two months of runway, gone, with nothing to show a board", "A slipped OKR"],
                ],
            }),
            ("p", "The right unit for a startup is not money. It is <strong>weeks of runway per decision</strong>. Once you convert to that unit, a one-off engagement that costs the equivalent of a few days of burn to avoid a three-month detour stops looking like a luxury and starts looking like insurance you can actually price."),

            ("h2", "What a startup is actually buying"),
            ("p", "Not a strategy deck. Not a framework. Not a 60-slide market landscape you already know better than the person presenting it — that failure mode has its own article: <a href=\"../audit-nobody-reads/\">the audit nobody reads</a>."),
            ("p", "What is worth paying for is narrow and specific:"),
            ("ul", [
                "<strong>Pattern recognition on a failure you haven't hit yet.</strong> Someone who has watched the same decision go wrong four times can tell you which of your three options has the failure mode you can't see from inside.",
                "<strong>A written answer with a number in it.</strong> Not \"consider evaluating\" — \"do this, here's the cost, here's what breaks if you're wrong, here's the trigger to reverse it.\"",
                "<strong>Removal of a decision from your head.</strong> Founder attention is the scarcest input in the company. Outsourcing one hard analysis for two weeks is often worth more than the analysis itself.",
                "<strong>An opinion with no internal politics attached.</strong> Your team's recommendation is partly shaped by who will have to do the work. An outsider's isn't.",
            ]),
            ("q", "You are not buying knowledge. You are buying the removal of one specific uncertainty, before it becomes three months of building the wrong thing."),

            ("h2", "The four moments where it reliably pays off"),
            ("h3", "1. Before an irreversible technical or structural commitment"),
            ("p", "Choosing the data model, the billing architecture, the core platform, the legal structure of a multi-country entity. These are decisions where the cost of being wrong is paid in migrations, not in refactors. A few days of outside review before the commitment is the highest-leverage money a startup spends."),
            ("h3", "2. When you're about to hire for a skill you can't evaluate"),
            ("p", "The classic seed-stage trap: hiring a senior specialist in a discipline where nobody on the team can tell competence from confidence. Buying two days of expertise to write the brief, review the shortlist and design the technical evaluation is dramatically cheaper than a wrong hire — and it also tells you whether you needed the hire at all."),
            ("h3", "3. When the same problem has been discussed three times without resolution"),
            ("p", "A recurring, unresolved debate inside a founding team is almost never an information problem. It is usually a framing problem — the two sides are optimising different variables and nobody has said so out loud. This is the cheapest possible engagement and the one founders leave longest."),
            ("h3", "4. When a number is moving and nobody can explain why"),
            ("p", "Churn, conversion, cost per acquisition, delivery time. If the team's explanation changes each month, you are looking at a measurement problem wearing the costume of a performance problem. An outsider with no stake in last quarter's narrative resolves it faster."),
            ("note", "Notice what's missing from that list: \"we need a strategy.\" A startup that needs an outsider to define its strategy has a founder problem, not a consulting problem, and no engagement will fix it."),

            ("h2", "How to scope it so it can't become a retainer"),
            ("p", "The most common way this goes wrong is not a bad consultant. It is an unbounded engagement that quietly turns into a monthly cost with no decision attached — the mechanism described in <a href=\"../consulting-retainer-trap/\">the consulting retainer trap</a>. Four constraints prevent it:"),
            ("steps", [
                ("Write the question as a single sentence ending in a question mark",
                 "\"Should we build the billing engine in-house or integrate a provider, given a 14-month runway?\" If you cannot compress it to one sentence, you are not ready to buy help — you are still deciding what to ask."),
                ("State the deliverable as an artefact, not an activity",
                 "\"A written recommendation with a cost estimate, the two conditions under which it's wrong, and a reversal trigger.\" Not \"analysis and support.\""),
                ("Fix the end date before the start date",
                 "Anything under three weeks stays sharp. Anything over six weeks starts generating work to justify itself, unless the scope genuinely warrants it."),
                ("Agree what happens after, in writing",
                 "Default should be: engagement ends, you own the decision. Any follow-on is a new, separately scoped piece of work. Say this out loud at the start and the drift never begins."),
            ]),

            ("h2", "When a founder should not hire a consultant"),
            ("p", "Being useful here means saying when the answer is no. Don't hire anyone if:"),
            ("ul", [
                "<strong>You already know the answer and want cover.</strong> Buying external validation for a decision you've made is the most expensive form of procrastination available.",
                "<strong>The problem is that you haven't talked to enough customers.</strong> No outsider can substitute for twenty conversations you haven't had. This is the single most common misdiagnosis at pre-seed.",
                "<strong>Nobody internally can act on the answer for the next quarter.</strong> An answer that arrives before the capacity to use it decays into a document.",
                "<strong>You want someone to manage a team you're avoiding managing.</strong> That is a hire, or a conversation you're postponing — not an engagement.",
                "<strong>The budget would meaningfully shorten your runway.</strong> If the fee is more than roughly a week of burn, the engagement has to be tied to a decision that's worth more than a week of burn. Usually it is. Sometimes it isn't — check.",
            ]),

            ("h2", "Telling a useful consultant from an expensive one, in one call"),
            ("p", "You get a lot of signal in thirty minutes if you're listening for the right things. A fuller checklist lives in <a href=\"../how-to-choose-a-consultant/\">how to choose a business consultant</a>; the short version for founders:"),
            ("ul", [
                "<strong>Do they narrow, or do they expand?</strong> Someone useful spends the call making your question smaller and more specific. Someone selling makes it bigger.",
                "<strong>Do they name a scenario where they'd tell you not to do the project?</strong> If no such scenario exists, you're talking to a vendor of activity.",
                "<strong>Do they ask what happens to the answer?</strong> A good consultant wants to know who will implement it and whether that person is in the room. A bad one doesn't need to know, because the deliverable is the deliverable.",
                "<strong>Can they describe a failure of theirs in specific terms?</strong> Specific means named constraints and a wrong assumption, not \"the client wasn't ready.\"",
                "<strong>Is the person on the call the person doing the work?</strong> At startup budgets this matters more than firm size — see <a href=\"../one-person-consulting-studio/\">the one-person studio argument</a>.",
            ]),

            ("h2", "The founders who use it well"),
            ("p", "They don't outsource decisions. They buy a second, sharper pair of eyes for the one decision that's too expensive to get wrong on the first attempt — and they keep the decision."),
            ("p", "The founders who avoid consulting usually aren't avoiding the cost. They're avoiding the idea that someone outside the company might see the problem faster than they can. That instinct is understandable, and it is the expensive one: it converts a two-week question into a three-month build."),
            ("p", "You don't need a retainer. You need someone for one hard question, at the one moment it actually matters, with an end date written down before you start."),
        ],
        "ru": [
            ("p", "Большинство основателей думает, что консалтинг покупают, когда компания уже достаточно велика, чтобы позволить себе медлительность. Всё ровно наоборот. <strong>Консалтинг ценнее всего тогда, когда вы слишком малы, чтобы пережить неверное решение.</strong>"),
            ("p", "Компания на 200 человек переживёт неудачную полугодовую ставку на неправильный процесс, неправильную автоматизацию, неправильного руководителя. Это будет погрешность округления и слегка неловкая ретроспектива. Стартап из семи человек — нет: одно неверное решение сжигает четверть ранвея, а ранвей не возвращается."),
            ("p", "Эта статья — практическая версия того же аргумента: реальная арифметика, четыре момента, когда внешний взгляд стабильно окупается, как ограничить проект, чтобы он тихо не превратился в подписку, и — это важно — случаи, когда основателю не нужно нанимать никого."),

            ("h2", "Асимметрия, которую все считают неправильно"),
            ("p", "Основатели хорошо считают расходы и плохо считают <em>время, потраченное не на том пути</em>. Сравните две стоимости, которые кажутся очень разными, а на деле нет:"),
            ("table", {
                "caption": "Сколько на самом деле стоит решение при разном размере компании",
                "head": ["", "Стартап на 7 человек", "Компания на 200 человек"],
                "rows": [
                    ["Ошибочная трёхмесячная разработка", "≈25% годовой инженерной ёмкости; часто разница между «дошли до следующей вехи» и «не дошли»", "Квартал одной команды; растворяется в пересмотре дорожной карты"],
                    ["Ошибочный найм руководителя", "3–6 месячных окладов плюс решения, принятые за это время, — обычно самая крупная денежная ошибка ранней стадии", "Процедура оценки и повторный найм"],
                    ["Ошибочный выбор платформы", "Стоимость миграции приходится ровно на тот квартал, когда вы поднимаете раунд", "Планируется как двухлетняя программа модернизации"],
                    ["Два месяца нерешительности", "Два месяца ранвея, безвозвратно, и нечего показать совету директоров", "Сорванная цель квартала"],
                ],
            }),
            ("p", "Правильная единица измерения для стартапа — не деньги. Это <strong>недели ранвея на решение</strong>. Как только вы переводите в эту единицу, разовый проект стоимостью в несколько дней сжигания денег, который предотвращает трёхмесячный крюк, перестаёт выглядеть роскошью и становится страховкой с понятной ценой."),

            ("h2", "Что стартап на самом деле покупает"),
            ("p", "Не стратегическую презентацию. Не фреймворк. И не обзор рынка на 60 слайдов, который вы знаете лучше выступающего, — у этого сценария есть отдельная статья: <a href=\"../audit-nobody-reads/\">аудит, который никто не читает</a>."),
            ("p", "Платить стоит за узкие и конкретные вещи:"),
            ("ul", [
                "<strong>Распознавание сценария, в который вы ещё не попали.</strong> Человек, четыре раза наблюдавший, как это решение идёт не так, скажет, у какого из ваших трёх вариантов есть режим отказа, невидимый изнутри.",
                "<strong>Письменный ответ с цифрой.</strong> Не «рассмотреть возможность», а «делайте так, вот стоимость, вот что сломается, если мы ошиблись, вот триггер для отката».",
                "<strong>Снятие одного решения с вашей головы.</strong> Внимание основателя — самый дефицитный ресурс компании. Вынести один тяжёлый анализ на две недели часто ценнее самого анализа.",
                "<strong>Мнение без внутренней политики.</strong> Рекомендация вашей команды отчасти сформирована тем, кому потом это делать. У внешнего человека такого фактора нет.",
            ]),
            ("q", "Вы покупаете не знание. Вы покупаете снятие одной конкретной неопределённости, пока она не превратилась в три месяца разработки не того."),

            ("h2", "Четыре момента, когда это стабильно окупается"),
            ("h3", "1. Перед необратимым техническим или структурным решением"),
            ("p", "Модель данных, архитектура биллинга, базовая платформа, юридическая структура для нескольких стран. Здесь цена ошибки платится миграциями, а не рефакторингом. Несколько дней внешнего разбора до фиксации — самые эффективные деньги, которые тратит стартап."),
            ("h3", "2. Когда вы собираетесь нанять специалиста, которого не можете оценить"),
            ("p", "Классическая ловушка ранней стадии: нанять сильного специалиста в дисциплине, где никто в команде не отличает компетентность от уверенности. Купить два дня экспертизы на составление задания, разбор шортлиста и техническую проверку кандидатов радикально дешевле неверного найма. Заодно выяснится, нужен ли этот найм вообще."),
            ("h3", "3. Когда одна и та же тема обсуждается третий раз без результата"),
            ("p", "Повторяющийся неразрешённый спор внутри команды основателей почти никогда не связан с нехваткой информации. Обычно это проблема рамки: стороны оптимизируют разные переменные, и никто не сказал этого вслух. Это самый дешёвый возможный проект — и тот, который откладывают дольше всего."),
            ("h3", "4. Когда цифра движется, а объяснить никто не может"),
            ("p", "Отток, конверсия, стоимость привлечения, срок поставки. Если объяснение команды меняется каждый месяц, перед вами проблема измерения, переодетая в проблему результата. Внешний человек, не заинтересованный в прошлоквартальной версии событий, разбирается быстрее."),
            ("note", "Обратите внимание, чего в списке нет: «нам нужна стратегия». Стартап, которому внешний человек должен определить стратегию, имеет проблему с основателем, а не с консалтингом, и никакой проект её не решит."),

            ("h2", "Как ограничить проект, чтобы он не превратился в абонентку"),
            ("p", "Чаще всего всё портит не плохой консультант, а неограниченный проект, который тихо превращается в ежемесячный расход без привязки к решению — механика описана в статье <a href=\"../consulting-retainer-trap/\">ловушка консалтингового ретейнера</a>. Четыре ограничения это предотвращают:"),
            ("steps", [
                ("Сформулируйте вопрос одним предложением, заканчивающимся вопросительным знаком",
                 "«Строить биллинг у себя или интегрировать провайдера при ранвее в 14 месяцев?» Если сжать до одного предложения не получается, вы ещё не готовы покупать помощь — вы всё ещё решаете, что спрашивать."),
                ("Опишите результат как артефакт, а не как деятельность",
                 "«Письменная рекомендация с оценкой стоимости, двумя условиями, при которых она неверна, и триггером отката». Не «анализ и сопровождение»."),
                ("Зафиксируйте дату окончания раньше даты старта",
                 "До трёх недель проект остаётся острым. Свыше шести недель он начинает порождать работу, оправдывающую собственное существование, — если объём действительно этого не требует."),
                ("Договоритесь письменно, что будет после",
                 "По умолчанию: проект закончился, решение ваше. Любое продолжение — новая работа с отдельным объёмом. Проговорите это на старте, и дрейф не начнётся."),
            ]),

            ("h2", "Когда основателю не нужен консультант"),
            ("p", "Быть полезным здесь означает сказать, когда ответ «нет». Не нанимайте никого, если:"),
            ("ul", [
                "<strong>Вы уже знаете ответ и хотите прикрытия.</strong> Покупка внешнего подтверждения уже принятого решения — самая дорогая форма прокрастинации.",
                "<strong>Проблема в том, что вы не поговорили с достаточным числом клиентов.</strong> Никакой внешний человек не заменит двадцать разговоров, которых не было. Это самая частая ошибка диагноза на предпосевной стадии.",
                "<strong>Внутри некому применить ответ ближайший квартал.</strong> Ответ, приходящий раньше, чем появляется ёмкость его использовать, вырождается в документ.",
                "<strong>Вы хотите, чтобы кто-то поуправлял командой вместо вас.</strong> Это найм или отложенный разговор, а не проект.",
                "<strong>Бюджет заметно укоротит ваш ранвей.</strong> Если стоимость больше примерно недели сжигания, проект обязан быть привязан к решению, которое стоит дороже недели сжигания. Обычно так и есть. Иногда нет — проверьте.",
            ]),

            ("h2", "Как за один созвон отличить полезного консультанта от дорогого"),
            ("p", "За тридцать минут можно получить много сигнала, если слушать правильные вещи. Полный чек-лист — в статье <a href=\"../how-to-choose-a-consultant/\">как выбрать бизнес-консультанта</a>; короткая версия для основателей:"),
            ("ul", [
                "<strong>Он сужает или расширяет?</strong> Полезный человек весь созвон делает ваш вопрос меньше и конкретнее. Продающий — больше.",
                "<strong>Называет ли он сценарий, при котором отговорит вас от проекта?</strong> Если такого сценария нет, перед вами продавец деятельности.",
                "<strong>Спрашивает ли он, что произойдёт с ответом?</strong> Хороший консультант хочет знать, кто будет внедрять и есть ли этот человек в разговоре. Плохому знать не нужно, потому что результат — это отчёт.",
                "<strong>Может ли он описать свой провал конкретно?</strong> Конкретно — это названные ограничения и неверная предпосылка, а не «клиент был не готов».",
                "<strong>Тот ли человек на созвоне, который будет делать работу?</strong> На стартаперских бюджетах это важнее размера компании — см. <a href=\"../one-person-consulting-studio/\">аргумент про студию из одного человека</a>.",
            ]),

            ("h2", "Основатели, которые пользуются этим хорошо"),
            ("p", "Они не отдают решения наружу. Они покупают вторую, более острую пару глаз для одного решения, ошибиться в котором с первого раза слишком дорого, — и оставляют решение себе."),
            ("p", "Основатели, избегающие консалтинга, обычно избегают не расхода. Они избегают мысли, что кто-то снаружи может увидеть проблему быстрее них. Инстинкт понятный — и дорогой: он превращает двухнедельный вопрос в трёхмесячную разработку."),
            ("p", "Вам не нужен ретейнер. Вам нужен человек на один сложный вопрос, в один момент, когда это реально важно, с датой окончания, записанной до старта."),
        ],
    },
    takeaways={
        "en": [
            "Price decisions in weeks of runway, not in money — that conversion is what makes a one-off engagement obviously cheap or obviously wrong.",
            "The four reliable moments: before an irreversible commitment, before hiring a skill you can't evaluate, after the third unresolved debate, and when a metric moves unexplained.",
            "Buy a written answer with a number and a reversal trigger, never \"analysis and support.\"",
            "Fix the end date before the start date; agree in writing that the engagement ends with the decision.",
            "Don't hire if you want cover for a decision you've made, if the real gap is customer conversations, or if nobody can act on the answer this quarter.",
            "In the first call, a useful consultant makes your question smaller and can name a case where they'd tell you not to proceed.",
        ],
        "ru": [
            "Считайте решения в неделях ранвея, а не в деньгах — этот пересчёт сразу показывает, дёшев проект или бессмыслен.",
            "Четыре надёжных момента: перед необратимым решением, перед наймом специалиста, которого вы не можете оценить, после третьего безрезультатного спора и когда метрика движется без объяснения.",
            "Покупайте письменный ответ с цифрой и триггером отката, а не «анализ и сопровождение».",
            "Фиксируйте дату окончания раньше даты старта и письменно договаривайтесь, что проект заканчивается вместе с решением.",
            "Не нанимайте, если хотите прикрытия для уже принятого решения, если реальный пробел — в разговорах с клиентами или если применить ответ в этом квартале некому.",
            "На первом созвоне полезный консультант делает ваш вопрос меньше и может назвать случай, когда отговорил бы вас от проекта.",
        ],
    },
    faq={
        "en": [
            ("Can a seed-stage startup actually afford a consultant?",
             "The right comparison is not fee versus bank balance, it is fee versus the cost of the decision. Convert both into weeks of runway: if a short engagement costs a few days of burn and prevents a three-month build in the wrong direction, it is one of the cheapest purchases available. If the fee exceeds roughly a week of burn and isn't tied to a decision worth more than that, skip it."),
            ("What should a startup consulting engagement produce?",
             "A written recommendation containing a specific action, a cost estimate, the two conditions under which the recommendation is wrong, and a trigger for reversing it. If the deliverable is described as \"analysis and support\" rather than an artefact, the engagement has no defined end and will drift."),
            ("How long should an engagement be?",
             "Under three weeks keeps it sharp. Beyond six weeks, work starts being generated to justify the engagement unless the scope genuinely requires it. Fix the end date before the start date."),
            ("When should a founder NOT hire a consultant?",
             "When they already know the answer and want external cover; when the real gap is that they haven't spoken to enough customers; when nobody internally can act on the answer this quarter; when they're avoiding a management conversation; or when the fee would meaningfully shorten runway without being attached to a decision of equal value."),
            ("Consultant, advisor or fractional executive — what's the difference for a startup?",
             "A consultant answers a bounded question and leaves; an advisor gives recurring low-intensity access to judgement, usually for equity or a small fee; a fractional executive owns an operating function part-time. Use a consultant for a decision, an advisor for ongoing perspective, a fractional executive when the gap is capacity rather than knowledge."),
            ("How do I judge a consultant in a single 30-minute call?",
             "Watch whether they make your question smaller or larger, whether they can name a scenario in which they'd advise against the project, whether they ask who will implement the answer, and whether the person on the call is the person who will do the work."),
        ],
        "ru": [
            ("Может ли стартап на ранней стадии реально позволить себе консультанта?",
             "Сравнивать нужно не стоимость и остаток на счёте, а стоимость и цену решения. Переведите оба в недели ранвея: если короткий проект стоит несколько дней сжигания и предотвращает три месяца разработки не в ту сторону, это одна из самых дешёвых покупок вообще. Если стоимость больше примерно недели сжигания и не привязана к решению такой же ценности — не нужно."),
            ("Что должно быть результатом консалтингового проекта для стартапа?",
             "Письменная рекомендация с конкретным действием, оценкой стоимости, двумя условиями, при которых она неверна, и триггером отката. Если результат описан как «анализ и сопровождение», а не как артефакт, у проекта нет определённого конца и он будет дрейфовать."),
            ("Какой длины должен быть проект?",
             "До трёх недель он остаётся острым. После шести недель начинает порождаться работа ради оправдания проекта, если объём действительно этого не требует. Фиксируйте дату окончания раньше даты старта."),
            ("Когда основателю точно не нужен консультант?",
             "Когда ответ уже известен и нужно внешнее прикрытие; когда реальный пробел — в недостатке разговоров с клиентами; когда применить ответ в этом квартале внутри некому; когда откладывается управленческий разговор; когда стоимость заметно укорачивает ранвей и не привязана к решению сопоставимой цены."),
            ("Консультант, советник или фракционный руководитель — в чём разница для стартапа?",
             "Консультант отвечает на ограниченный вопрос и уходит; советник даёт регулярный доступ к суждению малой интенсивности, обычно за долю или небольшую плату; фракционный руководитель ведёт функцию на part-time. Консультант нужен под решение, советник — под постоянную оптику, фракционный руководитель — когда не хватает не знания, а ёмкости."),
            ("Как оценить консультанта за один тридцатиминутный созвон?",
             "Смотрите, делает ли он ваш вопрос меньше или больше, может ли назвать сценарий, при котором отговорит вас от проекта, спрашивает ли, кто будет внедрять ответ, и тот ли это человек, который будет делать работу."),
        ],
    },
)
